### ISSUE TITLE
Issues with pillow templates and choosing to use the same look for both sides of the pillow

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#191]
Create a pillow, size does not matter. Choose 4 image front template, 2 image back template. After selecting photos and arranging for the front, tap next. User is asked if they want to use the same look for the back side of the pillow, even though I only had the option to select two images. Duplicating the front would put 4 images on both sides. We should either remove the same look option, or add the option for 4 images on the back of the pillow.

**Comment by perisicboro** [comment]
@itscam Fixed in latest build.
