### ISSUE TITLE
LOW PRIORITY: 4 coasters selection has +/- which will always error

### ISSUE THREAD

**Issue by briantemple** [printdotio/printio-ios-sdk#228]
Flow requires a user to select 4 images to proceed to screen, and then presents an option to add more. None can be added, unless one is removed.

If +/- is presented, the UI should allow a user to add/remove to reach a multiple of four.

![img_0913](https://cloud.githubusercontent.com/assets/303257/4210046/8cea6d00-3870-11e4-81a5-328ca20749e4.PNG)

**Comment by AustenB** [comment]
Fixed
