### ISSUE TITLE
iPAD: Status bar not hidden on iPad 

### ISSUE THREAD

**Issue by barnbucket** [printdotio/printio-ios-sdk#25]
We have turned the status bar off in the SDK.  The status bar is not being displayed on iphones as expected.  On the ipad mini (non-retina) we are still seeing the status bar.  

Attached are screenshots of what this looks like.  It looks particularly bad on the product edit pages.
![35013a88-5254-43d2-a8bb-4f2f779017a6_zps5h4vg9ri](https://cloud.githubusercontent.com/assets/5324780/3461496/a3892b06-0223-11e4-9b0d-d87704e88287.PNG)
![dc188e56-ba21-475c-98b1-4188501d018b_zpser0onqms](https://cloud.githubusercontent.com/assets/5324780/3461499/b1495bb2-0223-11e4-8bfd-9a3a56560a9f.PNG)

**Comment by AustenB** [comment]
@barnbucket we made one change that might fix it: please retest

**Comment by AustenB** [comment]
@itscam please fix

**Comment by AustenB** [comment]
Test
