### ISSUE TITLE
Large file uploads to Framework

### ISSUE THREAD

**Issue by bdparrish** [printdotio/printio-ios-sdk#261]
I was wondering if there was anything in the works to accommodate those that want to pass through pictures that are large files from our internal API?  We have pictures that would be taken with the phone, but I would like to not have to upload 10 12 Mb files to the framework for preview purposes.  Is there a way to send a thumbnail  for preview purposes and a url of the location to the larger image?

**Comment by perisicboro** [comment]
```Objective-C
setImages:(NSArray *)images
```

accepts UIImage, NSString (image url), ALAsset and PHAsset in latest sdk version.
