### ISSUE TITLE
Low: Pre-uploaded images + thumbnails when using `setImages`

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#267]
In our use case we pre-upload the photos to a remote server in the background and then send them to the SDK using `setImages`. If I specify the local images then the SDK would re-upload them, if I specify the remote urls then it would take time for the SDK to show the thumbnails. Is there a way to specify both a remote url and a local one?

If not, then it could be a really useful feature.

**Comment by berendo** [comment]
> What I would like to do is (symbolic writing - please ignore specific interface):
> ```
> // Local thumbnail and pre-uploaded remote image
> NSArray *images = @[@{'thumb': uiimage_thumb, 'full': @'http:/google.com/img.jpg'}, ...]; 
> ```
This is _exactly_ what your Javascript SDK provides (see "Passing In Images" at https://www.gooten.com/platforms/javascript-sdk/documentation/web-widget/functionality, specifically the `pass in an object literal that allows for more options` example) and is absolutely a must for the iOS SDK as well. When high-resolution photos are on a backend service, consuming full-resolution download bandwidth just to derive local thumbnails is not reasonable.

I don't think this is a low-priority issue at all...

**Comment by perisicboro** [comment]
@berendo Consider using custom photo source instead, where you can set thumb url, and original image url: 

https://github.com/printdotio/printio-ios-sdk/blob/master/docs/Photo-Sources/custom_photo_sources.md

**Comment by berendo** [comment]
I have (before commenting on this issue). Unfortunately, there does not appear to be any way to use a custom photo source implementation to pass in a _pre-selected_ set of photos.

**Comment by perisicboro** [comment]
@berendo Passing thumb url along with original image url will be added to sdk. I will inform you when finish it and release new sdk version.

**Comment by berendo** [comment]
> Passing thumb url along with original image url will be added to sdk. I will inform you when finish it and release new sdk version.

That's fantastic to hear! In the meantime, if #529 (a.k.a. #274) can be addressed, I have a temporary hack that works, if the upload of the entire original can be cut out of the loop. Keep us posted, please!

**Comment by berendo** [comment]
> Fixed

@perisicboro I did not see any (obvious) updates to the online documentation. Could you point me toward (or elaborate here) the details on how to pass separate thumbnails vs original URLs to `[PrintIO setImages:]`? Thanks!

**Comment by berendo** [comment]
@perisicboro unfortunately, I'm still seeing the framework download the full-resolution images, even though I'm passing it `PIOPassedImage` instances with separate thumbnail and image URLs. For example, I confirmed at a breakpoint just before calling `setImages:` that I have:
```
(lldb) po images[0].imageUrl
▿ Optional<String>
  - some : "https://.../3/files/2246450100/media?signature=0f65eb8c321dcb05ac12b5826517c5dccb0584f7&v=4&auto_rotate=true"

(lldb) po images[0].thumbnailUrl
▿ Optional<String>
  - some : "https://.../3/files/2246450100/thumbnails/0f65eb8c321dcb05ac12b5826517c5dccb0584f7/s1280/thumbnail.jpg?v=4"
```
and yet, as soon as I select a product and the thumbnails have to be rendered, there's a noticeable delay and then I see:
```
... [17/Aug/2017:06:04:33 +0000] "GET /3/files/2246450100/media?signature=0f65eb8c321dcb05ac12b5826517c5dccb0584f7&v=4&auto_rotate=true HTTP/1.1" 200 2653379 826115 "-" "MysteryHouse/6.3.2-rc CFNetwork/811.4.18 Darwin/16.6.0" - - -
```
in our API server logs.

To further corroborate this, I've passed `file://` URLs for `thumbnailUrl` (since our app already has locally-cached assets) and I still see the downloads of the originals from the API server.

**Comment by perisicboro** [comment]
@berendo Of course SDK downloads full res images, because Image Editor works with full res images. Thumbs are used in Photo Selection only.

**Comment by berendo** [comment]
There were no images edited - I only got as far as photo and quantity selection. What's the point of downloading the full resolution originals if the upload of those are going to be suppressed given #274 has been fixed (again)?

**Comment by perisicboro** [comment]
Next screeen after photo selection is Product Editor (Image Editor) where we use downloaded images, not thumbnail

**Comment by berendo** [comment]
I really don't understand why the full resolution originals need to be downloaded, given your backend will simply be given the URL to get the images from anyway. It is really not acceptable to expect 10+ MB JPEG originals to be downloaded to a mobile device just to order prints. We just want this to work like your JavaScript SDK.

**Comment by perisicboro** [comment]
The point of downloading is to give user ability to customize product with original image, so for example he can see how deep he can zoom, and to have real preview of product. Your responsibility is to manage image size on your side.

**Comment by perisicboro** [comment]
Imagine, that you have thumbs in this editor:

![simulator screen shot aug 17 2017 9 38 19 am](https://user-images.githubusercontent.com/6410345/29401046-d8371f80-832f-11e7-9fc4-9248fb1d76da.png)
![simulator screen shot aug 17 2017 9 38 34 am](https://user-images.githubusercontent.com/6410345/29401049-da8772a8-832f-11e7-8596-1df7f64d4138.png)

**Comment by berendo** [comment]
No, I'm sorry, this makes no sense whatsoever. First of all, the reason we want to provide a separate "thumbnail" URL is because we already have pre-downloaded/high-resolution images available. The framework should use those and, if the user zooms in beyond the scale afforded by the "thumbnail," _then_ download the full resolution original. Commons flows don't have the user zooming into the images much at all. Waiting for the download of 10+ full resolution images is a very bad user experience.

Again, why can't this be made consistent with what your JavaScript SDK does? It appears to correctly use the thumbnail URLs for all visualization within the web app, passing the full resolution image solely by URL (not uploading), and wholly avoiding the download of the full resolution image to the browser.

**Comment by berendo** [comment]
> Imagine, that you have thumbs in this editor:

Sure, but, first of all, you're taking the term "thumbnail" too literally. As I said before, in our case, they are quite high resolution (sometimes even full resolution) and have been already downloaded and cached by other parts of our app, so we'd like to use them as much as possible. The framework is free to download anything higher resolution if the user enters an editing context that is not served sufficiently by the provided images. But, having the original fetched as soon as the user needs to adjust quantities of a few 5x7 prints that are already visualized as fairly small UI elements when we've provided 2048-pixel thumbnails is not acceptable.

Second of all, I think you really are ignoring the user experience problem of having the user wait for the download of 10+ full resolution photos, each of which can be 10+ MB in the case of DSLR-captured images. This gets even more compounded if the user is not on Wi-Fi, but cellular, and data usage concerns also enter the calculus. Our app is a completely online/offline capable app, which intelligently prefetches the likely-to-be used portions of the use's photo library in varying degrees of resolution, and we'd like to benefit from that by skipping the long delay after the product selection phase.

**Comment by berendo** [comment]
I have re-re-verified that your Javascript SDK does _not_ fetch the full-resolution original at this step:

![image](https://user-images.githubusercontent.com/1772903/29428299-8c1ce2e4-8341-11e7-96d2-8be479ba6421.png)

or even if I go deeper into the cropping editor:

![image](https://user-images.githubusercontent.com/1772903/29428320-9e8f6820-8341-11e7-95fc-50706d4743cc.png)

In using the Javascript SDK, we use the same methodology of providing a high-resolution "thumbnail" URL for the UI and a full-resolution original for production, and the "thumbnail" is used by the UI and the production was is fetched _only_ by the Gooten backend.

This is the behavior that should be implemented in the iOS SDK as well.

**Comment by perisicboro** [comment]
@berendo So, I will implement it in SDK on this way:
- if you pass in `imageUrl` and `thumbUrl`, `thumbUrl` will be downloaded and used for editing, while `imageUrl` will be only forwarded as print image url
- if you pass in only `imageUrl` , that image will be downloaded and used for editing and will be forwarded as print image url

**Comment by berendo** [comment]
> * if you pass in imageUrl and thumbUrl, thumbUrl will be downloaded and used for editing, while imageUrl will be only forwarded as print image url

That would be great, thank you.

I doubt you'd go out of your to make this impossible, but I'll mention anyway: please let `thumbUrl` also allow `file:` URL scheme as well. Based on what I've observed, I think the instantiation of the thumbnail within the frameworks involves an `[NSData dataWithContentsOfURL:]`, in which case `file:` scheme support should fall out for free.

**Comment by perisicboro** [comment]
> @berendo So, I will implement it in SDK on this way:

> if you pass in imageUrl and thumbUrl, thumbUrl will be downloaded and used for editing, while  imageUrl will be only forwarded as print image url
if you pass in only imageUrl , that image will be downloaded and used for editing and will be forwarded as print image url

Unfortunately, this feature isn't in our plans right now, so I need to postpone this implementation for now.

**Comment by berendo** [comment]
> Unfortunately, this feature isn't in our plans right now, so I need to postpone this implementation for now.

Wow, that's disappointing... I'll proceed with my monkey-patch of the SDK externally via the Objective-C runtime to do the right thing™ as it is unusable for our application in its current state. I'd strongly suggest you guys prioritize this bug to bring the functionality to par with the Javascript SDK.
