### ISSUE TITLE
Low: Image passed in displayed on layout selection but blurry and no frame

### ISSUE THREAD

**Issue by barnbucket** [printdotio/printio-ios-sdk#273]
When passing in an image it is displayed on the Choose photo & layout design step.  It is a nice touch to display the photo selected. It is showing up a bit blurry and it is not displayed in the frame. 

Here is a screen shot:
![0c161dec-f7e7-49c9-8053-1b4943d69750_zpspwu9naee](https://cloud.githubusercontent.com/assets/5324780/4638012/336ad32e-53f4-11e4-97eb-77cd163b93be.PNG)

**Comment by AustenB** [comment]
@barnbucket we are removing this feature in next versions. We will be changing it to be more useful
