### ISSUE TITLE
Images are downloaded and re-uploaded on client when image urls are passed to setImages

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#274]
When we use `setImages` and pass publicly available URLs, what seems to be happening is:
1. SDK downloads these images to client for preview (full res)
2. SDK uploads these images to PrintIO storage from client

There is a significant bandwidth and UX impact when in fact the upload (2) can be performed by PrintIO on the server side. The download (1) can be avoided as well but this relates to another ticket #267 . In fact we have the thumbnails available as public urls as well.

In our use case, we pre-uploaded the photos for better user experience but we're having a hard time to make use of it using this SDK.

**Comment by berendo** [comment]
The issue appears to have regressed - @Xyand are you still actively using the `PrintIO` framework?

**Comment by perisicboro** [comment]
@berendo I will take a look at this asap, and inform you when fix it.

**Comment by berendo** [comment]
> @berendo I will take a look at this asap, and inform you when fix it.

Thank you! It is kind of a show-stopper for us right now.

**Comment by perisicboro** [comment]
@berendo This is fixed now. Fix will be available in next sdk update, in a day or two.

**Comment by berendo** [comment]
Looking forward to it @perisicboro!

**Comment by perisicboro** [comment]
@berendo Fixed in sdk v1.8.40(38)

**Comment by berendo** [comment]
Looks good - I was able to confirm that the originals were fetched by Gooten's backend servers without being uploaded from the iOS device.
