### ISSUE TITLE
Medium Missing option to add more photos in the multi image edit view

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#292]
There is no way to add more photos during multi image customization screen (not documented). The equivalent customization screen for other products allows it.

![ios simulator screen shot oct 31 2014 12 22 50 am](https://cloud.githubusercontent.com/assets/1929813/4853203/ca3a30d8-6083-11e4-9fea-0882f8928d67.png)

(btw, notice that the title isn't centered)

**Comment by AustenB** [comment]
@perisicboro lets add the tap to show replace photo to this page like we added for photobooks -> tapping replace photo would show the add a photo page
