### ISSUE TITLE
LOW: Separate price from currency in `PrintIOWidgetOnCloseWithData` order_data

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#309]
Currently the prices take the form of "$10.11". It is unclear which currency has been used and parsing is needed to get the numeric value itself.

I suggest having both price and currency fields.

**Comment by nmarkovic04** [comment]
@Xyand Are you referring to the ship options prices or the overall price? I've split the overall price into value and currency, leaving the old field(compatibility), like so:

"overall" = "$18.27";
"overall_currency" = "$";
"overall_value" = "18.27";

**Comment by AustenB** [comment]
@Xyand confirmed fixed
