### ISSUE TITLE
Country change doesn't reflect when doing so in PIO_SCREEN_PRODUCT_DETAILS

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#318]
When changing country in the product details screen it doesn't update the selected country and always seem to update the product. Some change does take place as when the screen us reopened again the new country is shown.

Relevant code:
```
[printIO showCountrySelectionOnScreen:PIO_SCREEN_PRODUCT_DETAILS backgroundColor:teal];
...
...
[printIO goToProductId:code];
[printIO open];
```

Screenshot:
![ios simulator screen shot nov 23 2014 4 06 31 pm](https://cloud.githubusercontent.com/assets/1929813/5157806/405df740-732b-11e4-92b3-df231d773d60.png)

**Comment by AustenB** [comment]
@Xyand can you send init code to boro@print.io

**Comment by AustenB** [comment]
@Xyand are you setting the country -> if so this likely removed the ability to edit... I am closing this issue -> send the init code in full to me and I can likely find the issue
