### ISSUE TITLE
Unavailable delivery countries

### ISSUE THREAD

**Issue by mattmcneeney** [printdotio/printio-ios-sdk#320]
When the user opens the PrintIO SDK via the iOS app, the user is presented with a long list of countries to deliver to. Whilst this in itself is not a problem, clicking on most of these countries results in a "Currently not supported" message. Can we hide these unsupported delivery destinations?

**Comment by AustenB** [comment]
@mattmcneeney They should work now

**Comment by AustenB** [comment]
@mattmcneeney confirming this works
