### ISSUE TITLE
Little bug in Products list. Prints picture not showing up.

### ISSUE THREAD

**Issue by felix-systems** [printdotio/printio-ios-sdk#324]
Hi, there is a little bug on the Products list. As you can see in the screenshot, the Prints picture is not showing up. In one column list it's ok, though. 
![products list](https://cloud.githubusercontent.com/assets/9982169/5267783/0e6ae646-7a54-11e4-91dc-b842cc431d77.jpg)

**Comment by AustenB** [comment]
Ready to test Feb 20th
