### ISSUE TITLE
Estimated arrival date is 3 days from order

### ISSUE THREAD

**Issue by briantemple** [printdotio/printio-ios-sdk#327]
Placed this order today (12/4) and noticed the estimated arrival date reported to customers in the order confirmation is 3 days from now (12/7). Unless all orders are being overnight shipped, this will give customers an unrealistic expectation of when to receive their products.

* Order details have been redacted from this image. Issue in question circled in red.
![img_0958](https://cloud.githubusercontent.com/assets/303257/5308208/eac05792-7bd1-11e4-8e63-50c031c239af.PNG)

**Comment by AustenB** [comment]
@itscam to confirm
