### ISSUE TITLE
bundle size is huge

### ISSUE THREAD

**Issue by da1ssk** [printdotio/printio-ios-sdk#330]
The size of PrintIOBundle.bundle is 11.4mb. Is there any way to reduce the size?

**Comment by yyjim** [comment]
We are having same issue. Our app will be over 50mb after integrate the sdk.
Two suggestions on how to reduce the size:
1) make image and font assets downloadable instead of built into the SDK
2) limit product offerings.

**Comment by perisicboro** [comment]
Bundle size is reduced to 5mb in this version:
https://github.com/printdotio/printio-ios-sdk/releases/tag/1.0.45-dev

**Important (for now):
If you use smaller size bundle, 'Add text' feature will be auto-disabled in SDK.**

**Comment by AustenB** [comment]
@yyjim @da1ssk hey guys. We released a version that has text in a separate bundle.  It cut the size in half. Let us know feedback
