### ISSUE TITLE
Images passed are not visible

### ISSUE THREAD

**Issue by pesquibr** [printdotio/printio-ios-sdk#342]
Hi all. I'm passing many urls of high resolution images through the setImages method, but just a few images are visible when I access the product images selection page for the first time. To see all images I have to wait a while and then access the page again. Could be the API accept urls of low resolutions images (used only for the product images selection) and urls of high resolutions (used for print the products) ? I think that this way the load of the images would be faster. Thanks.

**Comment by AustenB** [comment]
@pesquibr is this fixed?

**Comment by pesquibr** [comment]
I resolved my problem using a different approach. I downloaded all images and I passed the local url of them to the setImages method. But would be a good option if the setImages method can accept a thumb image and a full image url too (as suggested on #267). I'll close this ticket. Thanks.
