### ISSUE TITLE
Enhancement: Increase the size of dragged image in product customization screen

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#344]
The thumbnails are quite small and when I drag an image I can't actually see it under my thumb. So in fact I have no indication of whether dragging has started or not. Making the dragged image larger would give a better indication that dragging has started.

**Comment by perisicboro** [comment]
Fixed 1.0.43-dev.

**Comment by AustenB** [comment]
@Xyand please confirm.

**Comment by Xyand** [comment]
Confirmed.

On Sun, Mar 22, 2015 at 10:11 PM, Austen Bernstein <notifications@github.com
