### ISSUE TITLE
Negative sums when using absolute $ coupon codes

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#345]
When using a coupon code that given discount that is greater than A. items total OR B. order total the checkout/payment screens show negative sums. This is very confusing and unclear what would happen when user actually pays... (we pay him?)

![ios simulator screen shot dec 19 2014 4 39 48 pm](https://cloud.githubusercontent.com/assets/1929813/5516283/aa5c8ef0-889c-11e4-98b8-7e15feff02bb.png)
![ios simulator screen shot dec 19 2014 4 40 06 pm](https://cloud.githubusercontent.com/assets/1929813/5516282/aa58a0e2-889c-11e4-9cf2-92a75aa1b320.png)

**Comment by AustenB** [comment]
@Xyand please confirm
