### ISSUE TITLE
Something wrong with passed image numbering

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#347]
Notice that the index is 2 but there is only 1 photo selected/passed...

![ios simulator screen shot dec 24 2014 1 17 55 pm](https://cloud.githubusercontent.com/assets/1929813/5548034/9ecb95c4-8b6f-11e4-9642-b37decc9c037.png)

**Comment by AustenB** [comment]
@nmarkovic04 Bug to fix

**Comment by AustenB** [comment]
@Xyand fixed ready to test
