### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#348]
I can't recreate it but from my production logs I see many crashes with the following message:

    ALL»EXCEPTION DESCRIPTION: NSGenericException Trace: __NSFastEnumerationMutationHandler PIOStringFromNetworkReachabilityStatus __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ -[N

`PIOStringFromNetworkReachabilityStatus` seems to be related with the SDK. The exception description is from my analytics platform so I don't have more details to offer.

**Comment by AustenB** [comment]
@Xyand we cant recreate - should we keep it?

**Comment by Xyand** [comment]
You can close it for now I see there are less crashes now. I'll reopen if it becomes an issue again.
