### ISSUE TITLE
"Prints" product does not work with only one image.

### ISSUE THREAD

**Issue by vrabeux** [printdotio/printio-ios-sdk#351]
Hi,

We are using version 1.0.33.

It seams that when using 
``` 

    [printIO setImages:images];

``` 
And that  images contains only one UIImage, the Prints product gets stuck loading just before the page where you should be editing. 
It seams to work fine if images contains more images.

Am I doing anything  wrong ?

**Comment by Xyand** [comment]
Did you try it on the latest version?

**Comment by vrabeux** [comment]
Solved it. Thanks.
