### ISSUE TITLE
Product coming soon are still displayed

### ISSUE THREAD

**Issue by vrabeux** [printdotio/printio-ios-sdk#352]
Hello,

The version I am using is 1.0.37.
In my code I have : 
``` 

[printIO hideComingSoonProducts:YES];

``` 

But sadly, product that are "coming soon" are still displayed.

Is there any other way to hide them ?

Thank you in advance.

**Comment by perisicboro** [comment]
@vrabeux Please send me initialization code for ```printIO``` and recipeIds you use. It this happening in staging or production mode?

**Comment by vrabeux** [comment]
Yes, I am using production mode. Aren't  the recipeIds a bit "private" to be posted on Github ?

**Comment by perisicboro** [comment]
@vrabeux Send me initialization code with recipeIds on boro@print.io

**Comment by AustenB** [comment]
@perisicboro where did we leave off with this one?

**Comment by perisicboro** [comment]
It works 100%. We tested it a lot, without any issue.

**Comment by itscam** [comment]
@AustenB @perisicboro We are still seeing this issue.

![img_0266](https://cloud.githubusercontent.com/assets/8051364/6646104/77f6409c-c987-11e4-9350-3790447b47ba.PNG)

Also, Much more to come at the bottom of the screen:
![img_0267](https://cloud.githubusercontent.com/assets/8051364/6646105/77f66f86-c987-11e4-943f-ca219e89eae9.PNG)

**Comment by AustenB** [comment]
Is this in staging or live?

In staging it shows coming soon products.

But to hide them on client side --> use this code to filter the products
out:


---- Lets have a quick call and have your developer send us the
initialization code he is using just to confirm everything (send this by
email)

**Comment by AustenB** [comment]
@perisicboro confirm this is fixed for tomorrow @Ivan1985
