### ISSUE TITLE
Very High: SDK files iCloud backup policy - app rejected

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#353]
One of our latest updates was rejected by the App Store review team. The reason was: "your app does not follow the iOS Data Storage Guidelines".

After inspecting actual file usage I found that there are some files used by the SDK:
````
/Document/print_me.sqlite
/Document/PrintMeCache/
/Documents/Products/
/Documents/Thumbs/
````

While the folders `Products` and `Thumbs` are actually user generated content the other files and folders are not and seem to violate Apple's guidelines unless explicitly marked not for backup in the SDK code.

Please either fix by changing default storage folder or confirm that these files and folders are explicitly marked as not for backup.

https://developer.apple.com/icloud/documentation/data-storage/index.html

**Comment by perisicboro** [comment]
Fixed in https://github.com/printdotio/printio-ios-sdk/releases/tag/1.0.40-dev

**Comment by Xyand** [comment]
@perisicboro How did you fix it? I see the `print_me.sqlite` is still kept under `/Documents`

**Comment by Xyand** [comment]
Ok, now it's official:

```
Hello,

Upon further review, we found that the application remains out of compliance with 2.23 and uses 2.8MB of storage at time of review. The print_me.sqlite is using the lion's share of the user's iCloud storage.

Specifically, the files stored in /Documents and in /Library are automatically backed up to iCloud unless specifically stated not to. Please mark any files that are not generated by the end-user as do not backup so the application can comply with the 2.23 guideline.
```

**Comment by perisicboro** [comment]
@Xyand '''print_me.sqlite" was marked for not to backup, but now it's moved to Cache. (1.0.41-dev)

**Comment by Xyand** [comment]
Great. Thanks.
