### ISSUE TITLE
[Question] SDK callbacks on orders

### ISSUE THREAD

**Issue by vrabeux** [printdotio/printio-ios-sdk#354]
Hi,
Is there a way to track if the user made an order and went through the all process ? (callback, delegate ?) 
We are interested in the following values per order : 

* MARGIN PARTNER ( Price - discount - price partner )
* REVENUE : ( amount in $ )
* DISCOUNT ( yes / no)

Thanks in advance,

**Comment by perisicboro** [comment]
@vrabeux We have option, how to track successful order: https://github.com/printdotio/printio-ios-sdk/blob/master/docs/quick_start_sample_code.md#delegate-method-printiowidgetonclosewithdata-provides-keyvalue-pairs

**Comment by AustenB** [comment]
@vrabeux closing - let me know of any questions
