### ISSUE TITLE
Very High: Products won't load on 1.0.40-dev

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#355]
This happens for many products with the new version. Reverting to 1.0.37 solves the issue (but there are other problems there). This screens shows when pressing the Create button:

![ios simulator screen shot jan 26 2015 5 28 41 pm](https://cloud.githubusercontent.com/assets/1929813/5902315/31dac476-a582-11e4-9a8a-2bcb996bc26c.png)

**Comment by Xyand** [comment]
Same on 1.0.41-dev

**Comment by AustenB** [comment]
Any ideas?

On Mon, Jan 26, 2015 at 10:55 AM, Albert <notifications@github.com> wrote:

> Same on 1.0.41-dev
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/355#issuecomment-71482771>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by perisicboro** [comment]
Fixed in 1.0.42-dev. Later will beupdated.

**Comment by Xyand** [comment]
Working.
