### ISSUE TITLE
Very High: Can't add items to cart with recent builds (1.0.42-dev and up)

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#358]
Adding a product shows an empty cart.

**Comment by BrainFeverMedia** [comment]
I'm seeing this same issue on the latest build 1.0.44. From product detail, tapping "Save to cart" switches to cart view but doesn't add product.

**Comment by perisicboro** [comment]
@Xyand @BrainFeverMedia Please send me initialization code on boro@print.io. Also it would be nice if you can capture a video.

**Comment by Xyand** [comment]
https://www.dropbox.com/s/75ru28s5o06l868/bug.mov?dl=0

**Comment by perisicboro** [comment]
@Xyand @BrainFeverMedia It should be fixed in https://github.com/printdotio/printio-ios-sdk/releases/tag/1.0.47-dev.

**Comment by Xyand** [comment]
Working.

**Comment by BrainFeverMedia** [comment]
1.0.47-dev is working now. Thx.
