### ISSUE TITLE
Duplicate orders in admin

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#359]
Our partner's customer placed one order, but two orders were generated in Admin: 114240 and 114242.
First order is accurate, but order 114242 has multiple copies of one image. Can someone please look into it! Thanks.
[order 114240](https://admin-v2.print.io/Home#/orders/114240/summary)
[order 114242](https://admin-v2.print.io/Home#/orders/114242/summary)

**Comment by Xyand** [comment]
@perisicboro @AustenB Any estimates when this will be resolved? We want to include the fix  in our next release. Thanks.

**Comment by perisicboro** [comment]
@mkontic @Xyand This is fixed in 1.0.44
