### ISSUE TITLE
Multiple copies of the same image

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#360]
It appears there is a bug that's causing one photo to multiply to every item in the order. 

Please see the examples: 

[Order 111471](https://admin-v2.print.io/Home#/orders/111471/images)
[Order 120607](https://admin-v2.print.io/Home#/orders/120607/images)

**Comment by Xyand** [comment]
I have some extra data from my logs from the first order if you need.

**Comment by Xyand** [comment]
This is urgent. Keeps happening in production.

**Comment by Xyand** [comment]
@perisicboro @AustenB Any estimates when this will be resolved? We want to include the fix  in our next release. Thanks.

**Comment by perisicboro** [comment]
@mkontic @Xyand This is fixed in versions from 1.0.44.

**Comment by AustenB** [comment]
@Xyand please confirm. Closing as our tests show it is good to go now

**Comment by Xyand** [comment]
It didn't happen recently.
