### ISSUE TITLE
PrintIO framework is too large

### ISSUE THREAD

**Issue by jjxtra** [printdotio/printio-ios-sdk#363]
The PrintIO framework and bundle add just over 20 MB to my bundle size. Is there anyway to configure this framework to dynamically pull assets from the web?

**Comment by perisicboro** [comment]
@jjxtra I can create version without fonts (used for text feature), and bundle size will be about 7mb smaller. Are you gonna use 'add text' feature?

**Comment by jjxtra** [comment]
No, I will not be using the add text feature, since that's already in You
Doodle. In fact, if you can make a build without any editing whatsoever
that would be ideal, since my app is already a full fledged image editor.

-- Jeff

**Comment by jjxtra** [comment]
My suggestions is this:

1] Provide a way to turn off all editing programatically
2] Provide a separate bundle without any editing assets

That would be very helpful.

**Comment by perisicboro** [comment]
Bundle size is reduced to 5mb in this version:
https://github.com/printdotio/printio-ios-sdk/releases/tag/1.0.45-dev

**Important (for now):
If you use smaller size bundle, 'Add text' feature will be auto-disabled in SDK.**

1] @jjxtra From docs (use this to remove editing tools): 
```[_printIO showToolbarInCustomizeProduct:NO backgroundImage:nil];```

**Comment by jjxtra** [comment]
When using the reduced size bundle (and turning off editing) I still got this in the log:

2015-02-17 10:07:18.571 YouDoodlePro[62152:2153404] PrintIO: Font 'Action_Man.ttf' not found in main bundle

**Comment by jjxtra** [comment]
This has reduced the size by 5 MB which is nice, however it still adds 15 MB to my binary size. Is there anything else than can be removed from the bundle or the framework to get the size down further?

**Comment by perisicboro** [comment]
I just tested binary size of our Sample App, and it increases binary size by 9MB (using bundle without fonts) and 13MB (using bundle with fonts). Right now we are not able to remove anything from sdk. Why are you so concerned about binary size? I think it's not a problem for today's devices.

**Comment by jjxtra** [comment]
Many of my users are on 8-16 GB devices and many don't have any space at all. That is one concern. The other is the time it takes to download an app. For a non-game app, people expect a very fast download and if that doesn't happen they may cancel the download. If there's nothing else that can be removed that's fine, I'm willing to try it at the current size.
