### ISSUE TITLE
Need access to UINavigationController for appearance proxy

### ISSUE THREAD

**Issue by jjxtra** [printdotio/printio-ios-sdk#364]
I need access to the UINavigationController that PrintIO is being displayed with. Any appearance proxy settings (navigation bar background image for example) are hard to change in PrintIO. Getting the view controller property to work (issue #362) might solve this problem.

**Comment by perisicboro** [comment]
@jjxtra I tested your code, and it returns non-nil navigation controller. About this "(navigation bar background image for example) are hard to change in PrintIO" in docs you will find that it's very easy to change it.

https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#navigation-bar

**Comment by jjxtra** [comment]
This works in the latest commit, we can close it.
