### ISSUE TITLE
Need hide close button option for printIO widget

### ISSUE THREAD

**Issue by pyaniero** [printdotio/printio-ios-sdk#365]
I'm using the 'viewController' method for retrieving the printIO view controller and presenting it in a tabBarController as an extra tab of my application. The issue is that the back button on the printIO navigation bar is being displayed when it has not functionality.
When the printIO view controller is presented modally, this button allows the user to dismiss it. However, in this case where the printIO VC is presented inside a tabbar, the back button should not be displayed until further navigation is done.

Having an option for automatically hide the back (close) button when the printIO navigation stack is empty would be great.

**Comment by perisicboro** [comment]
@pyaniero I will try to make that option. For now, please send me initialization code on boro@print.io

**Comment by pyaniero** [comment]
@perisicboro Thanks. I sent the email.

**Comment by perisicboro** [comment]
@pyaniero I made a new method which you can use:

```Objective-C
[printIO setBackButtonHidden:YES];
```

This will be available tonight, in version 1.0.46

**Comment by pyaniero** [comment]
@perisicboro I tested the new version, it works like a charm :) 
I really appreciate your quick help on this.

BTW, Do you know when it will be included in a stable version?

Thanks.

**Comment by perisicboro** [comment]
@pyaniero We're testing new version right now. I hope on Monday or Tuesday to publish new stable build.

**Comment by AustenB** [comment]
@pyaniero is this fixed for you now

**Comment by AustenB** [comment]
@pyaniero it is in the newest stable build
