### ISSUE TITLE
Currency converter works incorrectly in debug mode

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#366]
Is this intentional? 

![attachment_0](https://cloud.githubusercontent.com/assets/1929813/6225182/955facc8-b68f-11e4-86af-6ffe80dc6852.jpg)

**Comment by AustenB** [comment]
@Xyand explain what part is wrong

**Comment by Xyand** [comment]
The exchange rate is competent wrong in the scenario I described.

**Comment by AustenB** [comment]
We should document this for people on staging
