### ISSUE TITLE
Unable to by-pass photo sources view

### ISSUE THREAD

**Issue by jjxtra** [printdotio/printio-ios-sdk#369]
I'm trying to skip the photos sources view, but no matter what I try it always shows up.

I understand if this shows up for views with multiple photos, but for single photos views I would expect this view to not show up.

    [printIO disablePhotoSourcesWhenImagesArePassedIn:YES];

    [printIO enablePhotoSourcesInCustomizeProduct:NO];

    [printIO enableShareOnFacebookDeal:NO];

    [printIO disablePhotoSourcesForOnePhotoTemplate:YES];

    [printIO setImages:@[ image ]];
![ios simulator screen shot feb 17 2015 11 01 36 am](https://cloud.githubusercontent.com/assets/1271832/6234115/640a6ebe-b695-11e4-849d-ce4d7c32c65a.png)

**Comment by perisicboro** [comment]
@jjxtra Please send me complete initialization code on boro@print.io

**Comment by perisicboro** [comment]
Fixed in next release.

**Comment by AustenB** [comment]
@jjxtra please confirm this fix is seen on your side

**Comment by AustenB** [comment]
@jjxtra please confirm this fix is seen on your side
