### ISSUE TITLE
Test for CS Team

### ISSUE THREAD

**Issue by TheTriciaRussel** [printdotio/printio-ios-sdk#371]
@perisicboro  @AustenB @Ivan1985 
![side dressors for bed](https://cloud.githubusercontent.com/assets/7386911/6251235/bf6a60b8-b760-11e4-8fd6-1b7773cdab77.jpeg)

Please get back to me or handle directly and le tme know its done

**Comment by AustenB** [comment]
confused. But looks comfy.

On Wed, Feb 18, 2015 at 11:25 AM, TheTriciaRussel <notifications@github.com>
wrote:

> Assigned #371 <https://github.com/printdotio/printio-ios-sdk/issues/371>
> to @AustenB <https://github.com/AustenB>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/371#event-237768228>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by TheTriciaRussel** [comment]
it was a test i was showing CS how to ticket issues :)

Tricia Russel
Director of Business Development & Operations
Skype: triciarussel17
print.io



On Wed, Feb 18, 2015 at 11:27 AM, Austen Bernstein <notifications@github.com
