### ISSUE TITLE
How deselected passed images ?

### ISSUE THREAD

**Issue by pesquibr** [printdotio/printio-ios-sdk#372]
Hi all. I'm passing images using the method "setImages". I have noticed that all images are selected by default on product photo selection. But I would like that the behavior was all images deselected by default, so the user can select explicitly the wanted images. Is there a way to do that ?

**Comment by perisicboro** [comment]
@pesquibr Right now there's not option to deselect images by default, but we will work on it. I expect in next release, this to be fixed.

**Comment by nmarkovic04** [comment]
@pesquibr @perisicboro Method added. Closed.
```Objective-C
/*
  A flag that determines whether passed images are preselected on the 'Select Photos' screen.
 */
- (void)setPreselectPassedImages:(BOOL)shouldPreselectPassedImages;
```

**Comment by Xyand** [comment]
What is the default behavior? Is it different from the old behavior?

**Comment by pesquibr** [comment]
For me, the default behavior are all passed images deselected. Which release version the method "shouldPreselectPassedImages" will be available ?

**Comment by Xyand** [comment]
I'd appreciate it if you keep the default behavior the same way it was before adding this feature. Unless there is a good reason of course.

**Comment by nmarkovic04** [comment]
The default behavior will stay unchanged.

@pesquibr 
> Hi all. I'm passing images using the method "setImages". **I have noticed that all images are selected  by default on product photo selection.**


>For me, **the default behavior are all passed images deselected.** Which release version the method "shouldPreselectPassedImages" will be available ?

Can you explain how passed images are both selected and deselected for you?

**Comment by pesquibr** [comment]
Sorry, maybe I've expressed myself wrong. I said that currently the API select all passed images in selection of product images, but in my app I would like that all passed images are deselected. The method "setPreselectPassedImages" will solve my problem. Thanks.

**Comment by AustenB** [comment]
Is it fixed or what's the solution

**Comment by nmarkovic04** [comment]
Implemented. Available in next release.
