### ISSUE TITLE
iPAD: Add button is skewed

### ISSUE THREAD

**Issue by jjxtra** [printdotio/printio-ios-sdk#373]
See screenshot
![ios simulator screen shot feb 18 2015 11 09 33 am](https://cloud.githubusercontent.com/assets/1271832/6253617/0b81fc8c-b760-11e4-9f60-d8d838b25bbd.png)

**Comment by AustenB** [comment]
@jjxtra this is ipad support. Something we will look into. What ipad is this on?

**Comment by jjxtra** [comment]
iPad Air and simulator

**Comment by AustenB** [comment]
@jjxtra iPad is not formally supported right now. We will be working on it in the 2nd quarter. 

Is your app only for iPad?

**Comment by jjxtra** [comment]
No it's on both iPhone and iPad - a universal app. I suppose I could hide Print.IO on iPad, but in asking my users if they would like this feature, many of my iPad users (bigger spenders) have said they would really like it.

**Comment by jjxtra** [comment]
Regardless, I want proper iPad support before I put this in the App Store.

**Comment by AustenB** [comment]
Ok. That will be a few months away. We are happy to discuss additional
needs you have.

Is that the only iPad error you are finding? If so we could make that 1
fix.

On Thu, Mar 12, 2015 at 12:50 PM, Jeff Johnson <notifications@github.com>
wrote:

> Regardless, I want proper iPad support before I put this in the App Store.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/373#issuecomment-78524521>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by jjxtra** [comment]
There was the other issue I logged about the text going out of bounds too on #376. If you fixed that one as well, I might be able to release it.

**Comment by perisicboro** [comment]
iPad or Universal configuration is not yet supported. SDK works only in iPhone app configuration.
