### ISSUE TITLE
Add outline to shopping cart image

### ISSUE THREAD

**Issue by jjxtra** [printdotio/printio-ios-sdk#374]
Please add a single pixel black outline to the shopping cart icon that appears in the top right. When using a white navigation bar, the shopping cart icon vanishes.

**Comment by AustenB** [comment]
You can use your own icon.

**Comment by jjxtra** [comment]
I certainly can, but with a framework like this, it's nice to limit the number of steps necessary to get up and running.

**Comment by AustenB** [comment]
@jjxtra the shopping cart icon is black - can you show us a screen shot
