### ISSUE TITLE
[printIO setIconForShoppingCart:] does not work

### ISSUE THREAD

**Issue by jjxtra** [printdotio/printio-ios-sdk#375]
I'm calling [printIO setIconForShoppingCart:@"shopping_cart_icon" withNumberOfProducts:NO labelPosition:CGPointZero textColor:UIColor.whiteColor]; but my icon does not appear.

I've tried the following for the image path:

shopping_cart_icon
shopping_cart_icon.png
shopping_cart_icon@2x.png
[[NSBundle mainBundle] pathForResource:@"shopping_cart_icon" ofType:@"png"]

I've triple checked that my image is added to my project.

**Comment by perisicboro** [comment]
Fixed in next release.

**Comment by jjxtra** [comment]
Thanks, awesome!
