### ISSUE TITLE
iPAD: Text appears out of text areas

### ISSUE THREAD

**Issue by jjxtra** [printdotio/printio-ios-sdk#376]
On the first screen, the text is overflowing the bounds of the text areas. 
The lines also do not span the height of the image.

Screenshot attached.
![ios simulator screen shot feb 18 2015 4 15 52 pm](https://cloud.githubusercontent.com/assets/1271832/6258857/7e453bde-b789-11e4-9a56-2aedfa0a90c5.png)

**Comment by AustenB** [comment]
@jjxtra we don't support ipad today -- will look into this later in march.

**Comment by perisicboro** [comment]
iPad or Universal configuration is not yet supported. SDK works only in iPhone app configuration.
