### ISSUE TITLE
Unable to order product samples

### ISSUE THREAD

**Issue by NWagner592** [printdotio/printio-ios-sdk#378]
We are currently unable to order the following items:

Acrylic Prints
Bath Mats
Beach Towels*
Bottle Labels
Curtain Panels*
Desk Calendars*
Hoodies (Both Pull-Over and Zippered)*
Onesies*
Pet Bowls
Posters (Need one full bleed, one with a black border, and one with a white border)*
Stickers*
T-Shirts (We need samples of both DTG and screenprinted)
Tea Towels*
Toddler Clothing*
Wall Calendars
Wood Prints
(the ones with * are most important)

Any help resolving this & getting these samples ordered is greatly appreciated.

**Comment by AustenB** [comment]
Nash -> move this to the vendor board.

On Mon, Feb 23, 2015 at 11:46 AM, NWagner592 <notifications@github.com>
wrote:

> We are currently unable to order the following items:
>
> Acrylic Prints
> Bath Mats
> Beach Towels*
> Bottle Labels
> Curtain Panels*
> Desk Calendars*
> Hoodies (Both Pull-Over and Zippered)*
> Onesies*
> Pet Bowls
> Posters (Need one full bleed, one with a black border, and one with a
> white border)*
> Stickers*
> T-Shirts (We need samples of both DTG and screenprinted)
> Tea Towels*
> Toddler Clothing*
> Wall Calendars
> Wood Prints
> (the ones with * are most important)
>
> Any help resolving this & getting these samples ordered is greatly
> appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/378>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by NWagner592** [comment]
I don't know how to do that.

**Comment by TheTriciaRussel** [comment]
@NWagner592  here: https://github.com/printdotio/printio-vendors

**Comment by NWagner592** [comment]
@TheTriciaRussel I got a 404 error/ that page doesn't exist.
