### ISSUE TITLE
Add smaller version to pod

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#379]
It would be very nice if you could update pod to use smaller version as an option (subspec). See example in this spec file (IDFA and Core)

https://github.com/CocoaPods/Specs/blob/476b4f9b11beac13f3da56f99ae6cc897d480988/Specs/GoogleAnalytics-iOS-SDK/3.10/GoogleAnalytics-iOS-SDK.podspec.json

**Comment by AustenB** [comment]
@Xyand ready to test in next release
