### ISSUE TITLE
Cancel button is not clickable when when loading

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#380]
This button:
![img_0247](https://cloud.githubusercontent.com/assets/1929813/6430913/b43634f4-c027-11e4-948a-ca44db8fa56e.PNG)

**Comment by Xyand** [comment]
This mostly happens where there is no internet connection or when there are problems with the connection.

**Comment by Xyand** [comment]
Any updates?

**Comment by AustenB** [comment]
@Xyand will be available in the next release

**Comment by AustenB** [comment]
@Xyand please confirm. Thanks buddy
