### ISSUE TITLE
Metal Prints Error 

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#381]
HP customer has been trying to do order a metal print for the past 48 hr and keep getting an error.
She is using the app on an iPhone 6 plus "trying to do a 12 image metal print tried to auto populate the image and manually do the images. When doing manual the second space on the bottom from the left will never let me populate with an image and if auto populate I get the attached image."

Do you have ETA as to when this will be fixed?

![image1](https://cloud.githubusercontent.com/assets/10849553/6439927/49e4e06c-c0d8-11e4-9b17-afd258e4ae9b.PNG)

@perisicboro @bomberaya @AustenB

**Comment by perisicboro** [comment]
@Ivan1985 Please try to find which template has a bug.
@mkontic HelloPics app update will be in next 10-20 days.

**Comment by AustenB** [comment]
@mkontic can you see what size metal print this was for?

**Comment by mkontic** [comment]
@AustenB I don't have that info at the moment, but I just asked our customer. Will advise.

**Comment by mkontic** [comment]
@AustenB The Panoramic 6x24

**Comment by AustenB** [comment]
Fixed
