### ISSUE TITLE
Customize PrintIO Theme

### ISSUE THREAD

**Issue by UsmanINV8** [printdotio/printio-ios-sdk#383]
Hi Team PrintIO

We have integrated your SDK, everything is working fine. One thing we want to do, is that to customise the theme of SDK screens. The background, "Shipping to:" blue background. slide menu background etc.

That will be really good if one can customise these things. As we our application theme is totally different from theme of PrintIO. 

Thanks
Usman

**Comment by perisicboro** [comment]
@UsmanINV8 We support a lot of UI customization, please check these docs and see if you use something:

https://github.com/printdotio/printio-ios-sdk/blob/master/docs/specific_page_methods.md
https://github.com/printdotio/printio-ios-sdk/blob/master/docs/xml_customization_new.md

**Comment by AustenB** [comment]
@UsmanINV8 can you confirm you found everything you need?

**Comment by AustenB** [comment]
@UsmanINV8 can you confirm you found everything you need?

**Comment by UsmanINV8** [comment]
@AustenB Ya I have found everything. Thanks Team

**Comment by AustenB** [comment]
Y
