### ISSUE TITLE
How It Works screen title is "Breakout Commerce"

### ISSUE THREAD

**Issue by BrainFeverMedia** [printdotio/printio-ios-sdk#384]
The How it works screen title is "Breakout Commerce".

I searched through the docs and couldn't find any way to modify this. Let me know if I'm missing something.
I'm using setHowItWorksText to customize the screen text.
Thanks!
James

**Comment by perisicboro** [comment]
@BrainFeverMedia 

Use ```[self.printIO setHowItWorksText:@""];``` for setting text for how it works section, and ```[self.printIO setPayeeName:@""];``` to change title.

**Comment by BrainFeverMedia** [comment]
"setPayeeName" works. Thanks!
