### ISSUE TITLE
The image for the blanket didn't generate properly

### ISSUE THREAD

**Issue by jovana-kovacevic** [printdotio/printio-ios-sdk#385]
The image for this blanket wasn't generated properly - please see below and please advise
https://admin-v2.print.io/#/orders/144168/images
Thank you!

**Comment by perisicboro** [comment]
@jovana-kovacevic I can;t see the difference, where to look?

**Comment by jovana-kovacevic** [comment]
@perisicboro Hey Boro, Milena manually fixed this image. 
Thank you!

**Comment by perisicboro** [comment]
@jovana-kovacevic Ok :) Next time, save img manip command, and take few screenshots before someone fix the image, so we can fix it on our side.
