### ISSUE TITLE
Duplicate images on canvas

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#386]
Similar problem as before, order 144514. Customer uploaded 24 different images, but only one was generated. See the product preview vs. preview at 100%

@perisicboro @AustenB 

![image 1](https://cloud.githubusercontent.com/assets/10849553/6577289/f90ae78e-c73c-11e4-83b3-472d39ba2d38.jpg)

**Comment by AustenB** [comment]
This is a big bug. Where is it coming from?

**Comment by perisicboro** [comment]
@mkontic Which sdk version is this? this is an old bug, and it's fixed in latest sdk.

**Comment by mkontic** [comment]
@perisicboro @AustenB HelloPics/19 CFNetwork/711.1.16 Darwin/14.0.0

**Comment by AustenB** [comment]
@mkontic lets see if it happens again
