### ISSUE TITLE
Push Notifications pop-up

### ISSUE THREAD

**Issue by vrabeux** [printdotio/printio-ios-sdk#387]
Hi,

We have a strange push-notification popup on latest version : 
![image1](https://cloud.githubusercontent.com/assets/1539818/6594753/516f9e0e-c7e4-11e4-9b32-7a72507203d1.PNG)

I there anyway to hide it ?

Thanks a lot in advance.

**Comment by AustenB** [comment]
@vrabeux you need to set payee name and it will display as your name.

**Comment by nmarkovic04** [comment]
```Objective-C
@interface PrintIO : NSObject
/**
 Set payee name for order processing

 @param payeeName Payee name
 */
- (void)setPayeeName:(NSString *)payeeName;

**Comment by AustenB** [comment]
@vrabeux this solved it correct/
