### ISSUE TITLE
High: Nothing happens after selecting size for Tote Bags and Canvas Minis

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#388]

**Comment by AustenB** [comment]
@Xyand what version of the SDK?

Is this on staging or live?

Can you show what happens?

**Comment by perisicboro** [comment]
@Xyand Is this still happening? Please provide us more info, so we can fix it before next release.

**Comment by AustenB** [comment]
@Xyand please follow up

**Comment by AustenB** [comment]
@Xyand we cannot recreate this. Let us know if it still occurs. Closing for now.

**Comment by Xyand** [comment]
@AustenB Please reopen. I tested it again with the latest build (1.1.9). See video:

https://www.dropbox.com/s/h0dabd5xn0ydpzz/Untitled.mov?dl=0

**Comment by AustenB** [comment]
@Ivan1985 can you please try to recreate this. 

@Xyand is this on staging or live? Is this using your recipeid? That product shouldn't be live for you until I add it for you.

**Comment by AustenB** [comment]
@Xyand we cant reproduce - can you provide logs?

**Comment by Xyand** [comment]
@AustenB @Ivan1985 This may explain. Can you please add it to my recipe? I would retest.

Live. My recipeid

**Comment by perisicboro** [comment]
@Xyand Please can you send me a log from this step to boro@print.io

**Comment by Xyand** [comment]
done.

**Comment by Xyand** [comment]
Any updates?

**Comment by perisicboro** [comment]
@Xyand Fixed in v1.1.10-dev. It will be available today.

**Comment by Xyand** [comment]
How come I'm the only one who suffered from it?

**Comment by perisicboro** [comment]
@Xyand You use special combination of methods :)  Passed in images with disabled photo sources...
