### ISSUE TITLE
Changing 'Next' button text color

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#389]
Where can I configure the text color for the 'Next' button. It looks different from all other buttons.

![ios simulator screen shot mar 12 2015 11 11 56 am](https://cloud.githubusercontent.com/assets/1929813/6615080/66db9fc0-c8a9-11e4-9e64-6c53a0dc1fac.png)

**Comment by perisicboro** [comment]
@Xyand Use these two methods to customize "Next" and "Save to cart" buttons:
https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--setnavigationbarsavetocartbackgroundcolortitlecolorbuttonbackgroundcolorbuttontitlecolor

https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--navigationbarcolortitlecolorleftbuttonbackgroundcolorrightbuttonbackgroundcolortitlebuttonicon
