### ISSUE TITLE
Image quality warning doesn't show

### ISSUE THREAD

**Issue by Xyand** [printdotio/printio-ios-sdk#390]
I tried to use a tiny cropped image with the largest canvas wrap available.

**Comment by AustenB** [comment]
@Xyand was this for a single photo template -- what version of the SDK are you using also?

**Comment by Xyand** [comment]
Yes. 1.1.0

**Comment by AustenB** [comment]
@Xyand what is the resolution of the tiny image? It shows only if resolution is under 1/3 of size

**Comment by Xyand** [comment]
372x256

Originally this is a larger image that was cropped using the native Photos app.

**Comment by AustenB** [comment]
@Xyand can you show us a video/gif -- we are having trouble reproducing.

**Comment by AustenB** [comment]
@Xyand we are seeing it work on our side. 

It shows it on customization screen - not on photo sources screen

**Comment by Xyand** [comment]
I will retest.

Did you try taking a large image, cropping it with the native app and then
creating a product or did you just use my cropped image?

**Comment by AustenB** [comment]
@Xyand any luck recreating this?
