### ISSUE TITLE
Medium: Unnecessary screen for dog beds

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#391]
Newest SDK version, on production.

- Select dog bed, tap create it
- Select size and type

Observed: Another choose options page is displayed with a single image option, and then the user is automatically sent to the select photos screen. If you tap back, you can see the screen where you have only one option.

Can we simply remove this screen until more image options are available?

![5secondsapp 11](https://cloud.githubusercontent.com/assets/8051364/6630080/6f2a2c9c-c8da-11e4-9daf-e3c6d8e420f3.gif)

**Comment by AustenB** [comment]
We should be able to make it better. Hopefully we can get some nice
collages and design templates for it also

**Comment by perisicboro** [comment]
Fixed in next release.

**Comment by itscam** [comment]
Fix verified.
