### ISSUE TITLE
High: GIF and video files appearing as printable media from phone source

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#392]
Newest SDK, on production.

I was able to select GIF and video items for my print product. Before, these media items were removed from the album list. 

Also, there was no low-resolution warning for these thumbnail images, which should qualify as low-resolution.

**Comment by nmarkovic04** [comment]
You're right about GIFs and videos, we'll fix that one asap.

Regarding the low resolution, we're currently displaying the resolution warning if:
- image.width < imageRectOnProduct.width/3 OR
- image.height < imageRectOnProduct.height/3

**Comment by AustenB** [comment]
@itscam it displays the warning on the customization screen - not on the image sources screen. We will add it on image sources screen but only for 1) single photo templates and 2) only for the phone's photo source when we know resolution of image

**Comment by AustenB** [comment]
@itscam fixed in next release

**Comment by itscam** [comment]
@AustenB @nmarkovic04 I am able to select from GIF files from phone source on 1.1.9

**Comment by AustenB** [comment]
what about 1.1.10?

On Fri, Mar 27, 2015 at 2:08 PM, Cameron Bradley <notifications@github.com>
wrote:

> @AustenB <https://github.com/AustenB> @nmarkovic04
> <https://github.com/nmarkovic04> I am able to select from GIF files from
> phone source on 1.1.9
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/392#issuecomment-87036671>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by itscam** [comment]
There is no 1.1.10.

**Comment by AustenB** [comment]
Ok it should be coming shortly.

On Fri, Mar 27, 2015 at 3:42 PM, Cameron Bradley <notifications@github.com>
wrote:

> There is no 1.1.10.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/392#issuecomment-87068316>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by itscam** [comment]
@AustenB GIFs are still appearing in device media with build 1.1.12

**Comment by AustenB** [comment]
@itscam these shouldn't be showing now -> we tested this.

**Comment by itscam** [comment]
@AustenB Photo album contains three gifs and one video. GIFs are visible. 
![img_0379](https://cloud.githubusercontent.com/assets/8051364/7055072/07eecd92-ddfe-11e4-9be3-db1912724a4a.GIF)

**Comment by AustenB** [comment]
We don't see this on our side. This is confusing why. Are you using the
latest?

On Wed, Apr 8, 2015 at 4:47 PM, Cameron Bradley <notifications@github.com>
wrote:

> @AustenB <https://github.com/AustenB> Photo album contains three gifs and
> one video. GIFs are visible.
> [image: img_0379]
> <https://cloud.githubusercontent.com/assets/8051364/7055072/07eecd92-ddfe-11e4-9be3-db1912724a4a.GIF>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/392#issuecomment-91032708>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by itscam** [comment]
@AustenB Yes, this is 1.1.16. Again, this is from the phone source. GIFs and videos are not appearing in Photobucket albums.

Also, outside of the warning icon on the thumbnail, there was no resolution warning on the customization screen. I was able to complete an order with a very low-resolution GIF image. 

Can we add an explanation to the album thumbnail warning? Mention that it's a low-resolution image when tapped?

**Comment by AustenB** [comment]
Create a new ticket for the warnings -- will look into those as
enhancements for the next release.

On Wed, Apr 8, 2015 at 5:06 PM, Cameron Bradley <notifications@github.com>
wrote:

> @AustenB <https://github.com/AustenB> Yes, this is 1.1.16. Again, this is
> from the phone source. GIFs and videos are not appearing in Photobucket
> albums.
>
> Also, outside of the warning icon on the thumbnail, there was no
> resolution warning on the customization screen. I was able to complete an
> order with a very low-resolution GIF image.
>
> Can we add an explanation to the album thumbnail warning? Mention that
> it's a low-resolution image when tapped?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/392#issuecomment-91037504>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by itscam** [comment]
@AustenB Will do. Is there a known issue regarding the resolution warning being absent on the customization screen?

**Comment by AustenB** [comment]
Not on our side. Give me resolution sizes of input and product

**Comment by itscam** [comment]
No customization screen warning for 320 x 320 GIF image on 8x8 and 20x30 in framed prints, 36x36 canvas wrap.

**Comment by AustenB** [comment]
what about a non-gif image-- since maybe we can't read the size of that
one.
What about a regular image?

Thank you Cam

On Mon, Apr 13, 2015 at 3:45 PM, Cameron Bradley <notifications@github.com>
wrote:

> No customization screen warning for 320 x 320 GIF image on 8x8 and 20x30
> in framed prints, 36x36 canvas wrap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/392#issuecomment-92475229>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by itscam** [comment]
525x354 jpg image displayed resolution warning on select photos screen, but not on customize. What is the customize screen warning supposed to show?

**Comment by AustenB** [comment]
Was it a single photo template?

On Mon, Apr 13, 2015 at 6:41 PM, Cameron Bradley <notifications@github.com>
wrote:

> 525x354 jpg image displayed resolution warning on select photos screen,
> but not on customize. What is the customize screen warning supposed to show?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/392#issuecomment-92520512>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by itscam** [comment]
Yes.

**Comment by AustenB** [comment]
Than you dismissed the warning on page before.

Try multi photo & multi template -> should show on customize.
We don't warn user 2x for single template

On Mon, Apr 13, 2015 at 6:57 PM, Cameron Bradley <notifications@github.com>
wrote:

> Yes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/392#issuecomment-92526034>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by itscam** [comment]
Just tried multiple image templates for several products with low-res images, still no warning on the customize screen.

**Comment by AustenB** [comment]
Try changing the layout once on customize screen.

Otherwise -> ill talk with nikola tomorrow

On Mon, Apr 13, 2015 at 7:08 PM, Cameron Bradley <notifications@github.com>
wrote:

> Just tried multiple image templates for several products with low-res
> images, still no warning on the customize screen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/392#issuecomment-92529356>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio
