### ISSUE TITLE
Low/Medium: Number positioning in cart icon

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#393]
First screenshot shows where the cart item number was positioned in our last release. The second screenshot shows where the cart item number is positioned in the newest SDK. 

![fullsizerender 2](https://cloud.githubusercontent.com/assets/8051364/6631621/9dd2be92-c8ee-11e4-9cce-befba2554132.jpg)
![fullsizerender 3](https://cloud.githubusercontent.com/assets/8051364/6631623/9fd24564-c8ee-11e4-917c-2db83704063c.jpg)

**Comment by AustenB** [comment]
To confirm - this is only with iphone6 / iphone6+?

On Thu, Mar 12, 2015 at 9:34 PM, Cameron Bradley <notifications@github.com>
wrote:

> First screenshot shows where the cart item number was positioned in our
> last release. The second screenshot shows where the cart item number is
> positioned in the newest SDK.
>
> [image: fullsizerender 2]
> <https://cloud.githubusercontent.com/assets/8051364/6631621/9dd2be92-c8ee-11e4-9cce-befba2554132.jpg>
> [image: fullsizerender 3]
> <https://cloud.githubusercontent.com/assets/8051364/6631623/9fd24564-c8ee-11e4-917c-2db83704063c.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/393>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by itscam** [comment]
This is an issue on all devices as far as I can tell. This is from an iPhone 5:

![fullsizerender 4](https://cloud.githubusercontent.com/assets/8051364/6645951/048a6b5c-c986-11e4-95f6-c1aedecbfc31.jpg)

**Comment by perisicboro** [comment]
@itscam What method you use to set cart icon?

**Comment by koppacetic** [comment]
[self.printIO setIconForShoppingCart:[[NSBundle mainBundle]pathForResource:@"pb_icon_cart_black" ofType:@"png"]
                 withNumberOfProducts:YES labelPosition:CGPointMake(15, 6.5) textColor:[UIColor whiteColor]];
![pb_icon_cart_black](https://cloud.githubusercontent.com/assets/101262/6692819/b044adfc-cc94-11e4-9d9e-a0505fc576fd.png)

**Comment by perisicboro** [comment]
@itscam @koppacetic I know that you want to keep same initialization code, but we changed font size of products counter, and that requires changing label position.

Please try this position, it works perfect for me:
```[self.printIO setIconForShoppingCart:[[NSBundle mainBundle]pathForResource:@"pb_icon_cart_black" ofType:@"png"]
                    withNumberOfProducts:YES labelPosition:CGPointMake(14.0, 5.5) textColor:[UIColor whiteColor]];```
