### ISSUE TITLE
Low/Medium: Album text font change on Select Photos screen

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#394]
Top screenshot is from our production app, second screenshot is from the new SDK. The font has changed to the standard iOS font and doesn't match what we are using for the rest of the SDK. Is this something we can change?

![img_0305](https://cloud.githubusercontent.com/assets/8051364/6631736/5e7fb536-c8f0-11e4-8ba5-756cec249e01.PNG)![img_0304 1](https://cloud.githubusercontent.com/assets/8051364/6631739/697d7c02-c8f0-11e4-8f97-c68627b0eecc.PNG)

**Comment by AustenB** [comment]
Ready to test in next release

**Comment by itscam** [comment]
Fix verified.
