### ISSUE TITLE
Medium: Button colors on Select Photos screen have changed

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#396]
The Next button for our SDK should be orange, but it reverted to green on the newest SDK.

![img_0265](https://cloud.githubusercontent.com/assets/8051364/6646177/ffbdaede-c987-11e4-8778-a727b88d79d6.PNG)

**Comment by perisicboro** [comment]
Fixed in next release.

**Comment by itscam** [comment]
Fix verified. Can we change the color on the auto-arrange/drag and drop message too? @perisicboro @nmarkovic04 

![image1 3](https://cloud.githubusercontent.com/assets/8051364/6830440/69af29fc-d2df-11e4-8be7-aa43a2a902c5.PNG)

**Comment by AustenB** [comment]
Let's change design of it. Ask Tibor  for improved design
