### ISSUE TITLE
Images didn't generate correctly

### ISSUE THREAD

**Issue by tamaratomovski** [printdotio/printio-ios-sdk#397]
It appears that these images did not generate correctly and it's showing Image Ratio Missmatch. Could you please help?

https://admin-v2.print.io/Home#/orders/146488/images

Thanks!

 @perisicboro  

![admin](https://cloud.githubusercontent.com/assets/10880662/6655976/c9700502-cb17-11e4-8c36-3f1f079f74ca.png)
![admin1](https://cloud.githubusercontent.com/assets/10880662/6655977/c974f562-cb17-11e4-9772-1fad74b886bb.png)

**Comment by AustenB** [comment]
This image didn't load - Send it to the admin team/API team because the
image manip didn't load

On Sun, Mar 15, 2015 at 8:39 AM, tamaratomovski <notifications@github.com>
wrote:

> It appears that these images did not generate correctly and it's showing
> Image Ratio Missmatch. Could you please help?
>
> https://admin-v2.print.io/Home#/orders/146488/images
>
> Thanks!
>
> @perisicboro <https://github.com/perisicboro>
>
> [image: admin]
> <https://cloud.githubusercontent.com/assets/10880662/6655976/c9700502-cb17-11e4-8c36-3f1f079f74ca.png>
> [image: admin1]
> <https://cloud.githubusercontent.com/assets/10880662/6655977/c974f562-cb17-11e4-9772-1fad74b886bb.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/397>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by AustenB** [comment]
@micahasmith thoughts here?
