### ISSUE TITLE
High: Product preview layouts broken

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#398]
Product preview layouts seem to be broken. I've noticed this with framed prints and canvas wraps. I'm sure this is an issue for other products too. I've observed this on the iPhone 5 and 6.
![img_0273](https://cloud.githubusercontent.com/assets/8051364/6670325/9568cce2-cbc3-11e4-8686-7537cdf225df.PNG)
![img_0274](https://cloud.githubusercontent.com/assets/8051364/6670326/956a788a-cbc3-11e4-8dd0-424ccc7de649.PNG)
![img_0275](https://cloud.githubusercontent.com/assets/8051364/6670324/95685744-cbc3-11e4-9cd4-a8916cfa312a.PNG)

![img_0270](https://cloud.githubusercontent.com/assets/8051364/6670194/fa7ff5d4-cbc2-11e4-8975-6bae14dbd1f7.PNG)

**Comment by perisicboro** [comment]
@itscam it happens only when status bar is visible. Will be fixed asap!!

**Comment by perisicboro** [comment]
@itscam Fixed in v1.1.5-dev

**Comment by itscam** [comment]
Fix verified.
