### ISSUE TITLE
High: Paypal not appearing as a payment option

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#399]
![img_0278](https://cloud.githubusercontent.com/assets/8051364/6670887/1ed97e9c-cbc7-11e4-92a1-1af003e58c5f.PNG)

**Comment by nmarkovic04** [comment]
@itscam Confirmed and fixed. 

In the meantime you can use:
```Objective-C
[printIO setPaymentOptions:PaymentOptionCreditCard | PaymentOptionPayPal];
```
instead of 
```Objective-C
[printIO setPaymentOptions:PaymentOptionAll];
```
