### ISSUE TITLE
High: Product preview shrinks after image edit on iPad

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#401]
iPad Mini 2, on production. This may be related to what is causing https://github.com/printdotio/printio-ios-sdk/issues/398

1) Product preview is now much smaller on iPad. I can provide screenshots if you need them.

2) Product preview becomes even smaller when using the editor:

![img_2881](https://cloud.githubusercontent.com/assets/8051364/6675977/113f5eaa-cbea-11e4-8818-f7b19a58bf9f.GIF)

**Comment by itscam** [comment]
Also an issue on the iPad Mini 1st generation.

**Comment by AustenB** [comment]
@itscam We don't support iPads formally yet. 

we are fixing the underlying issue

**Comment by itscam** [comment]
@AustenB This is a new issue.. Previous SDK worked as expected on iPad.

**Comment by perisicboro** [comment]
@itscam Fixed.

**Comment by itscam** [comment]
Fix verified.
