### ISSUE TITLE
Photo source customization not working anymore.

### ISSUE THREAD

**Issue by pesquibr** [printdotio/printio-ios-sdk#402]
Hi all. I'm passing images using the photo source PIO_SM_PASSED_PHOTOS. I was using the version 1.47 and all was working fine, but after I upgrade to the version 1.1.0 I can not customize the "Title" and "IconPath" of the photo source. Currently It is showing the default PrintIO icon with the text "Preselected" instead. Do you have any ideia how can I fix that ? Thanks.

**Comment by Ivan1985** [comment]
Fixed in next release.

**Comment by AustenB** [comment]
@pesquibr let us know if you can confirm the fix

**Comment by pesquibr** [comment]
It was fixed. Thanks.
