### ISSUE TITLE
High: Upload performance issues for high image-count products

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#403]
Production, iPhone 6

Tinybook product, 72 camera images from phone source

I tested over a cellular connection that averages between 2-3 MBps up and down

After selecting photos, the import to the edit screen took over 10 minutes. Is there anything that can be done to optimize this? Are you pulling down the original size images?

**Comment by nmarkovic04** [comment]
Over 10 minutes definitely doesn't sound right. I can't reproduce on 5s. I'll investigate it further and get back to you.

**Comment by perisicboro** [comment]
@itscam Fixed and optimized.

**Comment by itscam** [comment]
Fix verified.
