### ISSUE TITLE
Medium: Glossy and Lustre icons not appearing for Prints

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#404]
Production, iPhone 5, 6, 6+.

Navigate to Prints product. Glossy and Lustre icons are missing.

![img_0282](https://cloud.githubusercontent.com/assets/8051364/6692212/f80749aa-cc90-11e4-8249-e039fb2bfc42.PNG)

**Comment by perisicboro** [comment]
@itscam Fixed. Will be available today in dev build.

**Comment by itscam** [comment]
Fix verified.
