### ISSUE TITLE
Low: Product detail image - Close button running into iOS status bar

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#405]
iPhone 5, 6, 6+ on production.

![image1 2](https://cloud.githubusercontent.com/assets/8051364/6692498/7d9c5988-cc92-11e4-86dc-f9fa8989f4e2.PNG)

**Comment by Ivan1985** [comment]
Already fixed, will be available in next release.

**Comment by itscam** [comment]
Thanks @Ivan1985

**Comment by itscam** [comment]
Fix verified.
