### ISSUE TITLE
High: Canvas Minis - No price displayed when selecting a size

### ISSUE THREAD

**Issue by barnbucket** [printdotio/printio-ios-sdk#406]
Select Canvas Minis and start creating a product. On the choose options screens there are different sizes presented. The prize is dependent on the size the user selects but price is not shown on this page.

**Comment by barnbucket** [comment]
Tote bags have a similar issue. Sizes are displayed but the price associated to the size is not available until you get to the shopping cart. 

We are pointed to production. Seeing this behavior on all devices tested.

**Comment by AustenB** [comment]
Yes. 1.1.10

On Fri, Mar 27, 2015 at 4:57 PM, Cameron Bradley <notifications@github.com>
wrote:

> Confirming that this will be in 1.1.10?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/406#issuecomment-87090157>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by AustenB** [comment]
@itscam ready for you to test

**Comment by itscam** [comment]
Fix verified.

**Comment by AustenB** [comment]
You are a testing machine
