### ISSUE TITLE
Low/Medium: Double tap to edit message obstructing preview and save button

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#407]
All devices, on production, newest sdk.

The double tap to edit message obstructs the preview for taller products. 

![img_0398](https://cloud.githubusercontent.com/assets/8051364/6830197/e4b4427e-d2dd-11e4-9688-f296d22d4d43.PNG)

**Comment by AustenB** [comment]
Asset needs to be a transparent png and not have white on bottom

**Comment by perisicboro** [comment]
@itscam I moved popup little bit up, but if you use custom asset, it should be transparent to avoid white on bottom. Available in v1.1.10-dev today
