### ISSUE TITLE
Medium: Way to block Flickr iTunes download dropdown?

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#408]
After logging-in to the Flickr source, you are prompted to allow access for photos. Unfortunately there is an app store drop-down on this page for the Flickr app. Is there anything you can do to block this?

![img_0395](https://cloud.githubusercontent.com/assets/8051364/6830566/3f131fa4-d2e0-11e4-9df1-3aa10e6def8a.PNG)

**Comment by AustenB** [comment]
@itscam low priority -> very difficult to do. Going to Backlog
