### ISSUE TITLE
Medium/High: Coming soon products and much more to come still visible

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#409]
All devices, newest SDK, on production.

Before calendars went live, we were still prompted to enter our email address to be notified when they went live. Also, the "much more to come" message is at the bottom of the product list.

**Comment by AustenB** [comment]
Is this Wall Calendars -> or regular Calendars?

**Comment by itscam** [comment]
Wall calendars. Is there a "Calendar" product as well?

**Comment by AustenB** [comment]
It doesn't say coming soon: [image: Inline image 1]

On Wed, Mar 25, 2015 at 1:42 PM, Cameron Bradley <notifications@github.com>
wrote:

> Wall calendars. Is there a "Calendar" product as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/409#issuecomment-86139917>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by perisicboro** [comment]
Build v1.1.10-dev will be available today.
Use these methods:

[- (void)hideMuchMoreToCome:(BOOL)hide;](https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--hidemuchmoretocome)
[- (void)hideComingSoonProducts:(BOOL)hide;](https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--hidecomingsoonproducts)

**Comment by AustenB** [comment]
@itscam confirm that no coming soon products are showing

**Comment by itscam** [comment]
No longer showing. Fix verified. Thanks!
