### ISSUE TITLE
High: Product image issues

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#410]
1) New product images(canvas posters, minis, calendars, rugs, dog beds) have a white background, while old products have a grey background. Tote bags have a darker grey background
![img_3120](https://cloud.githubusercontent.com/assets/8051364/6830934/da0ecec0-d2e2-11e4-872f-0696a74af727.PNG)

2) Rug product image has a mark to the left of the rug
![img_3119](https://cloud.githubusercontent.com/assets/8051364/6830966/1071cd00-d2e3-11e4-8158-a8ee259d24d8.PNG)

3) Missing grid view image for tote bags
![img_3121](https://cloud.githubusercontent.com/assets/8051364/6830971/14d9172c-d2e3-11e4-820c-3ef59ea2e375.PNG)

**Comment by perisicboro** [comment]
@AustenB This is not issue for iOS team.

**Comment by AustenB** [comment]
@itscam these are your pictures loaded for your account. Talk to Katie directly.
