### ISSUE TITLE
Blocked on big camera rolls.

### ISSUE THREAD

**Issue by vrabeux** [printdotio/printio-ios-sdk#411]
Hi,

When trying to access the camera roll of phones with more that 3000 pictures, the app freezes. CPU is at 100% usage, and nothing happens even after several seconds. 

version 1.0.45

**Comment by AustenB** [comment]
@vrabeux can you please use the latest SDK - there are many fixed since 1.0.45

**Comment by vrabeux** [comment]
1.1.14-dev solves it. Thanks for your time.
