### ISSUE TITLE
SparkMode canvas issue - images aren't generated

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#413]
Most of SparkMode canvas orders get to us with the Image Issue status in Admin panel, which means that the images aren't generated and there is some problem with the code in Manip Command. 

I can easily create new canvas images when it's for single image canvas, but there is a problem if it's for mosaic one:
https://admin-v2.print.io/Home#/orders/155225/images

![image 10](https://cloud.githubusercontent.com/assets/10849553/6938259/57cfec84-d862-11e4-89b4-ed486be9835c.jpg)

Here is the list of some orders that were in Image Issue, but I've created new images and pushed them into production:

https://admin-v2.print.io/Home#/orders/150968/summary
https://admin-v2.print.io/Home#/orders/135837/summary
https://admin-v2.print.io/Home#/orders/130663/summary
https://admin-v2.print.io/Home#/orders/127009/summary

@perisicboro @Ivan1985 @AustenB

**Comment by AustenB** [comment]
@mkontic people need to update to newest version of SDK -> then its fixed
