### ISSUE TITLE
Medium: Swipe gesture opening sidebar menu

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#414]
Newest SDK with all devices

Swiping gesture opens the sidebar menu for some products, including the new canvas minis and canvas posters. Can we block this on all screens where a user can swipe from right to left?

![5secondsapp 1](https://cloud.githubusercontent.com/assets/8051364/6955543/4b9381b2-d89c-11e4-8f82-0013042d472e.gif)

**Comment by barnbucket** [comment]
The swipe for the menu should only be available on the screens a user can access the menu, e.g. Print home screen.

**Comment by AustenB** [comment]
We will update

On Thu, Apr 2, 2015 at 10:57 AM, barnbucket <notifications@github.com>
wrote:

> The swipe for the menu should only be available on the screens a user can
> access the menu, e.g. Print home screen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/414#issuecomment-88935996>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by perisicboro** [comment]
Fixed.

**Comment by itscam** [comment]
@AustenB @perisicboro Fix confirmed on the canvas mini and poster screen, but can we turn off the sidebar for all screens that don't show the settings cog?
