### ISSUE TITLE
Medium: Double-tap to edit message position

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#417]
We filed an issue a couple weeks ago about the positioning of the double-tap to edit message on the customize screen. It would be great if we could revisit this issue at some point. On Android, the message sits between the action bar and preview. Currently on iOS, the message obstructs the save button and other action bar buttons. For instance, Calendars:

![img_3439](https://cloud.githubusercontent.com/assets/8051364/7127420/4c1b39fe-e201-11e4-9b60-4bd63a409fde.PNG)

**Comment by AustenB** [comment]
@perisicboro please make the double top popup go away right away on first screen tap

**Comment by perisicboro** [comment]
Fixed in next version.

**Comment by itscam** [comment]
@AustenB Can we change the position too?

**Comment by AustenB** [comment]
Want it centered within screen? @itscam

**Comment by itscam** [comment]
@AustenB That works, as long as it doesn't obstruct any actionbar buttons.

**Comment by AustenB** [comment]
Yea its in the middle now :)

Done and Done. Also our new style of it - is prettier.

On Wed, Apr 22, 2015 at 4:04 PM, Cameron Bradley <notifications@github.com>
wrote:

> @AustenB <https://github.com/AustenB> That works, as long as it doesn't
> obstruct any actionbar buttons.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/417#issuecomment-95320903>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by perisicboro** [comment]
@itscam I will upload new dev build tomorrow, so you can test it.

**Comment by itscam** [comment]
Thanks @AustenB and @perisicboro

**Comment by itscam** [comment]
@AustenB @perisicboro I thought you meant the preview would be centered and the message would be above the preview, as it is on Android. I'm sorry that I wasn't clear.

Is this possible? Even if you can only move the message to that location, and not adjust the preview position.
![screenshot_2015-04-28-15-59-13](https://cloud.githubusercontent.com/assets/8051364/7381438/7d137790-edc0-11e4-8557-d0effcd207ca.png)

**Comment by itscam** [comment]
@AustenB Is it possible to place this back at the top of the edit screen, while not moving into the action bar?
