### ISSUE TITLE
Free Shipping Coupon Partial Applying - Partner: Artkive

### ISSUE THREAD

**Issue by TheTriciaRussel** [printdotio/printio-ios-sdk#418]
Artkive, a partner who is integrating our sdk is having a issue with FREE SHIPPING Coupon for example shower curtains. If we have state level pricing, which we do for ship boxes, it does not know how much to take off for shipping so in this case this parter is saying it's taking of 7.03 instead of 11.05. I looked in the shipping boxes and the prices are correct. What needs to be done to fix this? Thanks in adance! 

partner email: jeff@thekivecompany.com
rep: sofia
@perisicboro  @AustenB 

![coupon1](https://cloud.githubusercontent.com/assets/7386911/7161615/f2d55fba-e35d-11e4-95b8-a0b043f32675.jpg)
![coupon2](https://cloud.githubusercontent.com/assets/7386911/7161613/f2d4fb7e-e35d-11e4-80bd-bd3ef01dc4c9.jpg)
![select address](https://cloud.githubusercontent.com/assets/7386911/7161617/f2d74a64-e35d-11e4-9643-d260906d0431.jpg)
![img_4468](https://cloud.githubusercontent.com/assets/7386911/7161614/f2d54660-e35d-11e4-8b2d-7c507030ac7b.PNG)
![img_4467](https://cloud.githubusercontent.com/assets/7386911/7161616/f2d5b488-e35d-11e4-88e9-25b3a5fc471d.PNG)

(SCREEN SHOTS ATTACHED)

**Comment by perisicboro** [comment]
@AustenB @Ivan1985 Details are in trello ticket.

**Comment by AustenB** [comment]
expect to use 1.2.0 for the release
