### ISSUE TITLE
High: Everything bag customize screen preview is broken

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#419]
This is a production issue.

Select Everything bags product, select layout and photos and proceed to customize screen. Bag is not represented, only the images. Same issue on shopping cart screen.

We did rename Everything Bags to Tote bags, but we are unsure if that is what caused this issue. If we are allowed to change the name of a product, we hope that it wouldn't cause an issue like this.

![img_3562](https://cloud.githubusercontent.com/assets/8051364/7171088/589acd98-e391-11e4-802c-a5fa61c35639.PNG)

**Comment by AustenB** [comment]
This is a very strange error.

I thought this was tested before it went live - it was showing up for you
last week.

Lets check asap tomorrow AM

On Thu, Apr 16, 2015 at 1:05 AM, Cameron Bradley <notifications@github.com>
wrote:

> This is a production issue.
>
> Select Everything bags product, select layout and photos and proceed to
> customize screen. Bag is not represented, only the images. Same issue on
> shopping cart screen.
>
> We did rename Everything Bags to Tote bags, but we are unsure if that is
> what caused this issue. If we are allowed to change the name of a product,
> we hope that it wouldn't cause an issue like this.
>
> [image: img_3562]
> <https://cloud.githubusercontent.com/assets/8051364/7171088/589acd98-e391-11e4-802c-a5fa61c35639.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/419>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by itscam** [comment]
@AustenB This is what the preview for Android looks like, also broken.

![screenshot_2015-04-15-19-23-03](https://cloud.githubusercontent.com/assets/8051364/7185776/2ca08b6a-e422-11e4-8151-bec05953b37f.png)

**Comment by AustenB** [comment]
This must be a server side issue.

Will get fixed today.

On Thu, Apr 16, 2015 at 6:20 PM, Cameron Bradley <notifications@github.com>
wrote:

> @AustenB <https://github.com/AustenB> This is what the preview for
> Android looks like, also broken.
>
> [image: screenshot_2015-04-15-19-23-03]
> <https://cloud.githubusercontent.com/assets/8051364/7185776/2ca08b6a-e422-11e4-8151-bec05953b37f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/419#issuecomment-93776373>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by AustenB** [comment]
@itscam fixed on server
