### ISSUE TITLE
High: Preselected images not loading on product customize screen

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#420]
Newest SDK version, all devices, on production

- Select an image to be passed through to print.io SDK
- Choose product in SDK, tap create it and choose other options
(notice that single image product contains the preselected image)

Observed: Preselected image is not passed to the customize screen. Hangs on loading.

**Comment by AustenB** [comment]
You should have the single image product showing in options turned off.
This was turned off in your code at the end of 2014.

How many images are being passed in? Are you passing them in as a URL or
other phone asset?

Does it happen with all products?

Are you adding additional photos on the choose photo step?

On Mon, Apr 20, 2015 at 5:19 PM, Cameron Bradley <notifications@github.com>
wrote:

> Newest SDK version, all devices, on production
>
>    - Select an image to be passed through to print.io SDK
>    - Choose product in SDK, tap create it and choose other options
>    (notice that single image product contains the preselected image)
>
> Observed: Preselected image is not passed to the customize screen. Hangs
> on loading.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/420>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by perisicboro** [comment]
@itscam When passing photos in sdk, add PIO_SM_PASSED_PHOTOS to available photo sources:

```Objective-C
[photoSources addObject:[[PIOSideMenuButton alloc]initWithType:PIO_SM_PASSED_PHOTOS]];
[self.printIO setAvailablePhotoSources:photoSources];
```

**Comment by barnbucket** [comment]
@perisicboro Is there a production ready release with this fix?

**Comment by perisicboro** [comment]
@barnbucket Production SDK will be on Monday. We are still testing it.
