### ISSUE TITLE
Image stretched on Shopping Cart page.

### ISSUE THREAD

**Issue by pesquibr** [printdotio/printio-ios-sdk#421]
Hi all. On the Shopping Cart page, the blue plus sign on the left of the text "Add More Products" is very stretched. Could you check this ? Thanks. 

![img_0323](https://cloud.githubusercontent.com/assets/1742312/7251268/2cdb85b2-e800-11e4-9703-c4ca88a1380f.png)

**Comment by perisicboro** [comment]
@pesquibr Fixed in v1.1.26-dev build. Will be available later today.

**Comment by AustenB** [comment]
@pesquibr please confirm this is fixed

**Comment by pesquibr** [comment]
It was fixed. Thanks.
