### ISSUE TITLE
Turning on disablePhotoSourcesForOnePhotoTemplate breaks multiple images

### ISSUE THREAD

**Issue by jjxtra** [printdotio/printio-ios-sdk#423]
I'm still trying to use disablePhotoSourcesForOnePhotoTemplate, but the photo sources still show up for the one image templates.

**Comment by AustenB** [comment]
This is a definite good find.

We will make sure that we open up disable for single with allowing
multiphotos to be passed in and collages working.

It might need to be called something different.

**Comment by jjxtra** [comment]
Great, thanks.

**Comment by perisicboro** [comment]
@jjxtra Fixed in v1.1.26-dev build. Will be available today.

**Comment by AustenB** [comment]
@jjxtra confirming fix
