### ISSUE TITLE
Unable to set navigation bar color

### ISSUE THREAD

**Issue by jjxtra** [printdotio/printio-ios-sdk#424]
I am trying to set the navigation bar background and tint color of the print io view controller, which looks like it is a UINavigationController. The navigation bar refuses to change colors and is always a green background with black tint. To make sure it wasn't something I was doing, I disabled all my appearance proxy code, and the issue still happens.

Here is my code:

```

- (void) customizePrintShopUI:(PrintIO*)printIO image:(UIImage*)image
{
    [printIO setTitleForFeaturedProductsScreen:TR(@"Label_PrintShop")];
    [printIO showToolbarInCustomizeProduct:NO backgroundImage:nil];
    [printIO enablePhotoSourcesInCustomizeProduct:NO];
    [printIO enableShareOnFacebookDeal:NO];
    [printIO disablePhotoSourcesForOnePhotoTemplate:YES];
    [printIO setImages:@[ image ]];
    UIViewController* vc = [printIO viewController];
    if ([vc isKindOfClass:UINavigationController.class])
    {
        UINavigationController* navVC = (UINavigationController*)vc;
        [navVC.navigationBar setTintColor:UIColor.blackColor];
        [navVC.navigationBar setBackgroundColor:UIColor.whiteColor];
        [navVC.navigationBar setBarTintColor:UIColor.whiteColor];
        [navVC.navigationBar setBackgroundImage:ImageFromColor(UIColor.whiteColor) forBarMetrics:UIBarMetricsDefault];
    }
}

// ... present the view ...

```

**Comment by perisicboro** [comment]
@jjxtra Try to use one of these methods:

[- navigationBarColor:titleColor:leftButtonBackgroundColor:rightButtonBackgroundColor:titleButtonIcon](https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--navigationbarcolortitlecolorleftbuttonbackgroundcolorrightbuttonbackgroundcolortitlebuttonicon)
[- setNavigationBarBackground](https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--setnavigationbarbackground)
[- setNavigationBarBackgroundForCustomizeProduct](https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--setnavigationbarbackgroundforcustomizeproduct)
[- setNavigationBarSaveToCartBackgroundColor:titleColor:buttonBackgroundColor:buttonTitleColor](https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--setnavigationbarsavetocartbackgroundcolortitlecolorbuttonbackgroundcolorbuttontitlecolor)

**Comment by AustenB** [comment]
@jjxtra closing for now - confirm it works for you

**Comment by jjxtra** [comment]
Those work, thanks.

**Comment by jjxtra** [comment]
Scratch that, none of these methods you suggest do anything, it's still always green.

**Comment by jjxtra** [comment]
Ok figured it out, apparently it has to be a full path. A nicer, cleaner API would just take a UIColor or UIImage instead of NSString...

**Comment by AustenB** [comment]
It works for all of our other SDK implementations :)

Please show the code you are trying to use.

On Thu, Apr 23, 2015 at 5:50 PM, Jeff Johnson <notifications@github.com>
wrote:

> Scratch that, none of these methods you suggest do anything, it's still
> always green.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/424#issuecomment-95728881>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by AustenB** [comment]
Lets add that as a request for enhancement :)

On Thu, Apr 23, 2015 at 5:53 PM, Jeff Johnson <notifications@github.com>
wrote:

> Ok figured it out, apparently it has to be a full path. A nicer, cleaner
> API would just take a UIColor or UIImage instead of NSString...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/424#issuecomment-95729652>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio
