### ISSUE TITLE
Camera Roll photo source crashes the app for photo books

### ISSUE THREAD

**Issue by nationalmediabrands** [printdotio/printio-ios-sdk#425]
When I go to photo books, choose "Phone" for the photo source and tap on Camera Roll, the app crashes with an error:

2015-04-20 17:20:10.481 Event Edition[686:216865] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<ImageCell 0x128abc1b0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key imageViewSizeWarning.'

The call stack says it crashes at [UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes]

Note I am using this on an iPad.

**Comment by AustenB** [comment]
Full iPad support will be available later this year.

But we will look into this issue.

**Comment by perisicboro** [comment]
@nationalmediabrands It should be fixed in this build: https://github.com/printdotio/printio-ios-sdk/releases/tag/1.1.28-dev

**Comment by AustenB** [comment]
@nationalmediabrands confirming it was fixed in newer builds
