### ISSUE TITLE
Hellopics: Everything bag

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#426]
Images weren't generated, but there are also no images in manipulation command.

Order: https://admin-v2.print.io/Home#/orders/171956/images

![image 54](https://cloud.githubusercontent.com/assets/10849553/7293952/946402a4-e9a9-11e4-87f5-0ed521e699bb.jpg)

@perisicboro @Ivan1985 @AustenB

**Comment by Ivan1985** [comment]
@mkontic Can you please ask customer: which build he used (number at the bottom of the side menu), which phone he used and which photo source he used for order, so we can diagnose the problem. Currently Everything bags works good!

**Comment by mkontic** [comment]
@Ivan1985 I asked. Just to let you know that customer placed new order and everything went well:
https://admin-v2.print.io/Home#/orders/173508/images

**Comment by mkontic** [comment]
@Ivan1985 Here's what we got from the customer: 
"I used the iPhone 6 plus and the pictures are from my camera roll and photo stream folders."
