### ISSUE TITLE
setIconForBackButton causes distorted image

### ISSUE THREAD

**Issue by jjxtra** [printdotio/printio-ios-sdk#427]
I have an 88x88 png that I am using, so I know my button is a square. Screenshot attached.

![ios simulator screen shot apr 23 2015 4 07 55 pm](https://cloud.githubusercontent.com/assets/1271832/7308571/eb10b9de-e9d2-11e4-90a9-76b038fab66e.png)

**Comment by AustenB** [comment]
@jjxtra send the code you are using to initialize and use this icon

**Comment by AustenB** [comment]
@jjxtra try to match the size of the cart icon we recommend in this doc: 

https://github.com/printdotio/printio-ios-sdk/blob/master/docs/Reference/dimensions_of_assets.md

**Comment by AustenB** [comment]
@perisicboro what size is this icon supposed to be?

**Comment by perisicboro** [comment]
Icon size 79 x 44 pixels, 72 pixels/inch

**Comment by AustenB** [comment]
Jeff please update to this size

On Tue, Apr 28, 2015 at 2:34 AM, perisicboro <notifications@github.com>
wrote:

> Icon size 79 x 44 pixels, 72 pixels/inch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/427#issuecomment-96945725>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by AustenB** [comment]
@jjxtra please update the size accordingly.
