### ISSUE TITLE
Set Product Detail Buttons

### ISSUE THREAD

**Issue by 1920ben** [printdotio/printio-ios-sdk#428]
Although we can set the image editor screen buttons (w/ imageEditorShowButtons), there doesn't seem to be a way to show/hide the bottom buttons on the attached screen. Our app specializes in text so it's redundant to have a text option on this screen. Can you add ability to show/hide buttons here?

![screen shot 2015-04-23 at 7 13 50 pm](https://cloud.githubusercontent.com/assets/6393554/7309523/88ed9090-e9ed-11e4-83fe-2e011e30cc9a.png)

**Comment by AustenB** [comment]
To find most options - you can find them by looking for methods that apply
to this screen in the SDK at this link:

https://github.com/printdotio/printio-ios-sdk/blob/master/docs/specific_page_methods.md

The method to hide that bar currently exists - the docs are here for it:

https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--showtoolbarincustomizeproductbackgroundimage



On Thu, Apr 23, 2015 at 7:18 PM, 1920ben <notifications@github.com> wrote:

> Although we can set the image editor screen buttons (w/
> imageEditorShowButtons), there doesn't seem to be a way to show/hide the
> bottom buttons on the attached screen. Our app specializes in text so it's
> redundant to have a text option on this screen. Can you add ability to
> show/hide buttons here?
>
> [image: screen shot 2015-04-23 at 7 13 50 pm]
> <https://cloud.githubusercontent.com/assets/6393554/7309523/88ed9090-e9ed-11e4-83fe-2e011e30cc9a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/428>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by 1920ben** [comment]
I completely missed that. Thanks @AustenB !
