### ISSUE TITLE
Image Issue

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#429]
We have a lot of orders with Image Issue status where images weren't generated, all placed via iOS, multiple products.

Some of the orders:
https://admin-v2.print.io/Home#/orders/173899/summary
https://admin-v2.print.io/Home#/orders/173877/summary
https://admin-v2.print.io/Home#/orders/173836/summary
https://admin-v2.print.io/Home#/orders/172986/summary
https://admin-v2.print.io/Home#/orders/172954/summary
https://admin-v2.print.io/Home#/orders/172595/summary
https://admin-v2.print.io/Home#/orders/167740/summary
https://admin-v2.print.io/Home#/orders/167689/summary

![image issue](https://cloud.githubusercontent.com/assets/10849553/7318997/cb819b0a-ea91-11e4-9c87-5025d50a31cc.jpg)

@perisicboro @Ivan1985 @AustenB

**Comment by perisicboro** [comment]
@mkontic At the bottom of each imgmanip command, you'll find:
```
"font":""
```

just change it to:
```
"font":"opensans"
```

and image can be created. This bug is already fixed. When partners and HelloPics update SDK, it will disappear.

**Comment by mkontic** [comment]
K, thakns! :)

**Comment by AustenB** [comment]
Are all of these people using text?
@perisicboro <https://github.com/perisicboro>

On Fri, Apr 24, 2015 at 11:36 AM, Milena <notifications@github.com> wrote:

> K, thakns! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/429#issuecomment-95969427>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by AustenB** [comment]
@perisicboro were seeing uri:(null) --> lets make sure we get this release out ASAP

**Comment by perisicboro** [comment]
@mkontic @AustenB Old bug from v1.1.16.
