### ISSUE TITLE
Shipment Confirmation Emails - Rock Chromatic

### ISSUE THREAD

**Issue by stefanbognar** [printdotio/printio-ios-sdk#430]
Ryan from RockChromatic says he doesn't receive shipment confirmation emails.

Here's an example of an order he didn't receive a shipment confirmation to:
https://admin-v2.print.io/Home#/orders/171621/summary

I tried putting my own email address in the shipping info and re-sending the shipment confirmation but I didn't receive it.

**Comment by AustenB** [comment]
This goes in a different repo. Please email to Ben and close ticket. It's a
Web thing not mobile side
