### ISSUE TITLE
Default Photo Source not auto opening

### ISSUE THREAD

**Issue by 1920ben** [printdotio/printio-ios-sdk#431]
When using the following setup code:

[printIO setDefaultPhotoSource:PIO_PS_PHONE albumId:@""];

The phone/camera roll doesn't seem to open by default. This screen still appears:

![screen shot 2015-04-30 at 1 21 58 pm](https://cloud.githubusercontent.com/assets/6393554/7418448/e6f4e5a0-ef3b-11e4-8e76-38556d556983.png)

**Comment by AustenB** [comment]
@perisicboro if we don't have a way to auto show/auto open any of the image sources -> lets add it

**Comment by perisicboro** [comment]
Fixed in v1.2.2
