### ISSUE TITLE
Show two column products list by default

### ISSUE THREAD

**Issue by 1920ben** [printdotio/printio-ios-sdk#432]
Is it possible to display the two column products list by default?

![screen shot 2015-04-30 at 1 26 28 pm](https://cloud.githubusercontent.com/assets/6393554/7418545/bb266952-ef3c-11e4-856b-3b226e896f20.png)

**Comment by AustenB** [comment]
https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--setfeaturedproductsdefaultview

Set it to all products not featured

On Thu, Apr 30, 2015 at 1:28 PM, 1920ben <notifications@github.com> wrote:

> Is it possible to display the two column products list by default?
>
> [image: screen shot 2015-04-30 at 1 26 28 pm]
> <https://cloud.githubusercontent.com/assets/6393554/7418545/bb266952-ef3c-11e4-856b-3b226e896f20.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/432>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by AustenB** [comment]
@1920ben please confirm done

**Comment by AustenB** [comment]
@1920ben confirming this fixed the issue
