### ISSUE TITLE
Disable image rotation animation when scrolling through products

### ISSUE THREAD

**Issue by 1920ben** [printdotio/printio-ios-sdk#433]
Would like to to disable the rotation animation of loading images when scrolling:

![screen shot 2015-04-30 at 1 24 11 pm](https://cloud.githubusercontent.com/assets/6393554/7418610/0b6353bc-ef3d-11e4-9a58-60a2c43ef808.png)

**Comment by perisicboro** [comment]
@1920ben Use this method: https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--disableanimationinproductslist from SDK version 1.2.2
