### ISSUE TITLE
Apostrophe needs to be escaped

### ISSUE THREAD

**Issue by VSergiyenko** [printdotio/printio-ios-sdk#437]
when people have apostrophes in their first/last names (example is below),
![img_0370](https://cloud.githubusercontent.com/assets/7405464/7670331/90b25472-fca9-11e4-81f1-086b7af51071.jpg)
ios submits apostrophes as \&apos; text
and in admin it looks funky:
https://admin.print.io/Home#/orders?SortField=dateCreated&Desc&SimpleSearch=apos&page=1&tab=4
![screenshot 2015-05-17 15 34 56](https://cloud.githubusercontent.com/assets/7405464/7670371/8c6229e6-fcaa-11e4-8dee-ee3f81f2779b.png)

example of test order:
https://admin.print.io/Home#/orders/187692/summary
fyi @Ivan1985

**Comment by perisicboro** [comment]
@Ivan1985 Fixed in v1.2.12

**Comment by Ivan1985** [comment]
Verified: 1.2.12
