### ISSUE TITLE
Crash when opening PrintIO interface on iPad

### ISSUE THREAD

**Issue by nikmesoft** [printdotio/printio-ios-sdk#438]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/linhnguyen/Library/Developer/CoreSimulator/Devices/30A4E97C-AC2A-4365-9DCB-233FE2CA32C5/data/Containers/Bundle/Application/AFDDFA91-274D-4817-8BB7-E9F8AFD0048F/BestPhotoGiftMaker.app/PrintIOBundle.bundle> (not yet loaded)' with name 'CellFProduct''

**Comment by AustenB** [comment]
Can you send me the init code you are using?

**Comment by nikmesoft** [comment]
Quite simple:

    static NSString *const sRecipeId = @"00000000-0000-0000-0000-000000000000";
    // RecipeId is developer defined and provided by PrintIO Account and Sales Team
    PrintIO *printIO = [[PrintIO alloc]initWithViewController:self
                                                  environment:PRINTIO_PRODUCTION
                                           productionRecipeId:kPRINTIO_RECIPE_ID
                                              stagingRecipeId:sRecipeId];
    NSArray *images = @[image];
    [printIO setImages:images];
    [printIO setPassedImageFirstInPhotoSources:YES];
    [printIO disablePhotoSourcesWhenImagesArePassedIn:YES];
    // Start widget
    [printIO open];

I download PrintIO sample project, but the same issue when running on iPad.

**Comment by AustenB** [comment]
The recipe ID you have only works for staging.

In order to set up an account for production please email Tricia@print.io

Otherwise you need to use environment: staging

On Fri, May 22, 2015 at 8:28 PM, Nikmesoft Co. Ltd. <
notifications@github.com> wrote:

> Quite simple:
>
> static NSString *const sRecipeId = @"00000000-0000-0000-0000-000000000000";
> // RecipeId is developer defined and provided by PrintIO Account and Sales Team
> PrintIO *printIO = [[PrintIO alloc]initWithViewController:self
>                                               environment:PRINTIO_PRODUCTION
>                                        productionRecipeId:kPRINTIO_RECIPE_ID
>                                           stagingRecipeId:sRecipeId];
> NSArray *images = @[image];
> [printIO setImages:images];
> [printIO setPassedImageFirstInPhotoSources:YES];
> [printIO disablePhotoSourcesWhenImagesArePassedIn:YES];
> // Start widget
> [printIO open];
>
> I download PrintIO sample project, but the same issue when running on iPad.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/438#issuecomment-104806625>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by AustenB** [comment]
Which ipad and which version of iOS are you using?

On Sun, May 24, 2015 at 1:55 PM, Austen Bernstein <austen@print.io> wrote:

> The recipe ID you have only works for staging.
>
> In order to set up an account for production please email Tricia@print.io
>
> Otherwise you need to use environment: staging
>
> On Fri, May 22, 2015 at 8:28 PM, Nikmesoft Co. Ltd. <
> notifications@github.com> wrote:
>
>> Quite simple:
>>
>> static NSString *const sRecipeId = @"00000000-0000-0000-0000-000000000000";
>> // RecipeId is developer defined and provided by PrintIO Account and Sales Team
>> PrintIO *printIO = [[PrintIO alloc]initWithViewController:self
>>                                               environment:PRINTIO_PRODUCTION
>>                                        productionRecipeId:kPRINTIO_RECIPE_ID
>>                                           stagingRecipeId:sRecipeId];
>> NSArray *images = @[image];
>> [printIO setImages:images];
>> [printIO setPassedImageFirstInPhotoSources:YES];
>> [printIO disablePhotoSourcesWhenImagesArePassedIn:YES];
>> // Start widget
>> [printIO open];
>>
>> I download PrintIO sample project, but the same issue when running on
>> iPad.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/printdotio/printio-ios-sdk/issues/438#issuecomment-104806625>
>> .
>>
>
>
>
> --
> Austen Bernstein
> Founder & CEO
> printio
>
>
>


-- 
Austen Bernstein
Founder & CEO
printio

**Comment by nikmesoft** [comment]
I tested sample app on both iPad  OS version 7.x or 8.x. The same issue.

Staging or production mode is not an issue. I checked all xib files in your framework and I cannot find CellFProduct~ipa.xib, just CellFProduct~iphone.xib only
![screen shot 2015-05-25 at 11 19 50 am](https://cloud.githubusercontent.com/assets/1610938/7791728/0cefd3a8-02d0-11e5-9a35-aa2a0fbc4284.png)

I'm working on a fully iPad app (full iPad screen)

**Comment by nikmesoft** [comment]
Hello,
Any updates about this issue?

**Comment by perisicboro** [comment]
We don't support full iPad app, only universal app (iPhone and iPad), and that's the reason why it's crashing.

**Comment by nikmesoft** [comment]
Thanks for your responses!
I see that PrintIO SDK only support iPhone app, not universal app or iPad app.

However I don't understand why I cannot find any info about this limitation. Your team should inform about this.

**Comment by perisicboro** [comment]
I can try to convert all ~iphone.xib to simple xibs, then it should work.

**Comment by AustenB** [comment]
We support universal just not full ipad

**Comment by nikmesoft** [comment]
I don't clear about your idea with universal app.
An univeral app will support both iPhone and iPad device fully. Universal app = full iPhone app + full iPad app.

An iPhone app can run on iPad device but not full screen

I am working on an universal app( full support for both iPhone device and iPad device)

**Comment by perisicboro** [comment]
Sorry for inconvenience, right now it only works as iPhone app, but can be run on iPad also.

**Comment by nikmesoft** [comment]
I see. All iPhone app can be run on iPad devices.

So current version of PrintIO SDK only support iPhone app, not universal app or iPad app.

I think that your team should add this note to Readme file.
