### ISSUE TITLE
Canvas Mini possible bug

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#439]
Image not generated, Image Ratio Missmatch message:

https://admin-v2.print.io/Home#/orders/197206/summary

Whats wrong with this order and how can it be (manually) fixed?

@perisicboro @Ivan1985 @AustenB

**Comment by mkontic** [comment]
I received following in partner zendesk regarding this order:

"Input image http://cdn.print.io/img-manip/150529-1252545870a8457d-9.jpg doesn't have expected aspect ratio. Input image aspect ratio (width : height) is 8.125 : 8.125 
Expected aspect ratio for CanvasMini-8x10 is (width : height) 8.125 : 10.125 or 10.125 : 8.125"

**Comment by mkontic** [comment]
And Canvas Wraps as well:

https://admin-v2.print.io/Home#/orders/197173/images

@tamaratomovski

**Comment by Ivan1985** [comment]
@mkontic Probably the problem is with the low resolution images, I'll try to recreate this issue.

**Comment by perisicboro** [comment]
@mkontic  For first order I need imgmanip command. For second, change this: ```"width":"0","height":"0"```to fix it, until we fix it in sdk.

**Comment by mkontic** [comment]
@perisicboro  It looks like we fixed first one manually, can't get the img manip now.

For second - where to change it?

{"commands":[{"name":"combine","args":{"map":"0=+450+450,1=+450+450"}},{"index":"999","args":{"format":"jpg"},"name":"convert"},{"name":"quality","args":{"value":"100"}}],"settings":{"color":"#000000","width":"0","height":"0"},"name":"canvas","layers":[{"commands":[{"name":"combine","args":{"map":"0=+0+0"}}],"settings":{"index":"0","width":"3000","height":"3000","color":"#000000"},"name":"canvas","layers":[{"commands":[{"name":"affine","args":{"matrix":"2.6408451,0.0000000,0.0000000,2.6408451,0.0000000,0.0000000"}}],"name":"image","settings":{"uri":"https://printio-api.s3.amazonaws.com/48ee3f05734d39dbfc05074845fb8e22a2bca3b3541feb6e01fdd5a526035f95.jpg","index":"0"}}]},{"name":"text","settings":{"height":3000,"color":"#ffffff","horizontalAlign":"center","width":3000,"size":376.6816,"text":"","font":"opensans","verticalAlign":"top","index":"1"}}]}

**Comment by mkontic** [comment]
@perisicboro More ios19 orders with the same bug:

https://admin-v2.print.io/Home#/orders/198895/images
https://admin-v2.print.io/Home#/orders/198732/images

What should I do with them and is there anyway to fix them manually?

**Comment by mkontic** [comment]
One more:

https://admin-v2.print.io/Home#/orders/198054/images

@tamaratomovski so she can follow.

**Comment by AustenB** [comment]
@milena -> ignore these for magnetgram -> the vendor side code puts these
together into the final form -

Guys message Stevan J about what we should do to remove this from being an
error.

On Mon, Jun 1, 2015 at 8:29 AM, Milena <notifications@github.com> wrote:

> One more:
>
> https://admin-v2.print.io/Home#/orders/198054/images
>
> @tamaratomovski <https://github.com/tamaratomovski> so she can follow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/439#issuecomment-107422373>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by mkontic** [comment]
@AustenB Should I ticket magnetgrams in vendor repository?
https://admin-v2.print.io/Home#/orders/198895/images

**Comment by perisicboro** [comment]
@Ivan1985 try to recreate this bug with sdk version 1.2.0

**Comment by stefanbognar** [comment]
We have one more with prints and posters:

https://admin.print.io/Home#/orders/200088/summary

**Comment by stefanbognar** [comment]
Guys, we have another canvas mini iOS order with a bug

https://admin-v2.print.io/Home#/orders/208015/status

@perisicboro @AustenB @Ivan1985

**Comment by Ivan1985** [comment]
@stefanbognar Can you please ask customer few questions, cause I can not reproduce this issue in our SDK:

- which app version using (user can find version number in side menu on the bottom of the screen in our app)
- which device
- which iOS version have (on the device choose settings/general/about/version)
- from which photo source has chosen photos

**Comment by AustenB** [comment]
@stefanbognar is this solved now?
