### ISSUE TITLE
Can't delete items from the shopping cart

### ISSUE THREAD

**Issue by jovana-kovacevic** [printdotio/printio-ios-sdk#440]
We have a customer who claims he can't delete any items from his cart.
"I went in and tried to re-order. Again the app will not let me delete items from the shopping cart. I can change to any number but "0". How can I delete items from the cart, if it will not let me pick "0"?"
We advised him to update the app version previously, so he should be using the latest one. He tried placing the order with an iPhone 6.
Please advise, thanks!

**Comment by AustenB** [comment]
Tell him to swipe to the left and it will give him the option to delete the
item or edit the item in the cart.

On Mon, Jun 1, 2015 at 5:25 AM, jovana-kovacevic <notifications@github.com>
wrote:

> We have a customer who claims he can't delete any items from his cart.
> "I went in and tried to re-order. Again the app will not let me delete
> items from the shopping cart. I can change to any number but "0". How can I
> delete items from the cart, if it will not let me pick "0"?"
> We advised him to update the app version previously, so he should be using
> the latest one. He tried placing the order with an iPhone 6.
> Please advise, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/440>.
>



-- 
Austen Bernstein
Founder & CEO
printio
