### ISSUE TITLE
Number of products in shopping cart

### ISSUE THREAD

**Issue by pesquibr** [printdotio/printio-ios-sdk#441]
Hi All. I used to see the number of selected products to buy in the red circle overlay of the shopping cart in the upper right hand corner of the print.io screen. Now, there is just a red circle with no number of items in my cart. I can still check out when I tap that icon, but it would be nice to have that number back on the red circle. Is this feature was removed or is it a bug in the current SDK version (1.2.11)? Thanks.

**Comment by perisicboro** [comment]
@pesquibr Please send me your initialization code on boro@print.io so I can review it and test.

**Comment by perisicboro** [comment]
@pesquibr Fixed in sdk v1.2.20. Will be available today on Github.

**Comment by pesquibr** [comment]
Thanks.
