### ISSUE TITLE
UI Bug using Coupons for New partner The Kive Company

### ISSUE THREAD

**Issue by WinRisner** [printdotio/printio-ios-sdk#444]
Hi all,

Please take a look at the issue our partner is having. Correct price for Item is $27.99 when using a free shipping coupon. However, you can see that when the product is in the shopping cart it deducts the coupon price from the order of the item ($24.12). The correct final price of the product should be $

![img_4907](https://cloud.githubusercontent.com/assets/11613672/8233503/989bfb8e-15a4-11e5-91dd-d3e013cf341b.PNG)
![img_4906](https://cloud.githubusercontent.com/assets/11613672/8233502/98999132-15a4-11e5-8650-cc4022bd9780.PNG)

Thank you,

Win

**Comment by perisicboro** [comment]
@WinRisner In shopping cart, where coupon is applied, we still don't know the shipping price, so discount is deducted from product's price. When user selects shipping method, discount is deducted from (product's price + shipping price), and user only has to pay product price. Final total price is price without shipping costs.

So, what exactly is bug here?

**Comment by WinRisner** [comment]
It's a little confusing to the partner why the coupon is added before shipping method. Is it possible to not apply the coupon until shipping method has been selected?

**Comment by WinRisner** [comment]
It also does look like we know what the shipping price is since the coupon price is the same in the shopping cart and checkout

**Comment by WinRisner** [comment]
@perisicboro Boro, do you see what I mean?

**Comment by perisicboro** [comment]
@WinRisner Replied you on pm.

**Comment by AustenB** [comment]
@WinRisner is this solved now?
