### ISSUE TITLE
Duplicate symbols when I try to Archive

### ISSUE THREAD

**Issue by pesquibr** [printdotio/printio-ios-sdk#446]
Hi All. I can build and run my project fine, but when I try to Archive the project I got many errors from the linker. This is occurring with the last versions of the PrintIO SDK. Should I change any property on project settings ? I'm using Cocoapods, XCode 6.2 and PrintIO SDK 1.2.22. Thanks.

Some errors from the linker:
...
duplicate symbol l130 in:
    Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectMask_AcrylicBlock.o)
    Pods/PrintIO/PrintIO.framework/PrintIO(PPRiskDeviceData.o)
ld: 578 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by perisicboro** [comment]
@pesquibr Please send me a full log, and project configuration on boro@print.io.

**Comment by AustenB** [comment]
@pesquibr confirming an email was sent?

**Comment by perisicboro** [comment]
@AustenB He sent it. We are communicating over email about this issue.

**Comment by pesquibr** [comment]
The errors were fixed after upgrade the XCode to version 6.3.2. Thanks.

**Comment by AustenB** [comment]
did we upgrade our side or did he upgrade his?

On Tue, Jun 30, 2015 at 10:57 PM, pesquibr <notifications@github.com> wrote:

> Closed #446 <https://github.com/printdotio/printio-ios-sdk/issues/446>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/446#event-344908761>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by pesquibr** [comment]
@AustenB It was after upgrade my side.
