### ISSUE TITLE
Custom Photo Source does not appear in source selection

### ISSUE THREAD

**Issue by arik-so** [printdotio/printio-ios-sdk#447]
In your online code customization documentation file (https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md), the method setCustomPhotoSources is never mentioned. According to the file describing the custom photo sources (https://github.com/printdotio/printio-ios-sdk/blob/master/docs/Photo-Sources/custom_photo_sources.md), just calling the setCustomPhotoSources method should be enough for the source to be shown. 
However, when I do that, and I set breakpoints inside the methods: 

```objective-c
- (NSString *)title;
- (NSString *)buttonIconPath;
- (BOOL)isAuthed;
```

none of these breakpoints is ever hit. This is what the relevant code looks like:

```objective-c
PrintIO *printIO = [[PrintIO alloc] initWithViewController:self environment:PRINTIO_STAGING productionRecipeId:productionRecipeID stagingRecipeId:stagingRecipeID];
    
self.keepySource = [PrintIOPhotoSourceKeepy new];
[printIO setCustomPhotoSources:@[self.keepySource]];
    
[printIO open];
```

I even set the photo source to a strong pointer in order to prevent accidental deallocation should you be using weak references. And yet, it does not show up. Am I missing something?

**Comment by perisicboro** [comment]
Fixed in v1.2.23

**Comment by perisicboro** [comment]
@arik-so https://github.com/printdotio/printio-ios-sdk/releases/tag/1.2.23-dev Replace PrintIO.framework and PrintIOBundle.bundle because this is dev version.

**Comment by AustenB** [comment]
@arik-so confirm this fixed it

**Comment by offirg1** [comment]
@arik-so  ?

**Comment by arik-so** [comment]
This has fixed it. I thought we already cleared per email a few days ago that it was fixed, but yeah, the issue is definitely fixed.
