### ISSUE TITLE
CanvasMini - mixed width/height

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#448]
Hi guys,

CanvasMini images are not rotated properly in Admin.

![image 45](https://cloud.githubusercontent.com/assets/10849553/8351919/0f14dcd6-1b31-11e5-9f93-dcbe4ac32bff.jpg)

Dimensions are ok, but width/height is mixed up.

Here is the code, cause I need to fix this manually:

{"commands":[{"name":"combine","args":{"map":"0=+0+0,1=+0+0"}},{"index":"999","args":{"format":"jpg"},"name":"convert"},{"name":"quality","args":{"value":"100"}}],"settings":{"color":"","width":"2437","height":"3037"},"name":"canvas","layers":[{"commands":[{"name":"combine","args":{"map":"0=+3-218"}}],"settings":{"index":"0","width":"2437","height":"3037","color":""},"name":"canvas","layers":[{"commands":[{"name":"affine","args":{"matrix":"1.5894001,0.0000000,0.0000000,1.5894001,0.0000000,0.0000000"}}],"name":"image","settings":{"uri":"http://oi1381.photobucket.com/albums/ah225/mhernandez8631/Mobile%20Uploads/2013-02/9E45D09A-A77D-45E7-8C1E-8963D9B3DCD0_zps9qy5fcj6.jpg~original","index":"0"}}]},{"name":"text","settings":{"height":3037,"color":"#ffffff","horizontalAlign":"center","width":2437,"size":273.4276,"text":"","font":"opensans","verticalAlign":"top","index":"1"}}]}

@perisicboro @AustenB

**Comment by AustenB** [comment]
@mkontic than it should be updated in build info.

**Comment by mkontic** [comment]
Who should do that? Vendor team? SJ?

**Comment by Ivan1985** [comment]
@mkontic @AustenB We had this issue earlier and it was fixed: https://trello.com/c/KYOLLUCb/1908-canvas-minis-wrong-orientation-on-production-mode

But issue occurred again, so I notified vendor/data team and they will fix it asap

**Comment by perisicboro** [comment]
This should be fixed. If it happens again, reopen ticket.
