### ISSUE TITLE
Status bar overlays content, and occasionally doesn't match the application orientation

### ISSUE THREAD

**Issue by arik-so** [printdotio/printio-ios-sdk#449]
Status bar orientation mismatch:
![image](https://cloud.githubusercontent.com/assets/927534/8359053/d3068626-1b18-11e5-92ce-e36990c72270.png)

Status bar content overlay:
![image](https://cloud.githubusercontent.com/assets/927534/8359060/dec13fd8-1b18-11e5-8583-7405ece7cdcc.png)

**Comment by AustenB** [comment]
What device is this on? What iOS version?

Do you want to show the status bar or would you want to hide it during the
commerce process?

Do you show the status bar in your host app or do you hide it?

On Thu, Jun 25, 2015 at 12:02 PM, Arik Sosman <notifications@github.com>
wrote:

> Status bar orientation mismatch:
> [image: image]
> <https://cloud.githubusercontent.com/assets/927534/8359053/d3068626-1b18-11e5-92ce-e36990c72270.png>
>
> Status bar content overlay:
> [image: image]
> <https://cloud.githubusercontent.com/assets/927534/8359060/dec13fd8-1b18-11e5-8583-7405ece7cdcc.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/449>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by arik-so** [comment]
It is on the iPhone 5s, and the iOS version is 8.3. It appears to me personally that in the first screen, it would make more sense to hide the status bar, whereas in the second screen, it would probably suffice to move the top buttons down a bit.

**Comment by AustenB** [comment]
Our team will look into this asap and get back to you. This could be a
status bar bug - as it should always be hidden on the customization screen.

On Thu, Jun 25, 2015 at 1:21 PM, Arik Sosman <notifications@github.com>
wrote:

> It is on the iPhone 5s, and the iOS version is 8.3. It appears to me
> personally that in the first screen, it would make more sense to hide the
> status bar, whereas in the second screen, it would probably suffice to move
> the top buttons down a bit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/449#issuecomment-115329862>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by arik-so** [comment]
It might very well be a status bar bug. If it is, there is another minor issue: the method

```objective-c
[printIO setStatusBarDark:YES hidden:YES];
```

does not, when hidden is set to NO, change the status bar text color to white regardless of whether setStatusBarDark is set to YES or NO, and additionally, when hidden is set to YES, the status bar still remains visible at all times.

**Comment by AustenB** [comment]
Tag this as a separate github ticket. We will take a look at this also.
Perhaps we need to give better instructions how to use the method.

On Thu, Jun 25, 2015 at 1:30 PM, Arik Sosman <notifications@github.com>
wrote:

> It might very well be a status bar bug. If it is, there is another minor
> issue: the method
>
> [printIO setStatusBarDark:YES hidden:YES];
>
> does not, when hidden is set to NO, change the status bar text color to
> white regardless of whether setStatusBarDark is set to YES or NO, and
> additionally, when hidden is set to YES, the status bar still remains
> visible at all times.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/449#issuecomment-115336386>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by offirg1** [comment]
It's also happens on iOS6

**Comment by AustenB** [comment]
please email the initialization code you are using to this to Boro and we
will try to solve tomorrow.

On Thu, Jun 25, 2015 at 7:47 PM, offirg1 <notifications@github.com> wrote:

> It's also happens on iOS6
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/449#issuecomment-115432097>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by perisicboro** [comment]
@offirg1 @arik-so Do you show the status bar in your host app or do you hide it? 

By default status bar is visible in SDK, use method:
```objective-c
[printIO setStatusBarDark:YES hidden:YES];
```
to hide it. In general it works in our sample app, but we had cases where status bar visibility not acting as expected. So if you set it hidden, and it's still visible in sdk, then do not use method above to hide it. In this way you would avoid issues like on second screenshot.

For photobooks: status bar bug is fixed, and will be available in next update.

**Comment by offirg1** [comment]
We show it

**Comment by perisicboro** [comment]
If SDK can't hide status bar using method from comment above, then just don't use that method, and sdk will work with visible status bar.

**Comment by AustenB** [comment]
@perisicboro i think they are saying the status bar is showing on top of
the nav buttons - we had this issue in 2014.

On Fri, Jun 26, 2015 at 9:26 AM, perisicboro <notifications@github.com>
wrote:

> If SDK can't hide status bar using method from comment above, then just
> don't use that method, and sdk will work with visible status bar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/449#issuecomment-115684319>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by perisicboro** [comment]
@AustenB Hiding status bar doesn't work them, that's why it's showing on top of buttons. solution is not to try to hide it, just not to use that method.

**Comment by AustenB** [comment]
@offirg1 You heard it here. Don't use that method.

On Fri, Jun 26, 2015 at 10:26 AM, perisicboro <notifications@github.com>
wrote:

> @AustenB <https://github.com/AustenB> Hiding status bar doesn't work
> them, that's why it's showing on top of buttons. solution is not to try to
> hide it, just not to use that method.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/449#issuecomment-115707526>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by offirg1** [comment]
@arik-so

**Comment by perisicboro** [comment]
Fixed in latest SDK version.
