### ISSUE TITLE
Slow processing, any way to do it differently?

### ISSUE THREAD

**Issue by offirg1** [printdotio/printio-ios-sdk#450]
[Uploading slow processing.mov…]()
When i choose for the mini book, 100 photos the loading is really slow, before it lands on the list that show the photos, that it does, processing images, and then when i save to card it does process again, and again wait for very long time. 

Any reason why it has to process twice, and is there is any way to speed up the process?

**Comment by AustenB** [comment]
what phone model, what iOS version.

what are the size of the photos you are using?

Are you cropping many of them or no.

Where are the photos coming from that you are using - which photo source?

On Thu, Jun 25, 2015 at 7:54 PM, offirg1 <notifications@github.com> wrote:

> When i choose for the mini book, 100 photos the loading is really slow,
> before it lands on the list that show the photos, that it does, processing
> images, and then when i save to card it does process again, and again wait
> for very long time.
>
> Any reason why it has to process twice, and is there is any way to speed
> up the process?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/450>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by offirg1** [comment]
IOS6 - Os 8.3 
Photos are coming from Keep the keepy photo source
Not cropping or touching the photos,

**Comment by AustenB** [comment]
Can you try phone source, Facebook, and dropbox and see if any of those are
slow.

Do you cache the images on Keep -> it could be making the process slower.
If you notice a difference between the 3 i mentioned and Keep.

On Thu, Jun 25, 2015 at 7:58 PM, offirg1 <notifications@github.com> wrote:

> IOS6 - Os 8.3
> Photos are coming from Keep the keepy photo source
> Not cropping or touching the photos,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/450#issuecomment-115433311>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by offirg1** [comment]
Austen, can you tag Arik, as I am not able to do it :)

**Comment by arik-so** [comment]
I see this, we will test it with non-custom photo sources.

**Comment by AustenB** [comment]
@arik-so any update here on the speed of other sources?

**Comment by arik-so** [comment]
What I have seen with other sources (primarily FB) is that it also takes its time and does the processing multiple times.

**Comment by AustenB** [comment]
How long is it taking? Is it when its 100 photos or also at 50 photos?

On Fri, Jun 26, 2015 at 11:13 PM, Arik Sosman <notifications@github.com>
wrote:

> What I have seen with other sources (primarily FB) is that it also takes
> its time and does the processing multiple times.
>
> Sent from my iPhone
>
> > On Jun 26, 2015, at 7:49 PM, Austen Bernstein <notifications@github.com>
> wrote:
> >
> > @arik-so any update here on the speed of other sources?
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/450#issuecomment-115948305>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by AustenB** [comment]
@perisicboro lets look into making this quicker

**Comment by perisicboro** [comment]
I'll try to speed up image processing specially for slower devices like iPhone 5, for next SDK update, which we expect to have this week.

**Comment by offirg1** [comment]
Here is the processing for 100 images on iphone 6 
https://www.dropbox.com/s/l0ysqp8hhxxgs21/slow%20processing.m4v?dl=0

**Comment by perisicboro** [comment]
@offirg1 Today I worked on this, and first result is that I managed to decrease saving product processing time from 22sec to 0.3sec. On this video, saving process duration is 32sec. From now on it will be less than 0.5 sec. I still have to finish few more things tomorrow, and then I'll upload new SDK update on git for testing.

**Comment by perisicboro** [comment]
Fixed in latest SDK version.
