### ISSUE TITLE
Images of an order don't show on Admin

### ISSUE THREAD

**Issue by offirg1** [printdotio/printio-ios-sdk#451]
This order on staging admin of Mini Book don't show the images we chose in the app
https://staging-admin-v2.print.io/Home#/orders/154460/images

**Comment by perisicboro** [comment]
@offirg1 Images from custom photo source?

**Comment by arik-so** [comment]
Yes. We are using a custom photo source, and we are implementing these methods:
```objective-c
- (void)fetchImageInPhotoSource:(id<PIOPhotoSource>)photoSource isThumbnail:(BOOL)thumbnail withCompletionHandler:(void (^)(UIImage *))imageFetchCompletionHandler
```
and this one:
```objective-c
- (NSString *)publicURLPath
```
where publicURLPath returns the same URL which is used in fetchImageInPhotoSource when isThumbnail is set to false. The images appear to be used just fine locally in the representations, but in the admin panel interface, they don't show up.

**Comment by perisicboro** [comment]
@arik-so Can I some how get custom photo source implementation, so I can retest it on my side?

**Comment by arik-so** [comment]
Do you need the implementation code, or would trying out a build suffice?

**Comment by AustenB** [comment]
The code

On Fri, Jun 26, 2015 at 1:37 PM, Arik Sosman <notifications@github.com>
wrote:

> Do you need the implementation code, or would trying out a build suffice?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/451#issuecomment-115802647>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by perisicboro** [comment]
@arik-so Send me on email, boro@print.io, that custom photo source class files.

**Comment by arik-so** [comment]
Hi Boro, I've sent you the classes via email.

**Comment by perisicboro** [comment]
@arik-so While looking at this order and code you sent me, I assume that custom photo source is pulling images from local storage:

```
"uri":"/assets/
```

then I saw that you implemented: 
```
- (NSString *)publicURLPath
```

but be aware of this:
```Objective-C
// Returns fullsize image public URL path.
//
// If implemented and returns a non-nil value, image link will be passed to the server
// instead of uploading the image.

-(NSString*)publicURLPath;
```
so image link starting with "/assets" has been passed to server. Just try to remove ```publicURLPath``` and image will be uploaded instead of sending invalid url.

**Comment by offirg1** [comment]
@arik-so  i think you said you tested it, please close if fixed

**Comment by arik-so** [comment]
Yep, that fixed it.
