### ISSUE TITLE
App crashes when trying to pay

### ISSUE THREAD

**Issue by pesquibr** [printdotio/printio-ios-sdk#452]
Hi All. I'm getting an app crash when I try check out the products on PrintIO. It's seems to be something related to Amazon AWS. I'm using the SDK 1.2.24 in production mode. If you want I can send the full stack trace by email. Thanks.
```
2015-07-01 13:59:39.396 artkive[824:232118] Problem acquiring reference to the public key, OSStatus == 0.
```

**Comment by perisicboro** [comment]
@pesquibr Please send it on boro@print.io

**Comment by perisicboro** [comment]
@pesquibr Amazon S3 works as expected, I tested uploads without problems. This error message you sent me is related to braintree. Please try to make order via Paypal, and tell me is this still happening? And also check keys for braintree.

**Comment by felipessousa** [comment]
@perisicboro I was checking the braintree keys and they look good for production. Print.io works as expected in sandbox mode using Print.io default keys. However if we change to production mode using our keys we get the public key error described above. Looking at the code I only can see a method to set the private key (setBraintreeStagingEncryptionKey) but what about the Merchant ID and CSE Key ? How do we get this set ? Thanks.

**Comment by perisicboro** [comment]
No need for Merchand ID and CSE key, only encryption key is needed. By default we use our encryption key only. For Paypal also, only clientId is needed. We have no complains from other partners with setting this up, so I believe that something is wrong with your keys.

**Comment by felipessousa** [comment]
How we solve this problem: EncryptionKey = CSE Key. After you put your CSE key on your code using "setBraintreeStagingEncryptionKey" method you must contact Print.io and ask them to let you configure your merchantID, private and public keys via their website.
