### ISSUE TITLE
Tinybooks is not processing the photos 

### ISSUE THREAD

**Issue by offirg1** [printdotio/printio-ios-sdk#453]
Running on Via the Keepy app, 
on iOS 6 
https://www.dropbox.com/s/mhywvt1y8c4io2g/slowprocess-tinybook.mov?dl=0
cc @AustenB

**Comment by perisicboro** [comment]
@offirg1 Try with this build https://github.com/printdotio/printio-ios-sdk/releases/tag/1.2.35-dev

**Comment by perisicboro** [comment]
Fixed. Test in latest SDK version.
