### ISSUE TITLE
print 5x7 bug - order #237726

### ISSUE THREAD

**Issue by stefanbognar** [printdotio/printio-ios-sdk#454]
Hi guys,

We received an order that seems to be out of order.

This is the code for one of the pictures:

{"commands":[{"name":"combine","args":{"map":"0=+0+0"}},{"index":"999","args":{"format":"jpg"},"name":"convert"},{"name":"quality","args":{"value":"100"}}],"settings":{"color":"#ffffff","width":"0","height":"0"},"name":"canvas","layers":[{"commands":[{"name":"combine","args":{"map":"0=+0-5"}}],"settings":{"index":"0","width":"2100","height":"1500","color":"#ffffff"},"name":"canvas","layers":[{"commands":[{"name":"affine","args":{"matrix":"2.5932043,0.0000000,0.0000000,2.5932043,0.0000000,0.0000000"}}],"name":"image","settings":{"uri":"http://oi1317.photobucket.com/albums/t639/ToadAF/Mobile%20Uploads/2014-05/15B93B35-5F1D-4871-B695-9B895276D933_zpsy7py35pz.jpg~original","index":"0"}}]}]}

![1](https://cloud.githubusercontent.com/assets/10885041/8621599/cdbcd2aa-2726-11e5-806a-f1339232bc82.jpg)

@Ivan1985 @perisicboro @AustenB

**Comment by AustenB** [comment]
@perisicboro lets look into this one again

**Comment by perisicboro** [comment]
If you get this one again, in latest sdk version, write to me.
