### ISSUE TITLE
Lay Flat book - not all images shows on the order

### ISSUE THREAD

**Issue by offirg1** [printdotio/printio-ios-sdk#455]
I was able to create the book of 10x10 20 pages, with 12 photos, 
Order went well, I saw all the photos on the album 

When i went to the admin to look at the order photos 8 to 12 are missing

**Comment by offirg1** [comment]
Order link 
https://admin.print.io/Home#/orders/241249/images

**Comment by perisicboro** [comment]
@offirg1 this order looks ok, and all images are there. You should not pay attention on image 2 and 14, these are for vendors.
