### ISSUE TITLE
Auto-determined country occasionally null

### ISSUE THREAD

**Issue by arik-so** [printdotio/printio-ios-sdk#456]
Sometimes, the active country when opening the Print.IO dialog is null. However, a default country cannot be set, because when using the SDK method to set a country, the country becomes immutable.

**Comment by perisicboro** [comment]
@arik-so Fixed in v1.2.35-dev, not to show (null)

**Comment by arik-so** [comment]
Thanks, Boro, good to know. May I ask when that fix will be merged into master?

**Comment by perisicboro** [comment]
As soon as QA team test and verify newest version. I hope tomorrow evening. I'll inform you.

**Comment by arik-so** [comment]
Ok, thank you very much!
