### ISSUE TITLE
printIO getVersion returns nil

### ISSUE THREAD

**Issue by arik-so** [printdotio/printio-ios-sdk#457]
When running the following with an instance of PrintIO:

```objective-c
[printIO getVersion:^(PIOVersion *version) {
}];
```
all the properties of PIOVersion are either 0 or empty strings.

**Comment by perisicboro** [comment]
@arik-so Because for yours recipeId it is not set. For what do you use this?

**Comment by arik-so** [comment]
The recipe ID should definitely be set, because I set it in the previous call when I get the instance of PrintIO, which is printIO. 

To answer your question, we were contemplating using it to keep track of which version of Print.IO are users are currently using, seeing how not every release of our own may include an update of the Print.IO SDK.

**Comment by perisicboro** [comment]
That method doesn't return current version of sdk. To get what you want, use this:

```Objective-C
NSDictionary *infoDictionary = [[NSBundle bundleWithURL:[[NSBundle mainBundle] URLForResource:@"PrintIOBundle" withExtension:@"bundle"]] infoDictionary];
NSString *version = [NSString stringWithFormat:@"%@(%i)", [infoDictionary valueForKey:@"CFBundleShortVersionString"], [[infoDictionary valueForKey:@"CFBundleVersion"]intValue]];
NSLog(@"version: %@", version);
```

**Comment by arik-so** [comment]
Indeed, works like a charm.
