### ISSUE TITLE
MagGram-4-of-3inch 4 input images are expected

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#460]
Hi guys,

https://admin.print.io/Home#/orders/257576/summary

Partner: Photobucket 
Partner Email Addresses: print.support@photobucket.com printsupport@photobucket.com

Order item **has 3 input image(s)**. For SKU MagGram-4-of-3inch **4 input images are expected**.

@perisicboro @Ivan1985 @AustenB

**Comment by mkontic** [comment]
Hi guys,

We received order for Metal Magnets with only one image, when 4 are required:
https://admin.print.io/Home#/orders/258755/images

**Comment by mkontic** [comment]
Sorry, not Metal Magnets, but Magnet Grams.

**Comment by AustenB** [comment]
@mkontic @perisicboro so it happened with 1 of 4 and one with 3 of 4.

**Comment by mkontic** [comment]
@AustenB Correct.

**Comment by perisicboro** [comment]
@mkontic I think that build info was changed for this product. Check if it still happens in latest version. We were not able to recreate this bug.

**Comment by mkontic** [comment]
Ok, I'll let you know if we receive something similar from the latest version! :)
