### ISSUE TITLE
PayPal doesn't let me sign in to pay

### ISSUE THREAD

**Issue by bryanbarclay7** [printdotio/printio-ios-sdk#461]
I added the sdk to my app and I went to pay for an item using PayPal to test and it wouldn't let me sign into my account. It is the latest version of the sdk.

**Comment by perisicboro** [comment]
@bryanbarclay7 We use PayPal SDK in our SDK, so login in most cases is client's issue. Did you set clientId for PayPal?

https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--setpaypalstagingclientidproductionclientid

```Objective-C
/**
 Set PayPal's client ids, for both modes, staging and production. Default values are
 client ids from PrintIO
 https://developer.paypal.com/developer/applications/create

 @param sClientId Client ID for staging mode
 @param pClientId Client ID for production mode
 */
- (void)setPayPalStagingClientId:(NSString *)sClientId
              productionClientId:(NSString *)pClientId;
```

**Comment by bryanbarclay7** [comment]
I've created the all and I've added the sandbox and live mode. This doesn't seem to resolve the issue It seems as if something is still missing

**Comment by AustenB** [comment]
Email you initialization code to boro@print.io

**Comment by AustenB** [comment]
@bryanbarclay7 did you email the init code so we can help you follow up?

**Comment by bryanbarclay7** [comment]
Not sure I understand? 

Bryan

**Comment by perisicboro** [comment]
@bryanbarclay7 Part of code where printIO initialization is, so I can check it.

**Comment by bryanbarclay7** [comment]
Here is our part of code related to printIO initialization:

PrintIO * print = [[PrintIO alloc] initWithViewController:viewController
                                                  environment:PRINTIO_STAGING
                                           productionRecipeId:@"65c2d69b-fc40-4c5b-839d-86dcc6fced64"
                                              stagingRecipeId:@"809ddb7d-c3d6-4c44-ba75-1ef620074b84"];
    [print setPayPalStagingClientId:@"dOOqpO3FgyyAamUumaXlKH1Qo9jIaetnfWNdqgMB1fo="
                 productionClientId:@"wI2UYQNBWNzGIYFar9slbG/KcZTji81uAqBWdKXya3s="];
    [print setPaymentOptions:PaymentOptionAll];


Bryan

**Comment by AustenB** [comment]
@bryanbarclay7 Can you add me on skype to provide additional details. We are here to help. My Skype name is austenbernstein

**Comment by bryanbarclay7** [comment]
I've added you and still haven't had a response. Is this going to continue to be an issue or can you please help me get this fixed I'm about to just remove this completely from my app as this is taking a ridiculous amount of time.

**Comment by AustenB** [comment]
@bryanbarclay7 we're in touch on Skype -> We will help you figure out your issue. It isn't a bug.
