### ISSUE TITLE
Weird alert sign is showing up on some thumbnail

### ISSUE THREAD

**Issue by pesquibr** [printdotio/printio-ios-sdk#462]
Hi All. A weird alert sign is showing up on some (not all) thumbnail pictures when a user chooses to find a picture from her camera roll for a custom product. They don't show up for every product. I found it under Fleece Blanket and Framed Prints so far.

Steps to re-create:

1) Choose Fleece Blankets
2) Create it
3) Choose either size
4) Tap 'Phone' option

You'll see a screen of pictures with an alert sign in the lower left hand corner of each picture.

Thanks in advance.

![img_5741](https://cloud.githubusercontent.com/assets/1742312/9199347/4afa5d0a-4018-11e5-8943-e6e82cf6646e.PNG)
![img_5742](https://cloud.githubusercontent.com/assets/1742312/9199346/4af57b96-4018-11e5-9e26-e71a43297b63.PNG)

**Comment by AustenB** [comment]
These are resolution warnings.

On Tue, Aug 11, 2015 at 10:05 AM, pesquibr <notifications@github.com> wrote:

> Hi All. A weird alert sign is showing up on some (not all) thumbnail
> pictures when a user chooses to find a picture from her camera roll for a
> custom product. They don't show up for every product. I found it under
> Fleece Blanket and Framed Prints so far.
>
> Steps to re-create:
>
> 1) Choose Fleece Blankets
> 2) Create it
> 3) Choose either size
> 4) Tap 'Phone' option
>
> You'll see a screen of pictures with an alert sign in the lower left hand
> corner of each picture.
>
> Thanks in advance.
>
> [image: img_5741]
> <https://cloud.githubusercontent.com/assets/1742312/9199347/4afa5d0a-4018-11e5-8943-e6e82cf6646e.PNG>
> [image: img_5742]
> <https://cloud.githubusercontent.com/assets/1742312/9199346/4af57b96-4018-11e5-9e26-e71a43297b63.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/462>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by AustenB** [comment]
@pesquibr do you have something you would prefer instead?

**Comment by pesquibr** [comment]
It's all right. Thank you.
