### ISSUE TITLE
Layflat photobooks - "Save to Cart" is not responding after photo edit

### ISSUE THREAD

**Issue by mirit-keepy** [printdotio/printio-ios-sdk#463]
"Save to Cart" button is not responding once you edit one of your book's photos, so it's impossible to complete the order.

If I just select photos and make no edits, I'm able to click the button and proceed to checkout.

Testing on iPhone 6. iOS 8.4 via keepy app

@AustenB @arik-so

**Comment by AustenB** [comment]
What version of the iOS SDK is this from Printio

On Tue, Aug 11, 2015 at 5:11 PM, mirit-keepy <notifications@github.com>
wrote:

> "Save to Cart" button is not responding once you edit one of your book's
> photos, so it's impossible to complete the order.
>
> If I just select photos and make no edits, I'm able to click the button
> and proceed to checkout.
>
> Testing on iPhone 6. iOS 8.4
>
> @AustenB <https://github.com/AustenB> @arik-so
> <https://github.com/arik-so>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/463>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by mirit-keepy** [comment]
I believe we use the latest, but will only be able to confirm later tonight

**Comment by AustenB** [comment]
ok yes confirm tonight.

On Tue, Aug 11, 2015 at 6:24 PM, mirit-keepy <notifications@github.com>
wrote:

> I believe we use the latest, but will only be able to confirm later tonight
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/463#issuecomment-130096215>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by mirit-keepy** [comment]
It's confirmed - 1.2.38

**Comment by AustenB** [comment]
boro will look into it tomorrow

On Tue, Aug 11, 2015 at 6:37 PM, mirit-keepy <notifications@github.com>
wrote:

> It's confirmed - 1.2.38
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/463#issuecomment-130099322>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by Ivan1985** [comment]
@mirit-keepy @AustenB We found that issue and it's already fixed, will be available in next release

**Comment by TheTriciaRussel** [comment]
@Ivan1985 do we know when release will be so we can tell the? they need to know for marketing purposes. @mirit-keepy @jconkey @WinRisner -thanks!

**Comment by AustenB** [comment]
@mirit-keepy release is made today with this fix!

1.3.7
