### ISSUE TITLE
MagGram-6-of-2x3 - only one image produced

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#464]
Hi guys,

MagGram-6-of-2x3 - instead of 6 print images, only one is produced.

https://admin.print.io/Home#/orders/266803/summary

@perisicboro @Ivan1985 @AustenB

**Comment by perisicboro** [comment]
@Ivan1985 @ivankovicmilos Try to recreate this.

**Comment by AustenB** [comment]
@Ivan1985 any luck recreating?

**Comment by Ivan1985** [comment]
@AustenB No, we can't recreate this issue, probably they used some old version of SDK, currently Magnetgram works perfectly.
