### ISSUE TITLE
How to test payment on production environment without paying with real credit card?

### ISSUE THREAD

**Issue by offirg1** [printdotio/printio-ios-sdk#466]
How to test payment on production environment without paying with real credit card?

**Comment by AustenB** [comment]
Impossible today. You must attempt to pay with paypal and dont execute the
order.

The order will then be placed in pre-payment status in the admin.

On Thu, Aug 20, 2015 at 3:18 PM, offirg1 <notifications@github.com> wrote:

> How to test payment on production environment without paying with real
> credit card?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/466>.
>



-- 
Austen Bernstein
Founder & CEO
makeable

**Comment by offirg1** [comment]
How will I be able to see that the Order landed right to the production
environment

Offir
ᐧ

**Comment by perisicboro** [comment]
Just login to admin panel, production mode.
