### ISSUE TITLE
Unable to update to version 1.3.7

### ISSUE THREAD

**Issue by mirit-keepy** [printdotio/printio-ios-sdk#467]
When running  “pod outdated” it tells us there is a PrintIO update

Running a pod update is not updating the code.

When we force the pod file to use only  1.3.7 it fails on install saying: [!] Unable to satisfy the following requirements:

- `PrintIO (= 1.3.7)` required by `Podfile`

Please advise.
Thanks!

@AustenB

**Comment by AustenB** [comment]
@mirit-keepy Pod file should be updated shortly -> didn't know you were
using the pods for pulling

On Fri, Aug 21, 2015 at 4:03 PM, mirit-keepy <notifications@github.com>
wrote:

> When running “pod outdated” it tells us there is a PrintIO update
>
> Running a pod update is not updating the code.
>
> When we force the pod file to use only 1.3.7 it fails on install saying:
> [!] Unable to satisfy the following requirements:
>
>    - PrintIO (= 1.3.7) required by Podfile
>
> Please advise.
> Thanks!
>
> @AustenB <https://github.com/AustenB>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/467>.
>



-- 
Austen Bernstein
Founder & CEO
makeable

**Comment by mirit-keepy** [comment]
@AustenB thanks. please keep us posted. would like to include it in the version we submit to apple today.

**Comment by Ivan1985** [comment]
@mirit-keepy @AustenB It's fixed
