### ISSUE TITLE
Source code for the SDK

### ISSUE THREAD

**Issue by rughvi** [printdotio/printio-ios-sdk#468]
Hi team,
I am working to integrate the PRINTIO iOS /Android sdks into Xamarin Studio.
This is required for my app to process image printing.

Is there a way I can get the source code for the SDKs so that I can change the look and feel of the PRINTIO screens in line with that of my app screens.

Also do you have any .net / C# SDK that integrates with Xamarin Studio?

Many thanks,
Venkat V R

**Comment by AustenB** [comment]
We do not support this currently. 

You are welcome to use our api to build your own or use our SDK to make a native app.
