### ISSUE TITLE
Calendar support from the iOS SDK

### ISSUE THREAD

**Issue by offirg1** [printdotio/printio-ios-sdk#469]
Any ETA on when people can order Calendars? it's become relevant as presents for the holiday season are coming

**Comment by AustenB** [comment]
November

On Wed, Sep 2, 2015 at 8:16 PM, offirg1 <notifications@github.com> wrote:

> Any ETA on when people can order Calendars? it's become relevant as
> presents for the holiday season are coming
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/469>.
>



-- 
Austen Bernstein
Founder & CEO

**Comment by offirg1** [comment]
Ok, Thanks for the heads up
