### ISSUE TITLE
Coupon code doesn't work on checkout

### ISSUE THREAD

**Issue by fileyapp** [printdotio/printio-ios-sdk#470]
Steps to repro -
1. Added images through our app - keepy.me.
2. Checked out
3. Tried to enter the coupon code I've created, it was invalid.
4. Regenerated the coupon code and tried again, same error.

Thanks.

**Comment by AustenB** [comment]
Full details needed. What coupon was created Also screen shot the shopping
cart screen

On Thu, Sep 3, 2015 at 2:37 AM, Eli Nir <notifications@github.com> wrote:

> Steps to repro -
> 1. Added images through our app - keepy.me.
> 2. Checked out
> 3. Tried to enter the coupon code I've created, it was invalid.
> 4. Regenerated the coupon code and tried again, same error.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/470>.
>



-- 
Austen Bernstein
Founder & CEO

**Comment by fileyapp** [comment]
Thanks.
Coupon type -
One-Time use codes
Promotion
100% off
Entire order minimum $5

![2015-09-02 16 55 04](https://cloud.githubusercontent.com/assets/5760885/9647593/98fe9d36-5193-11e5-838c-2d516ad641c8.png)

**Comment by AustenB** [comment]
One time use not supported in iOS app today. We will look into if there is
any other issue here.

On Thu, Sep 3, 2015 at 2:56 AM, Eli Nir <notifications@github.com> wrote:

> Thanks.
> Coupon type -
> One-Time use codes
> Promotion
> 100% off
> Entire order minimum $5
>
> [image: 2015-09-02 16 55 04]
> <https://cloud.githubusercontent.com/assets/5760885/9647593/98fe9d36-5193-11e5-838c-2d516ad641c8.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/470#issuecomment-137276222>
> .
>



-- 
Austen Bernstein
Founder & CEO

**Comment by fileyapp** [comment]
Thanks again.

**Comment by AustenB** [comment]
@fileyapp is this a requested feature?
