### ISSUE TITLE
Paypal Checkout is paid to breakoutcommerce.com  

### ISSUE THREAD

**Issue by offirg1** [printdotio/printio-ios-sdk#471]
Our customers, doesn't need to see this. 
How do we change it to Keepy? 
You sent a payment of $4.69 USD to Breakout Commerce, Inc.
(payments@breakoutcommerce.com)

**Comment by AustenB** [comment]
You have to set up your own paypal account. Did you plug in your own
account?

On Wed, Sep 9, 2015 at 1:30 AM, offirg1 <notifications@github.com> wrote:

> Our customers, doesn't need to see this.
> How do we change it to Keepy?
> You sent a payment of $4.69 USD to Breakout Commerce, Inc.
> (payments@breakoutcommerce.com)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/471>.
>



-- 
Austen Bernstein
Founder & CEO

**Comment by perisicboro** [comment]
@offirg1 Did you try to change payee name?

https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--setpayeename

**Comment by AustenB** [comment]
@offirg1 in the docs boro pointed to the place to change the payee name.
