### ISSUE TITLE
Remove CFBundleExecutable Key

### ISSUE THREAD

**Issue by nh7a** [printdotio/printio-ios-sdk#472]
Apparently both PrintIOBundle.bundle and TextBundle.bundle need to remove CFBundleExecutable Key because it doesn’t contain a bundle excitable, and App Store doesn't allow it.  The error message at submission is "ERROR ITMS-90535: Unexpected CFBundleExecutable Key."

**Comment by AustenB** [comment]
@perisicboro any idea on this?

**Comment by nh7a** [comment]
FYI, removing the key from both bundle made the App Store submission work like a charm again. May or may not relates to Xcode 7 GM.

**Comment by perisicboro** [comment]
Fixed in v1.5.1(22)

**Comment by nh7a** [comment]
Cool. When can I see it in the Pods so that I don't have to do the hack by myself?

**Comment by tobiasfrier** [comment]
It should be a within the few hours.

Tobias Frier
Senior Product Manager
Skype: tobiasfrier
makeable.com

**Comment by nh7a** [comment]
It seems v1.5.1 hasn't been released as of right now, yet... :-(

**Comment by tobiasfrier** [comment]
I am sorry for the miscommunacation. 1.5.1 was an internal release. I will notify you when it is added to our master repo.

**Comment by perisicboro** [comment]
@nh7a Please confirm if it's fixed, and close a ticket.
