### ISSUE TITLE
Keppy Issue 

### ISSUE THREAD

**Issue by jovana-kovacevic** [printdotio/printio-ios-sdk#473]
Hi guys! 

Please see the email below and please advise:
"User Id: 2980
Username: Naoki Hiroshima

Partner Id: 504

Partner Name: Keepy Inc.

Url : https://admin.print.io/Home#/settings/teamMembers/

Message:

Having tried to submit a build to App Store, it didn't work apparently because something in Print.IO library is wrong. Please see the screenshot - https://dl.dropboxusercontent.com/spa/2nkvmiivbvscjwk/rw0ptjxw.png"

**Comment by perisicboro** [comment]
Do not use Xcode beta version to publish app. Try to use latest stable version.

**Comment by jovana-kovacevic** [comment]
Hi @perisicboro! The partner said: "How are you so sure I'm using Beta version? No, I'm not using Beta version. I'm using Xcode 7 GM."

**Comment by perisicboro** [comment]
Fixed in v1.5.1(22)

**Comment by perisicboro** [comment]
@jovana-kovacevic Confirm fix, and close the ticket.

**Comment by jovana-kovacevic** [comment]
Confirmed @perisicboro
