### ISSUE TITLE
Critical bug, - App crash also with Ver 1.5 

### ISSUE THREAD

**Issue by offirg1** [printdotio/printio-ios-sdk#474]
here is my bug: 
go to Keepy prints
choose the Keepy layflat
'creat it'
Choose options - 10X10
20 pages
Choose ANY  layout (checked with 4 different ones) 
Tap Keepy icon
Selected Keepy album
Press select all,
See the album- tap on one of the photo to replace photo
Choose the Keepy photo source
choose 7-8 photos and the app crash
app crashes
Add Comment

**Comment by AustenB** [comment]
How are you choosing 7-8 photos to replace one photo?



On Sat, Sep 12, 2015 at 2:45 AM, offirg1 <notifications@github.com> wrote:

> here is my bug:
> go to Keepy prints
> choose the Keepy layflat
> 'creat it'
> Choose options - 10X10
> 20 pages
> Choose ANY layout (checked with 4 different ones)
> Tap Keepy icon
> Selected Keepy album
> Press select all,
> See the album- tap on one of the photo to replace photo
> Choose the Keepy photo source
> choose 7-8 photos and the app crash
> app crashes
> Add Comment
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/474>.
>



-- 
Austen Bernstein
Founder & CEO

**Comment by AustenB** [comment]
Screen recordings are best for the quickest fixes.

On Sat, Sep 12, 2015 at 10:41 AM, Austen Bernstein <austen@makeable.com>
wrote:

> How are you choosing 7-8 photos to replace one photo?
>
>
>
> On Sat, Sep 12, 2015 at 2:45 AM, offirg1 <notifications@github.com> wrote:
>
>> here is my bug:
>> go to Keepy prints
>> choose the Keepy layflat
>> 'creat it'
>> Choose options - 10X10
>> 20 pages
>> Choose ANY layout (checked with 4 different ones)
>> Tap Keepy icon
>> Selected Keepy album
>> Press select all,
>> See the album- tap on one of the photo to replace photo
>> Choose the Keepy photo source
>> choose 7-8 photos and the app crash
>> app crashes
>> Add Comment
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/printdotio/printio-ios-sdk/issues/474>.
>>
>
>
>
> --
> Austen Bernstein
> Founder & CEO
>
>
>


-- 
Austen Bernstein
Founder & CEO

**Comment by AustenB** [comment]
@perisicboro will look into

**Comment by offirg1** [comment]
https://www.dropbox.com/s/tzsyyrghjraexqr/crash1.mov?dl=0

**Comment by AustenB** [comment]
Basically we need to prevent user from selecting more than 1 photo to
replace 1 photo.

Thought we solved it - but its likely low frequency. We will fix it ASAP.

On Sat, Sep 12, 2015 at 7:32 PM, offirg1 <notifications@github.com> wrote:

> https://www.dropbox.com/s/tzsyyrghjraexqr/crash1.mov?dl=0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/474#issuecomment-139828878>
> .
>



-- 
Austen Bernstein
Founder & CEO

**Comment by offirg1** [comment]
It happens also when selecting one photo sometimes

**Comment by perisicboro** [comment]
@offirg1 Does it happen always? Because I can't recreate it. Log will help if you have it.

**Comment by Ivan1985** [comment]
@offirg1 We tried to recreate this issue, but unfortunately we couldn't. Can you please tell us which version of iOS you have and which phone?

**Comment by offirg1** [comment]
Happens both on iOS 8.4 and 9 different type of phones

**Comment by perisicboro** [comment]
@offirg1 I still need log with crash

**Comment by offirg1** [comment]
@nh7a

**Comment by offirg1** [comment]
guys any update on that? from some reason the crashlytics is not catching the log when the crash happens.
This is a sample of feedback we got from dozens of customers so far 

I have tried several times to create my book and am frustrated...the app does not allow you to move pictures around, just pages, and it is pairing pictures together that I would prefer not to be placed side by side. Then, when I try to replace a picture on a page, the app crashes. Again, I have attempted to make a book several (several) times and on different days...same experience. I finally just gave up!

**Comment by AustenB** [comment]
This bug must be isolated to your photo source.

We aren't able to recreate it for some reason yet.

They want the ability to drag and drop photos between spaces. That's a
smart idea to add. We will add this to roadmap.

**Comment by ivankovicmilos** [comment]
Hello,

I downloaded Keepy app from store and try to recreate this issue. On my iPhone 6 plus (iOS 9 GM) everything works fine, I could not reproduce this crash with these steps. I used only 15 photos because uploading restriction in Keepy app (15 photos is max for this mounth)

@AustenB @perisicboro @offirg1 @tobiasfrier

**Comment by tobiasfrier** [comment]
@offirg1 

Can you please provide us with the log? We have not been able to reproduce the issue with the steps provided.

**Comment by offirg1** [comment]
We will have it today

**Comment by offirg1** [comment]
@nh7a has found that the issue is caused on our photo resource, and it related to large account with many photos. 

Offir

**Comment by tobiasfrier** [comment]
@offir thank you for informing us.
