### ISSUE TITLE
Price for 8x10 canvas does not match price set in admin dashboard

### ISSUE THREAD

**Issue by jefflipp** [printdotio/printio-ios-sdk#475]
The pricing for rectangle canvas wraps (all sizes) is incorrect in the app. An 8x10 canvas says the price is $11.82, but the customer price set on the dashboard is $21.28. Because of the discrepancy, an error message appears when you attempt to purchase a rectangular canvas wrap...screenshots attached.  

![canvas1](https://cloud.githubusercontent.com/assets/13223836/9851046/9b260114-5aab-11e5-9400-8a8931318b97.png)
![canvas2](https://cloud.githubusercontent.com/assets/13223836/9851045/9b253446-5aab-11e5-9c9f-947eab83b8bd.png)
![canvas3](https://cloud.githubusercontent.com/assets/13223836/9851047/9b2b37f6-5aab-11e5-9d78-ca231b5bce4c.png)

**Comment by tobiasfrier** [comment]
Hi Jeff,

Thanks for bring this to our attention. I'll get on this today and let you
know when the matter is resolved.

Tobias Frier
Senior Product Manager
Skype: tobiasfrier
makeable.com

**Comment by perisicboro** [comment]
@jefflipp Send me initialization code for printIO to boro@makeable.com and tell me does this issue occur in production or staging mode?

**Comment by jefflipp** [comment]
production

**Comment by perisicboro** [comment]
@jefflipp I still need initialization code

**Comment by AustenB** [comment]
Jeff,

Somehow you listed the canvas sku 2x in your recipe ID. This is the
problem.

I am not sure how this happened. We can have the Admin team take a look
into it.

Austen

On Mon, Sep 14, 2015 at 10:40 AM, perisicboro <notifications@github.com>
wrote:

> @jefflipp <https://github.com/jefflipp> I still need initialization code
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/475#issuecomment-140101960>
> .
>



-- 
Austen Bernstein
Founder & CEO

**Comment by perisicboro** [comment]
@jefflipp If it's fixed, please close the ticket.
