### ISSUE TITLE
Runs on Simulator but not on Real Device (iPhone).

### ISSUE THREAD

**Issue by fssilva** [printdotio/printio-ios-sdk#476]
Hi guys,

I'm using Xcode 7 and IOS9 but I'm getting this error when compiling for my iPhone. It works on Simulator. Does anyone know how to solve this ?

.../PrintIO/PrintIO.framework/PrintIO(ProductIds.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

PS: Print.io 1.5.0

**Comment by tobiasfrier** [comment]
@perisicboro 

can you take look at this?

**Comment by perisicboro** [comment]
@fssilva In your app target, put **Enable Bitcode** to **NO**

<img width="550" alt="screen shot 2015-09-18 at 1 44 11 pm" src="https://cloud.githubusercontent.com/assets/6410345/9958582/c1dc9b7a-5e0b-11e5-858f-b77f155ae92a.png">

**Comment by fssilva** [comment]
Are you guys going to update Print.io to support Bitcode ? Disable Bitcode is not a solution, is a quickfix.

**Comment by perisicboro** [comment]
@fssilva When all other frameworks that we use update to support bitcode, then we will make support also.

**Comment by fssilva** [comment]
Ok. Thank you.
