### ISSUE TITLE
Filter Products 

### ISSUE THREAD

**Issue by leenyburger** [printdotio/printio-ios-sdk#478]
I'd like to filter the products so the user does not have an option of product.  Very simple implementation.  The printIO page is still showing the user multiple options.   Here is the code : 
```
static NSString *const sRecipeId = @"00000000-0000-0000-0000-000000000000"; 
static NSString *const pRecipeId = @"600000000-0000-0000-0000-000000000000"; 
PrintIO *printIO = [[PrintIO alloc]initWithViewController:self environment:PRINTIO_STAGING productionRecipeId:pRecipeId stagingRecipeId:sRecipeId]; 
// Start widget 
[printIO setImages:imageArray]; 
[printIO disablePhotoSourcesWhenImagesArePassedIn:true]; 
[printIO goToProductId: PRODUCT_HARDCOVER_PHOTOBOOKS()withSKU:@"HardcoverBook-ImgWrpCover-6x6-100#GlossPaper-Glossy-20"]; 
[printIO setPreselectPassedImages:true]; 
[printIO open];
```

**Comment by perisicboro** [comment]
@leenyburger This method is not for filtering, it's purpose is only to jump to specified product, skipping selection steps.

**Comment by perisicboro** [comment]
@leenyburger To filter which products, templates etc are available for your recipeId, you have to do it in admin panel.
