### ISSUE TITLE
PRODUCT_PHOTOBOOKS() still says "come soon"

### ISSUE THREAD

**Issue by leenyburger** [printdotio/printio-ios-sdk#480]
Running in production mode, when I filter based on product photobooks 
```printIO goToProductId:PRODUCT_PHOTO_BOOKS()];```
I get the message "This product will be available soon". 

I can filter based on my dashboard, but my application has one overview page where the user can make a book, and one "postcard" page where is it appropriate for the user to create a product with one photo.  Filtering by product in the code does not seem to be working.  Any help you can provide would be appreciated.
Thanks.

**Comment by perisicboro** [comment]
@leenyburger Please send me initialization code (including recipeIds) on boro@makeable.com

**Comment by perisicboro** [comment]
@leenyburger We support only:

```Obj-C
PRODUCT_LAYFLAT_PHOTOBOOKS()
PRODUCT_HARDCOVER_PHOTOBOOKS()
PRODUCT_SOFTCOVER_PHOTOBOOKS()
PRODUCT_SELFCOVER_PHOTOBOOKS()
```

**Comment by perisicboro** [comment]
@leenyburger Verify this and close ticket if it works.
