### ISSUE TITLE
Folded Cards - are not showing Step4

### ISSUE THREAD

**Issue by offirg1** [printdotio/printio-ios-sdk#481]
When choosing the Folded card option, 
Stage 4 doesn't  show orientation option, and therefore there is no way to move to the next steps.
This is critical as we try to promote the cards for the holiday season 

Offir

**Comment by Ivan1985** [comment]
@offirg1 It's fixed, will be available in next release 1.5.17 (23)

**Comment by offirg1** [comment]
When is it planned to release ?

**Comment by Ivan1985** [comment]
@offirg1 The next release should be tomorrow.

**Comment by cthalin8** [comment]
We have the same issue with cards...cannot complete step 4.

**Comment by offirg1** [comment]
And we also have them with Iphone cases
ᐧ

**Comment by perisicboro** [comment]
@cthalin8 @offirg1 This was fixed in v1.5.17(24)
https://github.com/printdotio/printio-ios-sdk/releases/tag/1.5.17

https://github.com/printdotio/printio-ios-sdk/blob/master/ReleaseNotes.md
