### ISSUE TITLE
Confirmation emails with incorrect total

### ISSUE THREAD

**Issue by cthalin8** [printdotio/printio-ios-sdk#482]
A couple of customers have reached out because their order confirmation email made it seem as if they had ordered double.

Order 309692 was for 1 throw pillow totaling $44.95, but she received the attached confirmation email indicating the items totaled $77.54. 

The same thing happened for order 311394. 

![screen shot 2015-10-26 at 10 29 13 am](https://cloud.githubusercontent.com/assets/15328807/10736861/6e822b50-7bcc-11e5-8b8f-d2f98a16f887.png)
![screen shot 2015-10-26 at 10 29 04 am](https://cloud.githubusercontent.com/assets/15328807/10736864/7195f5ec-7bcc-11e5-9e3e-b8d4327bcd91.png)

**Comment by tobiasfrier** [comment]
@cthalin8 Thanks for bringing this to our attention. We'll get on this.

**Comment by tobiasfrier** [comment]
@cthalin8 This is a server side issue so I copied the ticket and added it to their to do list. I am also referenced in the ticket and will let you know when the matter has been resolved.

**Comment by cthalin8** [comment]
@tobiasfrier great, thank you!

**Comment by cthalin8** [comment]
@tobiasfrier do you have an ETA on when this will be fixed?

**Comment by tobiasfrier** [comment]
@cthalin8 

this was a server side issue and was just notified that the fix has already been deployed. It will be tested today or tomorrow. I will let you know more as soon as it is tested.
