### ISSUE TITLE
SDK too large

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#483]
Hi guys,

Please see the email we received from partner regarding iOS SDK:

"We are a new customer and trying to integrate your SDK into our photo 
manager. It appears though that between the few framework files, it 
comes to over 90mb. Is this correct? If so, is there a way to get rid 
of what we dont need like the other site site sdks? 90mb is just far too 
large to integrate into an existing app as is."

@tobiasfrier @perisicboro

**Comment by perisicboro** [comment]
@mkontic The size of SDK is 90mb uncompressed, when it's included in project, and built, it increases app size around 9mb.
