### ISSUE TITLE
Incorrect total cost error message 

### ISSUE THREAD

**Issue by kristinahavlovic** [printdotio/printio-ios-sdk#484]
Hi guys, our partner Keepy Inc. emailed us saying that their customer keeps getting an error message on the final screen saying: "Incorrect total cost--should have been $x

![image1](https://cloud.githubusercontent.com/assets/15343538/10845407/d84f374c-7f07-11e5-93de-1bd050d7e581.png)

Can you please look into this issue?

@perisicboro @Ivan1985 @mkontic

**Comment by mkontic** [comment]
@perisicboro Hey guys, any updates? Partner is getting impatient and his customer still can't buy anything.. Thanks!

**Comment by perisicboro** [comment]
@mkontic @kristinahavlovic I need sdk version, initialization code, exact address and product name. If it's a bug in sdk, fix will be available to customer in a two weeks.

**Comment by KeepyD** [comment]
printio-version: 1.5.0 (22)
email: amdefrein@gmail.com (dont put it public on git)
She's on iOS 9.0.1
located in Dublin, Dublin City, Ireland
Products : canvas minis, flat cards, magnetograms, metal magnets and a mousepad. 14 items in total

**Comment by KeepyD** [comment]
HELLO?

**Comment by perisicboro** [comment]
@KeepyD I need initialization code and products list in cart (screenshot or skus) so I can try to recreate this issue.

**Comment by KeepyD** [comment]
@perisicboro  What are initialization code? I will ask for a screenshot not sure she saved it but it's the 2nd time she is trying with diffrent products...

**Comment by perisicboro** [comment]
@KeepyD Initialization code for our SDK. I need to have the same working environment like it's in your application, and without exact list of products(skus) I can't recreate same environment. On that way I will find out which product is causing trouble.

**Comment by KeepyD** [comment]
![img_9228](https://cloud.githubusercontent.com/assets/15660153/11009849/40fa5394-848f-11e5-8ab5-e32addc62db7.png)
![img_9229](https://cloud.githubusercontent.com/assets/15660153/11009851/49610c26-848f-11e5-9a27-f7583d784772.png)
![img_9230](https://cloud.githubusercontent.com/assets/15660153/11009853/504a4f7a-848f-11e5-9220-10f7eca1c3f2.png)
![img_9231](https://cloud.githubusercontent.com/assets/15660153/11009856/53bc4550-848f-11e5-9cca-c9f9c3a84416.png)

**Comment by KeepyD** [comment]
@perisicboro here is what I got from my iOS Dev - 
"I don't think we can give them enough code to let them replicate the environment unless we give them A LOT of them. In other words, it's not mere "initialization code" but also a bunch of code that access to our image cache and local item cache."
Please advise ASAP!

**Comment by perisicboro** [comment]
@KeepyD I meant on piece of code where you initialize printIO sdk, set recipe ids... I don't need image cache, etc

**Comment by perisicboro** [comment]
@KeepyD I see a different prices for same skus (products):

CanvasMini-5x5  =  €7.13 and
CanvasMini-5x5  =  €4.46

also I installed keepy app and saw this:

CanvasMini-9x9  =  €12.84 and on screenshot
CanvasMini-9x9  =  €8.75

So whats going on: you changed the prices on some products before this customer made an order, and that's why he/she is getting incorrect total cost.

The only solution for this customer is to delete product(s) which have changed prices from cart, and to recreate them. In future sdk version we will make auto update of prices in cart.

**Comment by KeepyD** [comment]
ok. Thank you
