### ISSUE TITLE
ETA for intl shipping

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#485]
Hi guys,

Partner Design Luscinia - Phoetic brought this issue to my attention. 
The app states that est. arrival for international orders is 7 business days, which is incorrect.

International shipping may take up to 21 business days, depending on the domestic mail carrier and customs procedures. 

Partner said:
"It would be great if the information provided would make it clear the customer cannot expect the product to be delivered within '7 days'. 
'7 - 21' days for international shipping would be more accurate (and I will be even happy if the product arrives early!)."

Would it be possible to make this change?

@perisicboro

**Comment by tobiasfrier** [comment]
@mkontic Hi Milena,

I have added this request to our backlog. Thanks for making us aware of this.
