### ISSUE TITLE
Double Sided Card Image issues

### ISSUE THREAD

**Issue by cthalin8** [printdotio/printio-ios-sdk#486]
When ordering a double-sided card, it asks you to pick 4 images.  However when you go through the steps to edit the images, cover to the inside left and right, the image doesn’t change.  It’s not util the back cover you get a new image in there.

See attached photos and note the location at the top changes but the image doesn’t (despite 4 images being shown at bottom of screen).
![print io](https://cloud.githubusercontent.com/assets/15328807/11069061/33b92852-8789-11e5-989f-afdd16c86fe6.png)
![left](https://cloud.githubusercontent.com/assets/15328807/11069070/3b5a4956-8789-11e5-899d-33a8fa9cc971.png)
![right](https://cloud.githubusercontent.com/assets/15328807/11069074/3f9e782a-8789-11e5-9185-0767a91868e9.png)
![back](https://cloud.githubusercontent.com/assets/15328807/11069080/426d56fc-8789-11e5-9a21-d4639771087d.png)

**Comment by perisicboro** [comment]
@cthalin8 This is fixed in our next sdk release.

**Comment by perisicboro** [comment]
Our QA verified this issue.
