### ISSUE TITLE
"Pay with Apple Pay" not available in staging environment

### ISSUE THREAD

**Issue by jordansorensen** [printdotio/printio-ios-sdk#491]
When placing orders in the production environment, I see three payment options (pay with card, pay with PayPal, pay with ApplePay). In staging, however, I only see card and PayPal.
I've set up a merchant ID for my staging environment and sent it to print.io - is it possible that merchant ID was recorded incorrectly on print.io's side?

**Comment by perisicboro** [comment]
@jordansorensen Apple Pay fixes will be in next sdk version.
