### ISSUE TITLE
Release notes call setApplePayBusinessName "mandatory" but no other documentation

### ISSUE THREAD

**Issue by jordansorensen** [printdotio/printio-ios-sdk#492]
Could we get more documentation for what setApplePayBusinessName is for? The release notes call it mandatory but it's not mentioned anywhere else. How does it differ from setPayeeName?
If it really is mandatory it should probably also be added to the "Setting Up Apple Pay" docs.

**Comment by perisicboro** [comment]
@jordansorensen  All regarding issues to Apple Pay will be in next sdk version.

**Comment by jordansorensen** [comment]
Great, thanks, looking forward to it.

**Comment by perisicboro** [comment]
@jordansorensen Fixed in next sdk version, which we expect to be live this week.

**Comment by jordansorensen** [comment]
Great, thanks, looking forward to it.

**Comment by jordansorensen** [comment]
Looks like setApplePayBusinessName was removed in the latest SDK version.
