### ISSUE TITLE
useSinglePageCustomization causes crash

### ISSUE THREAD

**Issue by jordansorensen** [printdotio/printio-ios-sdk#493]
Not sure what useSinglePageCustomization is for, but wanted to try it out - crashes every time. Looks like there's code trying to edit the UI from a thread other than the main thread.
>2015-11-13 12:37:23.110 Sifterr[599:161639] This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.
> Stack:(
>0   CoreFoundation                      0x0000000184ef4f60 <redacted> + 148
>1   libobjc.A.dylib                     0x0000000199aa7f80 objc_exception_throw + 56
>2   CoreFoundation                      0x0000000184ef4e90 <redacted> + 0
>3   Foundation                          0x0000000185f132d8 <redacted> + 88
>4   Foundation                          0x0000000185d954fc <redacted> + 36
>5   UIKit                               0x000000018a58f8c4 <redacted> + 64
>6   UIKit                               0x000000018a58fb08 <redacted> + 548
>7   UIKit                               0x000000018a58f8d4 <redacted> + 80
>8   UIKit                               0x000000018a482a78 <redacted> + 240
>9   UIKit                               0x000000018a48232c <redacted> + 116
>10  UIKit                               0x000000018a4821b8 <redacted> + 504
>11  UIKit                               0x000000018a48fb0c <redacted> + 1792
>12  [myapp]                             0x00000001004a01e0 extractOBJdata + 32788
>13  [myapp]                             0x000000010049db24 extractOBJdata + 22872
>14  [myapp]                             0x0000000100359f00 payeeName + 27052
>15  libdispatch.dylib                   0x0000000100fbdca8 _dispatch_call_block_and_release + 24
>16  libdispatch.dylib                   0x0000000100fbdc68 _dispatch_client_callout + 16
>17  libdispatch.dylib                   0x0000000100fccec8 _dispatch_root_queue_drain + 2344
>18  libdispatch.dylib                   0x0000000100fcc590 _dispatch_worker_thread3 + 132
>19  libsystem_pthread.dylib             0x000000019a4d9470 _pthread_wqthread + 1092
>20  libsystem_pthread.dylib             0x000000019a4d9020 start_wqthread + 4

**Comment by perisicboro** [comment]
@jordansorensen I will need initialization code, to try to recreate this issue.

**Comment by jordansorensen** [comment]
Hm, strange, this was happening consistently and now I can't seem to reproduce it. Sorry to bother you; I'll re-open if I manage to repro this.
