### ISSUE TITLE
Doc clarification - app transport policy for production environment?

### ISSUE THREAD

**Issue by jordansorensen** [printdotio/printio-ios-sdk#494]
The docs say that we must disable App Transport Security for print.io to work. I see that this is true for the staging environment - I'm guessing because print.io has a security certificate for the server at print.io but not for the staging server.
Does this only need to be disabled for staging apps, or does it also need to be disabled for apps using the production environment? I'd strongly prefer not to ship my app with this disabled.

**Comment by perisicboro** [comment]
@jordansorensen We are not using only printio servers right now... until further this needs to be disabled.

**Comment by jordansorensen** [comment]
Okay, thanks for the clarification.

**Comment by jordansorensen** [comment]
In the meantime, is there a more limited way to carve out a security workaround for print.io? For example, is there a list of domains we could add to NSExceptionDomains instead of disabling ATS entirely?
