### ISSUE TITLE
Fleece Blankets aren't working

### ISSUE THREAD

**Issue by cthalin8** [printdotio/printio-ios-sdk#495]
Fleece Blankets aren’t working. You select “Make It” and you get a blank screen for “Choose Options”
![1](https://cloud.githubusercontent.com/assets/15328807/11326030/b3447030-9112-11e5-945e-9e00bf488c1a.png)

**Comment by perisicboro** [comment]
@cthalin8 It's fixed in next sdk version, which will be released this week.

**Comment by perisicboro** [comment]
Our QA verified this.
