### ISSUE TITLE
App crashing when Paypal is selected

### ISSUE THREAD

**Issue by cthalin8** [printdotio/printio-ios-sdk#497]
We've received a couple of complaints from users stating the app crashes when they select Paypal as their payment method. The following users experienced crashing: emmaliz21@gmail.com and debnreg.1993@yahoo.com

**Comment by cthalin8** [comment]
sheri.goade@yahoo.com also had issues with the app crashing when she selected Paypal...she ended up purchasing the order with a credit card and it went through.

**Comment by tobiasfrier** [comment]
@cthalin8 Thanks for bringing this to our attention. Does the crash when the user taps Paypal on the payment options screen? Can the user get to the PayPal screen at all?  Do you know what version of iOS they are running and which phones they are using? 

Tobias

**Comment by cthalin8** [comment]
ncory1@hotmail.com also had issues...she tried to pay with paypal three times and app crashed each time. Successfully placed an order when she used her credit card

**Comment by cthalin8** [comment]
ncory1@hotmail.com is using iPhone 7.2  iOS 2.8.3
 emmaliz21@gmail.com is using iPhone 6.1 iOS 2.8.3
debnreg.1993@yahoo.com using iPhone 7.1 iOS 2.8.3
sheri.goade@yahoo.com  using iPhone 7.2 iOS 2.8.3
