### ISSUE TITLE
HP customer not being able to order larger canvas sizes 

### ISSUE THREAD

**Issue by tamaratomovski** [printdotio/printio-ios-sdk#498]
Hi Boro!

We have a HP customer who only has the following sizes available for canvas prints:

6x6, 10x10
5x7, 8x10
10x20, 12x36

She has an iPhone 6 and has downloaded the app very recently.

Please let me know which other information you might need.

Thanks,
Tamara

@perisicboro 

![img_7063](https://cloud.githubusercontent.com/assets/10880662/11441189/d86453bc-9509-11e5-9016-381a3a851bec.PNG)
![img_7064](https://cloud.githubusercontent.com/assets/10880662/11441190/d8689814-9509-11e5-9dbe-fc5cdb5efc7e.PNG)
![img_7065](https://cloud.githubusercontent.com/assets/10880662/11441191/d869f1b4-9509-11e5-9c1f-ef78ef61c1bb.PNG)

**Comment by Ivan1985** [comment]
@tamaratomovski This is a question for Vendor team, they should enable other sizes for Canvas Wraps in HP app.

**Comment by tamaratomovski** [comment]
@Ivan1985  Thanks!
