### ISSUE TITLE
Duplicate orders - Hellopics app

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#499]
Hi guys, 

Duplicate orders, placed within 3 seconds.

https://admin.print.io/admin/#/orders/338754/summary
https://admin.print.io/admin/#/orders/338755/summary

@perisicboro

**Comment by mkontic** [comment]
More ios duplicates:
https://admin.print.io/admin/#/orders/343771/summary
https://admin.print.io/admin/#/orders/343778/summary

**Comment by perisicboro** [comment]
@mkontic Last two orders are from Photobucket iOS app. We can't do anything there, because they use very old version of our sdk. Until they upgrade it, this issue will remain.

**Comment by perisicboro** [comment]
@mkontic HelloPics update will be this week, with this bug fixed.
