### ISSUE TITLE
Block45 code not working correctly

### ISSUE THREAD

**Issue by jovana-kovacevic** [printdotio/printio-ios-sdk#500]
Hi Team!

Please see the screen shot and advise.
The customer is using the latest iPhone 6s app.
![block45](https://cloud.githubusercontent.com/assets/8796232/11608822/cffcbdb0-9b74-11e5-8983-fa8e16fdda91.png)
Thank you!

**Comment by Ivan1985** [comment]
@jovana-kovacevic Please, ask the customer which products had in shopping cart and which version of SDK is using (in side menu on the bottom is version number).
