### ISSUE TITLE
Coasters bug

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-ios-sdk#502]
Hi guys,

It looks like we have a bug with coasters.
As you can see, we have 2 items in this order, One is for Coaster with 4 images and other for coaster with 8 images.

For first item (4 image), this is the print ready image:
http://app-imgs.print.io/img-manip/151207-22191148c0b28dbc-c.jpeg

For second item (8 images):
http://app-imgs.print.io/img-manip/151207-22191536f5419b7e-a.jpeg

As you can see, last 4 images are missing from the second item. Please advise.

https://admin.print.io/admin/#/orders/356213/summary

@perisicboro

**Comment by Ivan1985** [comment]
@tobiasfrier  @mkontic We don't have Coasters with 8 images into SDK, I have to check what is going on. As you can see SKU's are the same for both items

**Comment by mkontic** [comment]
Yup, noticed it as well. Not sure how and why, but customer actually thought she got duplicates, so I'm guessing app used some images twice..
