### ISSUE TITLE
Makeable Privacy Policy

### ISSUE THREAD

**Issue by jordansorensen** [printdotio/printio-ios-sdk#503]
Because the Makeable SDK collects personal information, it should have a privacy policy that describes how that personal information can be used and shared. Our app has a privacy policy of its own, but we need to be able to refer to Makeable's policy as one of the third party policies that users agree to when they use the app's "order prints" feature.
I see HelloPics has a [privacy policy](http://www.hellopics.com/privacy) - does this privacy policy also apply to users of the Makeable SDK? If so, could it be updated to use the company's new name?

**Comment by tobiasfrier** [comment]
@jordansorensen 

The hellopics privacy policy does not extend to the the Makeable SDK. I will have to speak to our senior management about drafting a new privacy policy for the Makeable SDK.

**Comment by jordansorensen** [comment]
Thanks a ton for looking into this - any updates?
