### ISSUE TITLE
Multiple declarations of method in PrintIO.h

### ISSUE THREAD

**Issue by koppacetic** [printdotio/printio-ios-sdk#504]
In release 1.6.5, the PrintIO.h file has two declarations of

-(void)setShowsAddMoreProductsInShoppingCart:(BOOL)showsAddButton;

The second declaration marks the method as deprecated. Which one is correct?

This causes a compiler warning every time the PrintIO.h file is imported.

**Comment by tobiasfrier** [comment]
@koppacetic Thanks for bring this to our attention. We'll have a look a this tomorrow.

**Comment by perisicboro** [comment]
@koppacetic @tobiasfrier This is fixed in our next version v1.6.10(27) which will be released on Monday 25.

**Comment by koppacetic** [comment]
Verified fixed.
