### ISSUE TITLE
No Help button for side menu

### ISSUE THREAD

**Issue by koppacetic** [printdotio/printio-ios-sdk#505]
In previous releases of the SDK I was able to add a Help button to the side menu which pointed to a URL on our web site. That does not seem possible in the new SDK. There is no PIOSMButtonTypeHelp.

Has that functionality been removed? If not, how would I do that using the new side menu system?

FYI, here's how I did it in previous releases:

    PIOSideMenuButton *helpButton = [[PIOSideMenuButton alloc]initWithTitle:@"HELP"
                                                                       type:PIO_SM_HELP];
    helpButton.dataHolder = @"http://support.photobucket.com/hc/en-us/categories/200154330";

    [self.printIO sideMenuAddButtons:@[helpButton]
                         options:nil
                    optionsTitle:@"Options"
               optionsTitleColor:[UIColor blackColor]
                    optionsColor:[UIColor pb_ios7style_grey3]
                   accountsTitle:@"Accounts"
              accountsTitleColor:[UIColor blackColor]
                   accountsColor:[UIColor pb_ios7style_grey3]
                            info:nil
                       infoTitle:@"Info"
                  infoTitleColor:[UIColor blackColor]
                       infoColor:[UIColor pb_ios7style_grey3]
       backgroundImageForButtons:[[NSBundle mainBundle] pathForResource:@"pb_bcg" ofType:@"png"]];

The sideMenuAddButtons method does not seem to work at all anymore. I know it's deprecated but it should still work.

**Comment by perisicboro** [comment]
@koppacetic Fixed. In next sdk update, this fix will be available. You can use new method to set Help button:

```
PIOSideMenuButton *helpButton = [[PIOSideMenuButton alloc]initWithTitle:@"HELP" type:PIOSMButtonTypeHelp];
helpButton.dataHolder = @"http://support.photobucket.com/hc/en-us/categories/200154330";

[self.printIO setSideMenuItems:@[helpButton]];

**Comment by perisicboro** [comment]
Our QA verified this.
