### ISSUE TITLE
side menu navigation bar title

### ISSUE THREAD

**Issue by sebnun** [printdotio/printio-ios-sdk#508]
Hi, I can't seem to find documentation to change the navigation bar title on some side menu items. Is this possible?

I want to change the navigation bar title of "quality guarantee", "how it works" and "about us".
Currently those titles are "Makeable".

I'm using the release 1.6.10(28). 
Thanks

**Comment by tobiasfrier** [comment]
@sebnun 
This is not possible yet but will be available in an upcoming release.

**Comment by perisicboro** [comment]
@sebnun Actually, you can change the title. Use this method:

```
/**
 Set payee name for order processing

 @param payeeName Payee name
 */
-(void)setPayeeName:(NSString *)payeeName;
```
