### ISSUE TITLE
SDK photo upload with wrong resolutions?

### ISSUE THREAD

**Issue by sebnun** [printdotio/printio-ios-sdk#510]
I'm new to makeable, I don't know if this is an issue with the SDK or the backend, or I'm using the SDK wrong.

I ordered the SKU Greet-Fold-3.5x5-Dull-Single-1Pack, which requires images at least 1087x1575.
I uploaded 2 images 3264x2448 from the camera, I didn't see a red icon on the bottom left when selecting the photos. The order purchase completed fine. 

On the admin site the status went from "new" to "ReadyForImageDl" to "ImageIssue"
The message I see is "Image with a higher resolution should be uploaded to ensure great product quality."

The manipulation command for both images is 

`{"commands":[{"name":"combine","args":{"map":"0=+0+0,1=+0+0"}}],"settings":{"color":"#ffffff","width":"1087","height":"1575"},"name":"canvas","layers":[{"commands":[{"name":"combine","args":{"map":"0=-46+0"}}],"settings":{"index":"0","width":"1087","height":"1575","color":"#ffffff"},"name":"canvas","layers":[{"commands":[{"name":"affine","args":{"matrix":"1.1806597,0.0000000,0.0000000,1.1806597,0.0000000,0.0000000"}}],"name":"image","settings":{"uri":"https://printio-api.s3.amazonaws.com/7c95a3d43......jpg","index":"0"}}]},{"name":"text","settings":{"index":"1","font":"opensans","width":1087,"verticalAlign":"middle","originY":0,"color":"#ffffff","size":92.0668,"text":"","height":1575,"horizontalAlign":"center","originX":0,"allowWordBreak":true}}]}`

the AWS image from the manipulation command is 1000x1334

To check with a different product I ordered the SKU FlatCard-4x6-Finch-Single-1Pack and it's the same. The required image should be at least 1275x1875, and I uploaded a 3264x2448 photo.
the manipulation command is 

`{"commands":[{"name":"combine","args":{"map":"0=+0+0,1=+0+0"}}],"settings":{"color":"#ffffff","width":"1275","height":"1875"},"name":"canvas","layers":[{"commands":[{"name":"combine","args":{"map":"0=-65+0"}}],"settings":{"index":"0","width":"1275","height":"1875","color":"#ffffff"},"name":"canvas","layers":[{"commands":[{"name":"affine","args":{"matrix":"1.4055471,0.0000000,0.0000000,1.4055471,0.0000000,0.0000000"}}],"name":"image","settings":{"uri":"https://printio-api.s3.amazonaws.com/93d2b49d25f4bec0c8603c.....jpg","index":"0"}}]},{"name":"text","settings":{"index":"1","font":"opensans","width":1275,"verticalAlign":"middle","originY":0,"color":"#ffffff","size":109.6033,"text":"","height":1875,"horizontalAlign":"center","originX":0,"allowWordBreak":true}}]}`

the AWS image in this order is also 1000X1334

Why my orders have the status "imageIssue" with the message "Image with a higher resolution should be uploaded to ensure great product quality." ?

thanks

**Comment by micahasmith** [comment]
hey @sebnun, forward this one to partnersupport@print.io since it involves multiple platforms pls.

i'll help make sure it gets routed from there. thanks!
