### ISSUE TITLE
Order 396112 - images didn't generate

### ISSUE THREAD

**Issue by jovana-kovacevic** [printdotio/printio-ios-sdk#511]
Hi team!

Could you please review this order and let us know what was the problem with generating images for it? It's not "opensans" issue.
Thank you!
https://admin.print.io/admin#/orders/396112/images

**Comment by perisicboro** [comment]
@jovana-kovacevic I need imgmanip command (Manipulation command).

**Comment by jovana-kovacevic** [comment]
Image 1: {"name":"canvas","commands":[{"args":{"map":"0=+0+2600,1=+0+1300,2=+0+0,3=+1300+2600,4=+1300+1300,5=+1300+0,6=+2600+2600,7=+2600+1300,8=+2600+0,9=+0+0"},"name":"combine"},{"args":{"format":"jpg"},"index":"999","name":"convert"},{"args":{"value":"100"},"name":"quality"}],"layers":[{"name":"canvas","commands":[{"args":{"map":"0=-888-751"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/eddd03e027ab1bde9d0405b2cbab0b7cce80233bfcf8a5bc89506201bc1ee8dc.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"2.6327076,0.0000000,0.0000000,2.6327076,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"0"}},{"name":"canvas","commands":[{"args":{"map":"0=-317+0"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/24cff6150ff9d42e902e76c47790888bb1c43b95a522771afc29ec0eabeb0153.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"2.1398628,0.0000000,0.0000000,2.1398628,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"1"}},{"name":"canvas","commands":[{"args":{"map":"0=-249-109"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/cd6a58d7b02e65ffe89697c3e3e56417905b999caaa52224edb6a69cca45218d.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.7190804,0.0000000,0.0000000,1.7190804,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"2"}},{"name":"canvas","commands":[{"args":{"map":"0=-219-219"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/678c7cf5476857c2652b524df91b7fd8b9c6a7e423fdb0bdce72de08e539d239.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.5310575,0.0000000,0.0000000,1.5310575,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"3"}},{"name":"canvas","commands":[{"args":{"map":"0=-106-190"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/6fc8adfb7c882e682a8d8a12a8de945ed85ee0b915a56dc0bd475bc434094711.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"2.3842840,0.0000000,0.0000000,2.3842840,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"4"}},{"name":"canvas","commands":[{"args":{"map":"0=+0+0"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/5999d3de7e852fecc0f91b5e4b2195b5f6457ececfb476c7983eabd9b2dd31e3.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.1443663,0.0000000,0.0000000,1.1443663,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"5"}},{"name":"canvas","commands":[{"args":{"map":"0=-241-34"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/ebd7ab81b392007791fbf01d074f06efe0ecbbb3b2a53b8eb0a109432037459f.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.5385973,0.0000000,0.0000000,1.5385973,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"6"}},{"name":"canvas","commands":[{"args":{"map":"0=+0-115"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/21e607ad3082b5416adfde24caa15863ad8569db321618086fa9ea2914e13c1a.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.7038007,0.0000000,0.0000000,1.7038007,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"7"}},{"name":"canvas","commands":[{"args":{"map":"0=-381+0"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/74688e59b06b15a59e6e9726953c44b9cf47620c5052f984b4882da66a9f3f60.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.5348843,0.0000000,0.0000000,1.5348843,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"8"}},{"settings":{"color":"#ffffff","size":379.1667,"font":"opensans","text":"","originY":0,"allowWordBreak":true,"verticalAlign":"middle","height":3900,"horizontalAlign":"center","index":"9","width":3900,"originX":0},"name":"text"}],"settings":{"color":"","width":"3900","height":"3900"}}

Image 2: {"name":"canvas","commands":[{"args":{"map":"0=+0+2600,1=+0+1300,2=+0+0,3=+1300+2600,4=+1300+1300,5=+1300+0,6=+2600+2600,7=+2600+1300,8=+2600+0,9=+0+0"},"name":"combine"},{"args":{"format":"jpg"},"index":"999","name":"convert"},{"args":{"value":"100"},"name":"quality"}],"layers":[{"name":"canvas","commands":[{"args":{"map":"0=+0+0"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/2b3297697e487cf36fefe4024e5c21c9501788489f4f4b05303ee2c2cc9bbe94.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.1443663,0.0000000,0.0000000,1.1443663,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"0"}},{"name":"canvas","commands":[{"args":{"map":"0=+0+0"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/2b3297697e487cf36fefe4024e5c21c9501788489f4f4b05303ee2c2cc9bbe94.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.1443663,0.0000000,0.0000000,1.1443663,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"1"}},{"name":"canvas","commands":[{"args":{"map":"0=+0+0"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/2b3297697e487cf36fefe4024e5c21c9501788489f4f4b05303ee2c2cc9bbe94.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.1443663,0.0000000,0.0000000,1.1443663,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"2"}},{"name":"canvas","commands":[{"args":{"map":"0=+0-69"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/112aafabb66a3c468ee757b8e8039534520ff1c7ce9564f3d9ef330a6bbf2d86.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.5258217,0.0000000,0.0000000,1.5258217,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"3"}},{"name":"canvas","commands":[{"args":{"map":"0=+0+0"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/227cf2d9969d6cac1867cfe9a3093abe07b4907cdec2f2dba31078a5cc77c028.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.1443663,0.0000000,0.0000000,1.1443663,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"4"}},{"name":"canvas","commands":[{"args":{"map":"0=+0-206"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/6dda63afe35e9020697130ddbf527689fa7436716903ce5705d72c0eec946f7a.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"2.4074078,0.0000000,0.0000000,2.4074078,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"5"}},{"name":"canvas","commands":[{"args":{"map":"0=+0+0"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/2b3297697e487cf36fefe4024e5c21c9501788489f4f4b05303ee2c2cc9bbe94.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.1443663,0.0000000,0.0000000,1.1443663,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"6"}},{"name":"canvas","commands":[{"args":{"map":"0=+0+0"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/2b3297697e487cf36fefe4024e5c21c9501788489f4f4b05303ee2c2cc9bbe94.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.1443663,0.0000000,0.0000000,1.1443663,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"7"}},{"name":"canvas","commands":[{"args":{"map":"0=+0+0"},"name":"combine"}],"layers":[{"settings":{"uri":"https://printio-api.s3.amazonaws.com/2b3297697e487cf36fefe4024e5c21c9501788489f4f4b05303ee2c2cc9bbe94.jpg","index":"0"},"name":"image","commands":[{"args":{"matrix":"1.1443663,0.0000000,0.0000000,1.1443663,0.0000000,0.0000000"},"name":"affine"}]}],"settings":{"height":"1300","width":"1300","color":"","index":"8"}},{"settings":{"color":"#ffffff","size":379.1667,"font":"opensans","text":"","originY":0,"allowWordBreak":true,"verticalAlign":"middle","height":3900,"horizontalAlign":"center","index":"9","width":3900,"originX":0},"name":"text"}],"settings":{"color":"","width":"3900","height":"3900"}}

**Comment by perisicboro** [comment]
@jovana-kovacevic Are you sure that these commands are from order above?

**Comment by mkontic** [comment]
Boro, please open the order, second item, # 1145791.

**Comment by perisicboro** [comment]
ok. remove this from imgmanip   "allowWordBreak":true,

**Comment by perisicboro** [comment]
@Ivan1985 See what's going on with pillows without text.

**Comment by jovana-kovacevic** [comment]
@perisicboro Thanks, all good now.

**Comment by perisicboro** [comment]
@jovana-kovacevic @mkontic If you get more orders like this, you dont need to remove `"allowWordBreak":true` just replace `"name":"text"` with `"name":"text2"` and it will work, until we fix this bug.
