### ISSUE TITLE
Only one image generated for magnets

### ISSUE THREAD

**Issue by stefanbognar** [printdotio/printio-ios-sdk#516]
This order ended up as a vendorapi issue because not enough images generated for magnets

https://admin.print.io/admin/#/orders/408370/summary

This SKU is expected to have 4 images.

**Comment by perisicboro** [comment]
@stefanbognar This is very old version of iOS SDK, v19, and we are now on version v30, but anyway we will investigate this issue. @Ivan1985 @ivankovicmilos

**Comment by Ivan1985** [comment]
@stefanbognar @perisicboro This is correct behaviour. 

Use case 1: If user add only one image without changing number of copies on Customization screen, order will have only one image for printing. 

Use case 2: If user add only one image and change number of copies to max per set on Customization screen, order will have exactly the same images for printing as added into SDK.
