### ISSUE TITLE
Hellopics order with images that didn't generate

### ISSUE THREAD

**Issue by tamaratomovski** [printdotio/printio-ios-sdk#517]
Hi guys,

this Hellopics order has a number of items for which the images didn't generate.
When I open the manipulation command for these, it is not showing the image at all.

order: https://www.gooten.com/admin#/orders/426643/images

I have cancelled this order and given the customer a coupon to place it from the beginning, however, you should look into this :)

Thank you!

@perisicboro @Ivan1985 

![image 2](https://cloud.githubusercontent.com/assets/10880662/14017615/ff4c5a94-f1c8-11e5-808d-ca6127cc2a31.png)

**Comment by perisicboro** [comment]
@Ivan1985 Please open issue on ios private board, and try to recreate it.

**Comment by Ivan1985** [comment]
@tamaratomovski @perisicboro Ok, it will be investigated

**Comment by tamaratomovski** [comment]
@perisicboro  @Ivan1985  Thanks guys!
