### ISSUE TITLE
"Help" side menu button

### ISSUE THREAD

**Issue by sebnun** [printdotio/printio-ios-sdk#518]
Hi, currently the "Help" button on the side menu doesn't work (it does nothing when tapped) and I could not find a method to set the text of this item on the documentation.

I'm using the release 1.7.22.

Which method do I have to use to enable it? Thanks

![simulator screen shot apr 23 2016 8 25 22 pm](https://cloud.githubusercontent.com/assets/11248929/14764531/9570f310-0991-11e6-86e9-915918f8eb48.png)

**Comment by perisicboro** [comment]
@sebnun You can set it on this way:

```Objective-C
NSArray *defaultItems = [self.printIO defaultSideMenuItems];
NSMutableArray *sideMenuItems = [[NSMutableArray alloc]initWithArray:defaultItems];
NSArray *helpBtnArr = [sideMenuItems filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:[NSString stringWithFormat:@"SELF.type==%li", (long)PIOSMButtonTypeHelp]]];
        
PIOSideMenuButton *helpButton = [helpBtnArr firstObject];
helpButton.dataHolder = @"http://www.gooten.com"; //  url for help page
[self.printIO setSideMenuItems:sideMenuItems];
```
