### ISSUE TITLE
Incorrectly generated image - order 458660

### ISSUE THREAD

**Issue by jovana-kovacevic** [printdotio/printio-ios-sdk#519]
Hi team!

Could you please review this order and let me know why was this generated that way?
I updated the image manipulation command initially (removed "~original" from it, to see if the preview at 100% will match the product preview).
Thank you!

https://www.gooten.com/admin#/orders/458660/summary

**Comment by ivankovicmilos** [comment]
@jovana-kovacevic unable to reporduce this issue on our side. Tried with phone, facebook, instagram and few PB accounts. Also, I downloaded all images from "broken" orded, made order with same images and everything is ok on our end
