### ISSUE TITLE
Flip flops - Keepy 

### ISSUE THREAD

**Issue by jovana-kovacevic** [printdotio/printio-ios-sdk#520]
Hi team!

Please see the question we received from Keepy:

"Flip Flop looks like should be available on iOS but the photo on the app shows coming soon, can you help?"

Please advise, thank you!

**Comment by ivankovicmilos** [comment]
@jovana-kovacevic I assume that they have some older versions (32 is first version with Flip Flop)  and that the reason why Flip Flops are "comming soon". They need to update SDK with newest version. 

Ask them, which version they are using at the moment. I think they are using 24

**Comment by jovana-kovacevic** [comment]
Hi @ivankovicmilos !

Thanks, I assumed that might be the case, but I still wanted to check with you. I asked the partner which version is he using and I'll get back to you as soon as possible.

**Comment by perisicboro** [comment]
@jovana-kovacevic If this issue is fixed, please close the ticket.

**Comment by jovana-kovacevic** [comment]
Hi @perisicboro 
He didn't get back to us, but I told him to update the SDK, so I'm guessing he fixed it. I'll close the ticket.
Have a great day!
