### ISSUE TITLE
Facebook login prompt  NSURLErrorDomain error -999

### ISSUE THREAD

**Issue by aliehanani** [printdotio/printio-ios-sdk#521]
Upon launch, once navigated to Facebook log-in or for it photo-source, am prompted with the error **"The operation couldn't be completed. (NSURLErrorDomain error -999)**." Shortly after, the app returns to a blank screen with no actions available and I am forced to close. 

There are arbitrarily cases in which it does not prompt the error and allows you to log-in successfully. Though, closing and reopening the app may cause the same error to occur. 

I've tried different physical iDevices, apart from the simulator, yet same results. Research on the internet, regarding the error, also have not work. Though, today I did receive an alert from Facebook Developers that my app is making:  **"_API calls to Graph API v2.0, which will reach the end of the 2-year deprecation window on Monday, August 8, 2016. Please migrate all calls to v2.1 or higher in order to avoid potential broken experiences."_** Please advise.

**Comment by perisicboro** [comment]
@aliehanani Are you using our default Facebook settings? In next sdk version, we will migrate to v2.1.

**Comment by aliehanani** [comment]
Yes, that's correct.

**Comment by perisicboro** [comment]
@aliehanani Please send me initialization code for SDK, so I can try to recreate this issue.  boro@gooten.com

**Comment by perisicboro** [comment]
@aliehanani Sent you an email.

**Comment by aliehanani** [comment]
@perisicboro Thanks for the follow-up. Am starting to believe it an environment issue on my end, as the HelloPics app prompts the same error on the same iPhone, briefly, but allows you to log into FB.
