### ISSUE TITLE
Build issue in Xcode

### ISSUE THREAD

**Issue by phoenix377** [printdotio/printio-ios-sdk#523]
Hi, thank you for the great plugin.
I tried to run this by following QuickStart guide.
I've installed SDK using Pod and when I try to run it as specified in guide, it generates error
      Undefined symbols for architecture x86_64:
           "_OBJC_CLASS_$_PrintIO", referenced from:
           objc-class-ref in ViewController.o
Could you please tell me why such error occurred?

**Comment by perisicboro** [comment]
@phoenix377 Can you send me log on boro@gooten.com

**Comment by phoenix377** [comment]
@perisicboro I've sent log to boro@gooten.com

**Comment by perisicboro** [comment]
@phoenix377 I tried to recreate this issue, but unsuccessfully. I made two new test projects, one in ObjC and other in Swift, added pod file with PrintIO, and  installed it. Everything works as expected. Please try to reinstall PrintIO, or check project build setting. Also try to run it on real device.

**Comment by phoenix377** [comment]
@perisicboro I can not find the setup document in latest version, so I've used the setup document in version 1.8.1 - https://github.com/printdotio/printio-ios-sdk/blob/ed99cd17d7ea6dee9f3da9cdcd9b2232f3bf2f1a/docs/Step-1-project_setup.md
When I use SDK version 1.8.1, then it works without problem.
But with version 1.8.10 and 1.8.12, I get the above error in simulator and device both.

**Comment by perisicboro** [comment]
@phoenix377 It's safe to use 1.8.1, until I find a solution for latest release.

**Comment by Stjng** [comment]
I get exactly the same error with @phoenix377 . Please fix :)

**Comment by perisicboro** [comment]
@phoenix377 @Stjng Are you integrating sdk into new project or existing? If it's a new project, can you send it to boro@gooten.com, if not please send me ```xcodeproj``` file.

**Comment by Stjng** [comment]
I get the same error in the lastest version and ver 1.8.1 ( tried using Pod and Drag ). Here is my xcodeproj and xcworkspace
[ColorApp.xcodeproj.zip](https://github.com/printdotio/printio-ios-sdk/files/385667/ColorApp.xcodeproj.zip)
[ColorApp.xcworkspace.zip](https://github.com/printdotio/printio-ios-sdk/files/385668/ColorApp.xcworkspace.zip)

**Comment by perisicboro** [comment]
@Stjng @phoenix377 I found the cause of issue, working on fix. I'll inform you as soon as I release new version, hope it will be later today. Thanx for help!

**Comment by Stjng** [comment]
@perisicboro  thanks for your support. Waiting for new version 👍

**Comment by phoenix377** [comment]
@perisicboro That's great. Thank you.

**Comment by perisicboro** [comment]
@phoenix377 @Stjng New version just released v1.8.14(35), on Git and CocoaPods. Use quick start guide to integrate sdk: 
https://github.com/printdotio/printio-ios-sdk/blob/master/docs/quick_start_guide.md

Please confirm that this issue is fixed. Feel free to ask for any help.

**Comment by Stjng** [comment]
@perisicboro  Worked like a charm. Thanks very much 👍
