### ISSUE TITLE
Directly add UIImage to Gooten Photo Source

### ISSUE THREAD

**Issue by Stjng** [printdotio/printio-ios-sdk#524]
How to directly add an UIImage created by my App to Gooten Photo Source. I only find the way that i need to export the Image to Device and then choose from Phone Source.
Btw, do i able to use Gooten SDK via API, not via the webview? Ex: get list posters, canvas to print, post an order Form with our image and payment via Apple Pay, v..v...

**Comment by perisicboro** [comment]
@Stjng You can use [setImages](https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md#--setimages) function, or to create [custom photo source](https://github.com/printdotio/printio-ios-sdk/blob/master/docs/Photo-Sources/custom_photo_sources.md) 

We are working on Gooten Core SDK, without UI, just the thing you're talking about, where you'll be able to get all stuffs you need to create an order. I'll let you know when we release it public.

**Comment by perisicboro** [comment]
@Stjng Example how to use ```setImages``` 
```Objective-C
NSMutableArray *photoSources = [[NSMutableArray alloc]init];
[photoSources addObject:[[PIOSideMenuButton alloc]initWithType:PIO_SM_INSTAGRAM]];
[photoSources1 addObject:[[PIOSideMenuButton alloc]initWithType:PIO_SM_PASSED_PHOTOS]];
    
[self.printIO setAvailablePhotoSources:photoSources];
[self.printIO setImages:images];
```

**Comment by Stjng** [comment]
@perisicboro  Thanks for help! But i don't find any class `PIOSideMenuButton` ( only `PIOSideMenuButtons`), i'm using Swift.
Whatever, i founds another method `disablePhotoSourcesForOnePhotoTemplate` to direct use my added images. Thanks again :)
