### ISSUE TITLE
Broken framework search path override in podspec

### ISSUE THREAD

**Issue by berendo** [printdotio/printio-ios-sdk#528]
The following lines in the podspec for CocoaPods integration:

https://github.com/printdotio/printio-ios-sdk/blob/91abd2395680d4a8b56a8ed09d4f38a5ca08fe47/PrintIO.podspec#L37-L39

override the framework search paths incorrectly (and unncecessarily) and interfere with compiling with other frameworks provided via CocoaPods. For example, merely adding the line:
```
  pod 'PrintIO'
```
to our existing `Podfile`, results in compilation failing with headers related to Twitter's Crashlytics framework not being found via the project's precompiled prefix header:
```
.../Disneyland-Prefix.pch:15:13: fatal error: 'Crashlytics/Crashlytics.h' file not found
    #import <Crashlytics/Crashlytics.h>
            ^
1 error generated.
```
Using a local copy of the `PrintIO.podspec` with the lines overriding `FRAMEWORK_SEARCH_PATHS` and `OTHER_LDFLAGS` removed results in successful compilation, _including_ use of the PrintIO framework.

Those lines should be removed from the podspec file and the `pod` command should be left to its elements to set up the search paths for frameworks. In case it's relevant to reproducing this issue, `pod --version` reports `1.2.1`.

**Comment by perisicboro** [comment]
With next sdk update, we will take a look at this issue.

**Comment by perisicboro** [comment]
Fixed.

**Comment by berendo** [comment]
Thanks! The latest `PrintIO.podspec` works great.
