### ISSUE TITLE
Order is created with incorrect shipping charge

### ISSUE THREAD

**Issue by herebcs** [printdotio/printio-ios-sdk#531]
In 1.8.41 most Apple Pay issues were fixed, however there is one security hole remaining. During check out with Apple Pay if somebody selects a shipping address that does not match the country chosen on the product screen, then the order is created with an incorrect shipping cost. The cost is based on the country selected on the product screen and not the country where the order will be shipped to. If somebody finds this out then she/he is able to order items with shipping charge smaller than the one intended.
Cannot such orders be rejected with an error message? Or - alternatively - the shipping charge should be updated to reflect the real country in the shipping address.

thanks,
Csaba

**Comment by perisicboro** [comment]
@herebcs we will fix this asap.

**Comment by perisicboro** [comment]
@herebcs Fixed in v 1.8.42(38)
