### ISSUE TITLE
Setting language code doesn't seem to work

### ISSUE THREAD

**Issue by berendo** [printdotio/printio-ios-sdk#532]
We have:
```
        printIO?.setCountryCode("JP")
        printIO?.setLanguageCode("ja")
```
right after instantiating `PrintIO` and before invoking `open` on it. Alas, the UI still comes up in English:

![image](https://user-images.githubusercontent.com/1772903/29695176-1e9b5d44-88f6-11e7-8ca7-9346288f8459.png)

I've tried German and French as well, and none of them seemed to work. Am I doing something wrong?

**Comment by berendo** [comment]
Also, is there a definitive document on which languages actually have translations?

**Comment by perisicboro** [comment]
At this moment, only 'en'.
