### ISSUE TITLE
iPad crash when changing country for shipping address 

### ISSUE THREAD

**Issue by sfranusic** [printdotio/printio-ios-sdk#533]
**Summary**

After selecting a product, and while at the checking out step of purchasing the product, if you change the country for the shipping address a crash is observed. This appears to only affect iPads.

**Steps to reproduce**

1. From the Gooten UI select a product to make.
2. Tap Check Out button.
3. On the Add Address view tap the text field for country.
4. Tap Yes to confirm.

Expected: View should appear to allow you to select a new shipping country.

Observed: App crashes.

**Comment by perisicboro** [comment]
@sfranusic is it universal app?

**Comment by sfranusic** [comment]
Yes, the app is set to universal. 

I should also mention explicitly that when following these steps to reproduce listed above the crash is observed on iPad, but **not** on iPhone.
