### ISSUE TITLE
Back arrow in title bar is huge on iOS 11

### ISSUE THREAD

**Issue by herebcs** [printdotio/printio-ios-sdk#535]
iOS 11 displays the back arrow in the navigation bar magnified. It really looks ugly :(

**Comment by ivankovicmilos** [comment]
Hello @herebcs 

Can you please share screenshot and to tell us on which devices this happens?

thanks

**Comment by herebcs** [comment]
Hi,
it happens on any device, both real and simulator. Here is a screenshot of one of the affected screens. Please note that the search icon is also shifted, which makes the text overlap the cancel button. 
Unfortunately the same icon appears on many other screens as well.
(I changed the colour of the icons to white, but the same issue happens with the original bundle as well).

thanks!
![2017-09-20_15-16-18](https://user-images.githubusercontent.com/23424115/30645905-7ecba18e-9e17-11e7-9913-6e3af02b195c.png)

**Comment by herebcs** [comment]
I investigated this a little bit further. It turned out that iOS 11 has different logic when displaying navigation bar icons. On iOS 10 the navigation bar icon used to be scaled to 42x25 points. On the other hand, iOS 11 displays the icon without any scaling (pixel/point conversion happens in both cases, though).
As there are no @2x icons in the bundle, the max resolution that produces similarly looking icons under both OS versions is 42x25 pixels. After scaling the icon (icon_back_a.png) to this size and overwriting the original one in the bundle with that the problem seems to be solved.

**Comment by alex-vasenin** [comment]
@ivankovicmilos same problem

**Comment by perisicboro** [comment]
Fixed in latest release.
