### ISSUE TITLE
Question: adding multiple products to the cart?

### ISSUE THREAD

**Issue by alex-vasenin** [printdotio/printio-ios-sdk#536]
Hello,

I managed to point the SDK to single particular product with PointIO.go(toProductId:withSKU:) and set image with PointIO.setImages(). I'm looking for a way to add multiple products to the cart along with images. Is it even possible?

P.S. I found a method PointIO.setShoppingCartContent(), but I don't see the images in JSON from PointIO.shoppingCartJSONContent()

Thanks,
Alex

**Comment by perisicboro** [comment]
@alex-vasenin It's not possible at this moment, to add complete product to cart.
