### ISSUE TITLE
Enhancement: Push Notifications 

### ISSUE THREAD

**Issue by reinormand** [printdotio/printio-ios-sdk#92]
Check the Zazzle app. They send push notifications when the item is purchased, shipped, etc. it makes the customer feel more comfortable with the purchase and it might even decrease support calls.

**Comment by perisicboro** [comment]
@reinormand How to use push notifications in our sdk:
https://github.com/printdotio/printio-ios-sdk/blob/master/docs/Reference/PUSH_NOTIFICATIONS.md
